In [2]:
!pip install pdfplumber

Defaulting to user installation because normal site-packages is not writeable
Collecting pdfplumber
  Downloading pdfplumber-0.11.10-py3-none-any.whl.metadata (43 kB)
Collecting pdfminer.six==20260107 (from pdfplumber)
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: Pillow>=12.2.0 in c:\users\rachel\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pdfplumber) (12.3.0)
Collecting pypdfium2>=5.9.0 (from pdfplumber)
  Downloading pypdfium2-5.13.0-py3-none-win_amd64.whl.metadata (67 kB)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\rachel\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pdfminer.six==20260107->pdfplumber) (3.5.1)
Collecting cryptography>=36.0.0 (from pdfminer.six==20260107->pdfplumber)
  Downloading cryptography-50.0.1-cp311-abi3-win_amd64.whl.metadata (4.3 kB)
Collecting cffi>=2.0.0 (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber)
  Using cached cffi-2.1.1-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Downloading pdfplumber-0.11.10-py3-none-any.whl (60 kB)
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.6 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.6 MB 220.7 kB/s eta 0:00:28
   --- ------------------------------------ 0.5/6.6 MB 220.7 kB/s eta 0:00:28
   --- ------------------------------------ 0.5/6.6 MB 220.7 kB/s eta 0:00:28
   --- ------------------------------------ 0.5/6.6 MB 220.7 kB/s eta 0:00:28
   ---- ----------------------------------- 0.8/6.6 MB 239.6 kB/s eta 0:00:25
   ---- ----------------------------------- 0.8/6.6 MB 239.6 kB/s eta 0:00:25
   ---- ----------------------------------- 0.8/6.6 MB 239.6 kB/s eta 0:00:25
   ------ --------------------------------- 1.0/6.6 MB 251.7 kB/s eta 0:00:23
   ------ --------------------------------- 1.0/6.6 MB 251.7 kB/s eta 0:00:23
   ------ --------------------------------- 1.0/6.6 MB 251.7 kB/s eta 0:00:23
   ------ --------------------------------- 1.0/6.6 MB 251.7 kB/s eta 0:00:23
   ------ --------------------------------- 1.0/6.6 MB 251.7 kB/s eta 0:00:23
   ------- -------------------------------- 1.3/6.6 MB 258.1 kB/s eta 0:00:21
   ------- -------------------------------- 1.3/6.6 MB 258.1 kB/s eta 0:00:21
   ------- -------------------------------- 1.3/6.6 MB 258.1 kB/s eta 0:00:21
   --------- ------------------------------ 1.6/6.6 MB 274.1 kB/s eta 0:00:19
   ----------- ---------------------------- 1.8/6.6 MB 286.8 kB/s eta 0:00:17
   ----------- ---------------------------- 1.8/6.6 MB 286.8 kB/s eta 0:00:17
   ----------- ---------------------------- 1.8/6.6 MB 286.8 kB/s eta 0:00:17
   ----------- ---------------------------- 1.8/6.6 MB 286.8 kB/s eta 0:00:17
   ----------- ---------------------------- 1.8/6.6 MB 286.8 kB/s eta 0:00:17
   ------------ --------------------------- 2.1/6.6 MB 271.9 kB/s eta 0:00:17
   ------------ --------------------------- 2.1/6.6 MB 271.9 kB/s eta 0:00:17
   ------------ --------------------------- 2.1/6.6 MB 271.9 kB/s eta 0:00:17
   ------------ --------------------------- 2.1/6.6 MB 271.9 kB/s eta 0:00:17
   -------------- ------------------------- 2.4/6.6 MB 276.2 kB/s eta 0:00:16
   -------------- ------------------------- 2.4/6.6 MB 276.2 kB/s eta 0:00:16
   -------------- ------------------------- 2.4/6.6 MB 276.2 kB/s eta 0:00:16
   -------------- ------------------------- 2.4/6.6 MB 276.2 kB/s eta 0:00:16
   --------------- ------------------------ 2.6/6.6 MB 275.0 kB/s eta 0:00:15
   --------------- ------------------------ 2.6/6.6 MB 275.0 kB/s eta 0:00:15
   --------------- ------------------------ 2.6/6.6 MB 275.0 kB/s eta 0:00:15
   --------------- ------------------------ 2.6/6.6 MB 275.0 kB/s eta 0:00:15
   --------------- ------------------------ 2.6/6.6 MB 275.0 kB/s eta 0:00:15
   ----------------- ---------------------- 2.9/6.6 MB 273.7 kB/s eta 0:00:14
   ----------------- ---------------------- 2.9/6.6 MB 273.7 kB/s eta 0:00:14
   ----------------- ---------------------- 2.9/6.6 MB 273.7 kB/s eta 0:00:14
   ----------------- ---------------------- 2.9/6.6 MB 273.7 kB/s eta 0:00:14
   ------------------- -------------------- 3.1/6.6 MB 272.2 kB/s eta 0:00:13
   ------------------- -------------------- 3.1/6.6 MB 272.2 kB/s eta 0:00:13
   ------------------- -------------------- 3.1/6.6 MB 272.2 kB/s eta 0:00:13
   ------------------- -------------------- 3.1/6.6 MB 272.2 kB/s eta 0:00:13
   -------------------- ------------------- 3.4/6.6 MB 273.9 kB/s eta 0:00:12
   -------------------- ------------------- 3.4/6.6 MB 273.9 kB/s eta 0:00:12
   ---------------------- ----------------- 3.7/6.6 MB 272.6 kB/s eta 0:00:11
   ---------------------- ----------------- 3.7/6.6 MB 272.6 kB/s eta 0:00:11
   ---------------------- ----------------- 3.7/6.6 MB 272.6 kB/s eta 0:00:11
   ----------------------- ---------------- 3.9/6.6 MB 269.7 kB/s eta 0:00:10
   ----------------------- ---------------- 3.9/6.6 MB 269.7 kB/s eta 0:00:10
   ----------------------- ---------------- 3.9/6.6 MB 269.7 kB/s eta 0:00:10
   ----------------------- ---------------- 3.9/6.6 MB 269.7 kB/s eta 0:00:10
   --------------------------- ------------ 4.5/6.6 MB 260.6 kB/s eta 0:00:09
   --------------------------- ------------ 4.5/6.6 MB 260.6 kB/s eta 0:00:09
   --------------------------- ------------ 4.5/6.6 MB 260.6 kB/s eta 0:00:09
   --------------------------- ------------ 4.5/6.6 MB 260.6 kB/s eta 0:00:09
   ---------------------------- ----------- 4.7/6.6 MB 260.5 kB/s eta 0:00:08
   ---------------------------- ----------- 4.7/6.6 MB 260.5 kB/s eta 0:00:08
   ---------------------------- ----------- 4.7/6.6 MB 260.5 kB/s eta 0:00:08
   ---------------------------- ----------- 4.7/6.6 MB 260.5 kB/s eta 0:00:08
   ---------------------------- ----------- 4.7/6.6 MB 260.5 kB/s eta 0:00:08
   ---------------------------- ----------- 4.7/6.6 MB 260.5 kB/s eta 0:00:08
   ---------------------------- ----------- 4.7/6.6 MB 260.5 kB/s eta 0:00:08
   ------------------------------ --------- 5.0/6.6 MB 247.5 kB/s eta 0:00:07
   ------------------------------ --------- 5.0/6.6 MB 247.5 kB/s eta 0:00:07
   ------------------------------ --------- 5.0/6.6 MB 247.5 kB/s eta 0:00:07
   ------------------------------ --------- 5.0/6.6 MB 247.5 kB/s eta 0:00:07
   ------------------------------- -------- 5.2/6.6 MB 246.5 kB/s eta 0:00:06
   ------------------------------- -------- 5.2/6.6 MB 246.5 kB/s eta 0:00:06
   ------------------------------- -------- 5.2/6.6 MB 246.5 kB/s eta 0:00:06
   ------------------------------- -------- 5.2/6.6 MB 246.5 kB/s eta 0:00:06
   --------------------------------- ------ 5.5/6.6 MB 244.9 kB/s eta 0:00:05
   --------------------------------- ------ 5.5/6.6 MB 244.9 kB/s eta 0:00:05
   --------------------------------- ------ 5.5/6.6 MB 244.9 kB/s eta 0:00:05
   ---------------------------------- ----- 5.8/6.6 MB 244.2 kB/s eta 0:00:04
   ---------------------------------- ----- 5.8/6.6 MB 244.2 kB/s eta 0:00:04
   ---------------------------------- ----- 5.8/6.6 MB 244.2 kB/s eta 0:00:04
   ---------------------------------- ----- 5.8/6.6 MB 244.2 kB/s eta 0:00:04
   ---------------------------------- ----- 5.8/6.6 MB 244.2 kB/s eta 0:00:04
   ------------------------------------ --- 6.0/6.6 MB 240.8 kB/s eta 0:00:03
   ------------------------------------ --- 6.0/6.6 MB 240.8 kB/s eta 0:00:03
   ------------------------------------ --- 6.0/6.6 MB 240.8 kB/s eta 0:00:03
   ------------------------------------ --- 6.0/6.6 MB 240.8 kB/s eta 0:00:03
   ------------------------------------ --- 6.0/6.6 MB 240.8 kB/s eta 0:00:03
   -------------------------------------- - 6.3/6.6 MB 241.0 kB/s eta 0:00:02
   -------------------------------------- - 6.3/6.6 MB 241.0 kB/s eta 0:00:02
   -------------------------------------- - 6.3/6.6 MB 241.0 kB/s eta 0:00:02
   -------------------------------------- - 6.3/6.6 MB 241.0 kB/s eta 0:00:02
   -------------------------------------- - 6.3/6.6 MB 241.0 kB/s eta 0:00:02
   ---------------------------------------- 6.6/6.6 MB 240.0 kB/s eta 0:00:00
Downloading pypdfium2-5.13.0-py3-none-win_amd64.whl (3.9 MB)
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.9 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.9 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.9 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.9 MB 381.6 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/3.9 MB 381.6 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/3.9 MB 381.6 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/3.9 MB 381.6 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/3.9 MB 381.6 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/3.9 MB 381.6 kB/s eta 0:00:09
   -------- ------------------------------- 0.8/3.9 MB 289.3 kB/s eta 0:00:11
   -------- ------------------------------- 0.8/3.9 MB 289.3 kB/s eta 0:00:11
   -------- ------------------------------- 0.8/3.9 MB 289.3 kB/s eta 0:00:11
   ---------- ----------------------------- 1.0/3.9 MB 301.4 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/3.9 MB 301.4 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/3.9 MB 301.4 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/3.9 MB 301.4 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/3.9 MB 301.4 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/3.9 MB 301.4 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/3.9 MB 301.4 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/3.9 MB 301.4 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/3.9 MB 244.9 kB/s eta 0:00:11
   ---------------- ----------------------- 1.6/3.9 MB 290.2 kB/s eta 0:00:08
   ---------------- ----------------------- 1.6/3.9 MB 290.2 kB/s eta 0:00:08
   ---------------- ----------------------- 1.6/3.9 MB 290.2 kB/s eta 0:00:08
   ---------------- ----------------------- 1.6/3.9 MB 290.2 kB/s eta 0:00:08
   ------------------ --------------------- 1.8/3.9 MB 289.3 kB/s eta 0:00:08
   ------------------ --------------------- 1.8/3.9 MB 289.3 kB/s eta 0:00:08
   ------------------ --------------------- 1.8/3.9 MB 289.3 kB/s eta 0:00:08
   ------------------ --------------------- 1.8/3.9 MB 289.3 kB/s eta 0:00:08
   ------------------ --------------------- 1.8/3.9 MB 289.3 kB/s eta 0:00:08
   --------------------- ------------------ 2.1/3.9 MB 285.7 kB/s eta 0:00:07
   --------------------- ------------------ 2.1/3.9 MB 285.7 kB/s eta 0:00:07
   --------------------- ------------------ 2.1/3.9 MB 285.7 kB/s eta 0:00:07
   --------------------- ------------------ 2.1/3.9 MB 285.7 kB/s eta 0:00:07
   ------------------------ --------------- 2.4/3.9 MB 290.5 kB/s eta 0:00:06
   ------------------------ --------------- 2.4/3.9 MB 290.5 kB/s eta 0:00:06
   ------------------------ --------------- 2.4/3.9 MB 290.5 kB/s eta 0:00:06
   -------------------------- ------------- 2.6/3.9 MB 290.9 kB/s eta 0:00:05
   -------------------------------- ------- 3.1/3.9 MB 293.9 kB/s eta 0:00:03
   -------------------------------- ------- 3.1/3.9 MB 293.9 kB/s eta 0:00:03
   -------------------------------- ------- 3.1/3.9 MB 293.9 kB/s eta 0:00:03
   -------------------------------- ------- 3.1/3.9 MB 293.9 kB/s eta 0:00:03
   -------------------------------- ------- 3.1/3.9 MB 293.9 kB/s eta 0:00:03
   -------------------------------- ------- 3.1/3.9 MB 293.9 kB/s eta 0:00:03
   -------------------------------- ------- 3.1/3.9 MB 293.9 kB/s eta 0:00:03
   ----------------------------------- ---- 3.4/3.9 MB 261.8 kB/s eta 0:00:02
   ----------------------------------- ---- 3.4/3.9 MB 261.8 kB/s eta 0:00:02
   ----------------------------------- ---- 3.4/3.9 MB 261.8 kB/s eta 0:00:02
   ----------------------------------- ---- 3.4/3.9 MB 261.8 kB/s eta 0:00:02
   ----------------------------------- ---- 3.4/3.9 MB 261.8 kB/s eta 0:00:02
   ----------------------------------- ---- 3.4/3.9 MB 261.8 kB/s eta 0:00:02
   ----------------------------------- ---- 3.4/3.9 MB 261.8 kB/s eta 0:00:02
   ----------------------------------- ---- 3.4/3.9 MB 261.8 kB/s eta 0:00:02
   ------------------------------------- -- 3.7/3.9 MB 239.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.7/3.9 MB 239.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.7/3.9 MB 239.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.7/3.9 MB 239.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.7/3.9 MB 239.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.7/3.9 MB 239.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.7/3.9 MB 239.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.7/3.9 MB 239.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.7/3.9 MB 239.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.7/3.9 MB 239.7 kB/s eta 0:00:01
   ---------------------------------------- 3.9/3.9 MB 219.6 kB/s eta 0:00:00
Downloading cryptography-50.0.1-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.8 MB 310.6 kB/s eta 0:00:11
   ----- ---------------------------------- 0.5/3.8 MB 310.6 kB/s eta 0:00:11
   ----- ---------------------------------- 0.5/3.8 MB 310.6 kB/s eta 0:00:11
   ----- ---------------------------------- 0.5/3.8 MB 310.6 kB/s eta 0:00:11
   ----- ---------------------------------- 0.5/3.8 MB 310.6 kB/s eta 0:00:11
   -------- ------------------------------- 0.8/3.8 MB 281.9 kB/s eta 0:00:11
   -------- ------------------------------- 0.8/3.8 MB 281.9 kB/s eta 0:00:11
   -------- ------------------------------- 0.8/3.8 MB 281.9 kB/s eta 0:00:11
   -------- ------------------------------- 0.8/3.8 MB 281.9 kB/s eta 0:00:11
   -------- ------------------------------- 0.8/3.8 MB 281.9 kB/s eta 0:00:11
   ---------- ----------------------------- 1.0/3.8 MB 259.4 kB/s eta 0:00:11
   ---------- ----------------------------- 1.0/3.8 MB 259.4 kB/s eta 0:00:11
   ---------- ----------------------------- 1.0/3.8 MB 259.4 kB/s eta 0:00:11
   ---------- ----------------------------- 1.0/3.8 MB 259.4 kB/s eta 0:00:11
   ---------- ----------------------------- 1.0/3.8 MB 259.4 kB/s eta 0:00:11
   ------------- -------------------------- 1.3/3.8 MB 256.1 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/3.8 MB 256.1 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/3.8 MB 256.1 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/3.8 MB 256.1 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/3.8 MB 256.1 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/3.8 MB 256.1 kB/s eta 0:00:10
   ---------------- ----------------------- 1.6/3.8 MB 237.6 kB/s eta 0:00:10
   ---------------- ----------------------- 1.6/3.8 MB 237.6 kB/s eta 0:00:10
   ---------------- ----------------------- 1.6/3.8 MB 237.6 kB/s eta 0:00:10
   ---------------- ----------------------- 1.6/3.8 MB 237.6 kB/s eta 0:00:10
   ---------------- ----------------------- 1.6/3.8 MB 237.6 kB/s eta 0:00:10
   ---------------- ----------------------- 1.6/3.8 MB 237.6 kB/s eta 0:00:10
   ------------------- -------------------- 1.8/3.8 MB 204.2 kB/s eta 0:00:10
   ------------------- -------------------- 1.8/3.8 MB 204.2 kB/s eta 0:00:10
   ------------------- -------------------- 1.8/3.8 MB 204.2 kB/s eta 0:00:10
   --------------------- ------------------ 2.1/3.8 MB 199.4 kB/s eta 0:00:09
   --------------------- ------------------ 2.1/3.8 MB 199.4 kB/s eta 0:00:09
   --------------------- ------------------ 2.1/3.8 MB 199.4 kB/s eta 0:00:09
   --------------------- ------------------ 2.1/3.8 MB 199.4 kB/s eta 0:00:09
   --------------------- ------------------ 2.1/3.8 MB 199.4 kB/s eta 0:00:09
   ------------------------ --------------- 2.4/3.8 MB 200.0 kB/s eta 0:00:08
   ------------------------ --------------- 2.4/3.8 MB 200.0 kB/s eta 0:00:08
   ------------------------ --------------- 2.4/3.8 MB 200.0 kB/s eta 0:00:08
   ------------------------ --------------- 2.4/3.8 MB 200.0 kB/s eta 0:00:08
   ------------------------ --------------- 2.4/3.8 MB 200.0 kB/s eta 0:00:08
   ------------------------ --------------- 2.4/3.8 MB 200.0 kB/s eta 0:00:08
   ------------------------ --------------- 2.4/3.8 MB 200.0 kB/s eta 0:00:08
   --------------------------- ------------ 2.6/3.8 MB 197.9 kB/s eta 0:00:07
   --------------------------- ------------ 2.6/3.8 MB 197.9 kB/s eta 0:00:07
   --------------------------- ------------ 2.6/3.8 MB 197.9 kB/s eta 0:00:07
   --------------------------- ------------ 2.6/3.8 MB 197.9 kB/s eta 0:00:07
   --------------------------- ------------ 2.6/3.8 MB 197.9 kB/s eta 0:00:07
   ------------------------------ --------- 2.9/3.8 MB 197.8 kB/s eta 0:00:05
   ------------------------------ --------- 2.9/3.8 MB 197.8 kB/s eta 0:00:05
   ------------------------------ --------- 2.9/3.8 MB 197.8 kB/s eta 0:00:05
   ------------------------------ --------- 2.9/3.8 MB 197.8 kB/s eta 0:00:05
   ------------------------------ --------- 2.9/3.8 MB 197.8 kB/s eta 0:00:05
   ------------------------------ --------- 2.9/3.8 MB 197.8 kB/s eta 0:00:05
   -------------------------------- ------- 3.1/3.8 MB 198.9 kB/s eta 0:00:04
   -------------------------------- ------- 3.1/3.8 MB 198.9 kB/s eta 0:00:04
   -------------------------------- ------- 3.1/3.8 MB 198.9 kB/s eta 0:00:04
   ----------------------------------- ---- 3.4/3.8 MB 206.9 kB/s eta 0:00:03
   ----------------------------------- ---- 3.4/3.8 MB 206.9 kB/s eta 0:00:03
   ----------------------------------- ---- 3.4/3.8 MB 206.9 kB/s eta 0:00:03
   -------------------------------------- - 3.7/3.8 MB 213.8 kB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 213.8 kB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 217.2 kB/s eta 0:00:00
Downloading cffi-2.1.1-cp312-cp312-win_amd64.whl (185 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: pypdfium2, pycparser, cffi, cryptography, pdfminer.six, pdfplumber
Successfully installed cffi-2.1.1 cryptography-50.0.1 pdfminer.six-20260107 pdfplumber-0.11.10 pycparser-3.0 pypdfium2-5.13.0

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: C:\Users\Rachel\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
import pdfplumber

Checking the PDF

In [4]:
pdf_path = "2023-PROCUREMENT-PLAN.pdf"

with pdfplumber.open(pdf_path) as pdf:
    print("Number of pages:", len(pdf.pages))

Number of pages: 2

Inspecting the first page

In [5]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[0]
    text = page.extract_text()
    print(text)

Entity Chirundu Town Council
Procurement Plan for year 2023
Version 3
Procurement Budget 35673707.95
ZMW Control Total 35673707.95
Date Last Updated 26-06-23 15:42
Comments Consolidated Procurement Plan
ZMW Estimated Budget FX Budget Amount Estimated dates
Class UNSPSC IFMIS GL AccountDescription Ref No Project CodeUnit of MeasureQuantityGOZ Other Total CurrencyAmount Source of FuPnrdeqsualificaPtiroonc u(Yre/Nm)enPtu Mbleictahtoiodn Award
non consulting services 82100000 0Advertising and publicity 1 Each 18300 18300 Local ResouNrces sb 17-02-23 22-02-23
goods 51000000 0Relief, repartriation and burial of destitutes 2 Each 25950 25950 Local ResouNrces sb 09-03-23 14-03-23
goods 49000000 0Staff welfare and recreation 3 Each 91080 91080 Local ResouNrces sb 14-03-23 20-03-23
non consulting services 76121600 0waste and refuse collection 4 Each 580555 580555 Local ResouNrces sb 10-01-23 16-01-23
goods 39110000 0fixtures and fittings ( Procurement of Electricals and carpenterly materials)5 Each 32400 32400 Local ResouNrces sb 09-03-23 14-03-23
non consulting services 83121703 0internet charges 6 Each 74400 74400 Local ResouNrces db 22-01-23 25-01-23
non consulting services 60104904 0electricity charges 7 Each 158400 158400 Local ResouNrces db 30-01-23 31-01-23
goods 72130000 0Utilization of CDF Funds -2023 8 Each 17882261.3 17882261 CDF N obn 17-03-23 14-04-23
goods 72130000 0construction of a double storey office block 9 Each 250000 250000 EqualisationN fund/local s bresources 15-03-23 22-03-23
goods 72130000 0Maintenance and grading of roads 10 Each 630000 630000 Ward FundN sb 20-03-23 11-04-24
goods 20121400 0make Zambia Clean -Procurement of refreshments 11 Each 93900 93900 Local ResouNrces sb 20-01-23 24-01-23
goods 20121400 0tools and equipment(procurement of slashers, hoes, cutters,wheelbarrows1 e2tc) Each 58670 58670 Local ResouNrces sb 03-04-23 06-04-23
goods 46180000 0Protective clothing 13 Each 95525 95525 Local ResouNrces sb 12-04-23 14-04-23
goods 26101805 0Auto spares 14 Each 100000 100000 Local ResouNrces sb 15-02-23 20-02-23
goods 25172500 0Tyres for motor vehicles 15 Each 39000 39000 Local ResouNrces sb 03-03-23 07-03-23
goods 39111500 0Street light Equipment maintenence 16 Each 137700 137700 Local ResouNrces sb 03-05-23 08-05-23
goods 31162800 0Road Mantenance Materials 17 Each 294000 294000 Local ResouNrces sb 18-05-23 23-05-23
goods 14111509 0Various stationery 18 Each 425292 425292 Local ResouNrces sb 03-03-23 07-03-23
goods 44000000 0office eqipment 19 Each 40000 40000 Local ResouNrces sb 03-03-23 07-03-23
goods 56101700 0procurement of office furniture 20 Each 229800 229800 Local ResouNrces sb 11-04-23 14-04-23
goods 60102300 0Procurement of books, newspapers,magazines 21 Each 11250 11250 Local ResouNrces sb 03-02-23 07-02-23
goods 56101700 0office fittings (uphostering of office tables and chairs) 22 Each 20000 2000 Local ResouNrces sb 10-10-23 13-10-23
goods 72000000 0Building maintenance materials 23 Each 74020 74020 Local ResouNrces sb 29-03-23 03-04-23
goods 49101700 0Procurement of various materials for labour day 24 Each 58800 588800 Local ResouNrces sb 19-04-23 24-04-23
goods 15000000 0Petrol,oil and lubricants for local and travelling out 25 Each 200160 200160 Local ResouNrces sb 04-01-23 09-01-23
goods 41100000 0cleaning materials 26 Each 32700 32700 Local ResouNrces sb 10-01-23 13-01-23
non consulting services 41114200 0printing 27 Each 7000 7000 Local ResouNrces sb 06-06-23 13-06-23
non consulting services 81110000 0Data processing services 28 Each 73500 73500 Local ResouNrces db 16-02-23 20-02-23
goods 53102705 0public functions and ceremonies 29 Each 113700 113700 Local ResouNrces sb 06-10-23 09-10-23
works 70111713 0bush clearing and grass cutting 30 Each 67840 67840 Local ResouNrces sb 14-02-23 17-02-23
goods 43211500 0computers,periferials,equipment 31 Each 143001 143001 Local ResouNrces sb 03-04-23 11-04-23
goods 41103011 0Refrigerator, TV, CVR, Cameras 32 Each 41500 41500 Local ResouNrces sb 18-04-23 21-04-23
non consulting services 83111500 0Telephone,fax,telex,radio 33 Each 7000 7000 Local ResouNrces sb 08-06-23 13-06-23
goods 83101506 0water treatment chimicals 34 Each 278100 278100 Local ResouNrces sb 27-04-23 02-05-23
goods 47101600 0water reticulations 35 Each 95830 95830 Local ResouNrces sb 27-04-23 02-05-23
goods 43211507 0Conference,Serminars and workshops 36 Each 59040 59040 Local ResouNrces sb 17-02-23 21-02-23
non consulting services 48000000 0survey and mapping 37 Each 41460 41460 Local ResouNrces sb 01-08-23 04-08-23
works 72130000 0Construction of a staff house, ablution block and driiling equipping of a sola3r8 borehole at VerEua Cclhinic- 2022 CDF Project 1211834.95 1211835 2022 CDF N obn 27-04-23 26-05-23
goods 25161507 0procurement of a block making machine 39 Each 800000 800000 EqualizationN fund sb 22-05-23 24-05-23
works 72130000 0Construction of ablution block at the truck park 40 Each 150000 150000 EquilizationN fund sb 17-07-23 26-07-23
goods 25100000 0procurement of an Ambulance 41 Each 1789320 1789320 2023 CDF N obn 10-07-23 08-08-23
goods 25100000 0procurement of a garbage compactor truck 42 Each 1808560 1808560 2023 CDF N obn 17-07-23 18-08-23
works 72130000 0Construction of 3 sanitation facilities at Mission, T-Junction and Yellow Jack4e3t Each 1597084.53 1597085 2023 CDF N obn 18-08-23 15-09-23
works 25161507 0Procurement of desks for various Schools 44 Each 1032000 1032000 2023 CDF N obn 07-07-23 04-08-23
works 72130000 0construction of martenity wings at Chibende Clinic 45 Each 983302.99 983303 2023 CDF N sb 13-06-23 23-06-23
works 72130000 0drilling and equipping of solar powered borehle at Nabbanda Clinic 46 Each 351033 351033 2023 CDF N sb 18-09-23 29-09-23
works 72130000 0water reticulation in Kanengumbo, kandunga and mandenga village 47 Each 946394.18 946394.2 2023 CDF N sb 18-09-23 29-09-23
works 72130000 0water reticulation in chilindi, machavika, chibulameenda from siamaundu t4o8siabulendo Each 1910044.5 1910044 2023 CDF N obn 29-09-23 27-10-23
works 72130000 0Construction of a domitory, Cooking area and drilling and equipping of a so4lo9r borehole at NgE'aocmhbe Ilende Secondary School 2146000 2146000 2022/2023 CNDF obn 17-07-23 18-08-23

Checking the Tables

In [6]:
with pdfplumber.open(pdf_path) as pdf:
    tables = pdf.pages[0].extract_tables()
    print("Tables found:", len(tables))

Tables found: 0

Inspecting the word position

In [7]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[0]
    words = page.extract_words()

    for word in words[:100]:
        print(
            word["text"],
            "x0 =", round(word["x0"], 1),
            "top =", round(word["top"], 1)
        )

Entity x0 = 52.1 top = 83.7
Chirundu x0 = 113.3 top = 83.7
Town x0 = 133.3 top = 83.7
Council x0 = 145.8 top = 83.7
Procurement x0 = 52.1 top = 90.4
Plan x0 = 80.4 top = 90.4
for x0 = 90.5 top = 90.4
year x0 = 97.7 top = 90.4
2023 x0 = 164.5 top = 90.4
Version x0 = 52.1 top = 97.1
3 x0 = 172.1 top = 97.1
Procurement x0 = 52.1 top = 103.9
Budget x0 = 80.4 top = 103.9
35673707.95 x0 = 148.1 top = 103.9
ZMW x0 = 52.1 top = 110.6
Control x0 = 64.5 top = 110.6
Total x0 = 80.9 top = 110.6
35673707.95 x0 = 148.1 top = 110.6
Date x0 = 52.1 top = 117.3
Last x0 = 63.0 top = 117.3
Updated x0 = 72.4 top = 117.3
26-06-23 x0 = 143.8 top = 117.3
15:42 x0 = 163.2 top = 117.3
Comments x0 = 52.1 top = 124.0
Consolidated x0 = 113.3 top = 124.0
Procurement x0 = 141.2 top = 124.0
Plan x0 = 169.5 top = 124.0
ZMW x0 = 461.4 top = 137.5
Estimated x0 = 473.7 top = 137.5
Budget x0 = 495.5 top = 137.5
FX x0 = 548.3 top = 137.5
Budget x0 = 554.4 top = 137.5
Amount x0 = 570.2 top = 137.5
Estimated x0 = 661.1 top = 137.5
dates x0 = 682.9 top = 137.5
Class x0 = 52.1 top = 144.2
UNSPSC x0 = 113.3 top = 144.2
IFMIS x0 = 177.0 top = 144.2
GL x0 = 189.7 top = 144.2
AccountDescription x0 = 196.3 top = 144.2
Ref x0 = 341.2 top = 144.2
No x0 = 349.2 top = 144.2
Project x0 = 377.1 top = 144.2
CodeUnit x0 = 392.9 top = 144.2
of x0 = 416.0 top = 144.2
MeasureQuantityGOZ x0 = 421.4 top = 144.2
Other x0 = 500.7 top = 144.2
Total x0 = 524.5 top = 144.2
CurrencyAmount x0 = 548.3 top = 144.2
Source x0 = 589.8 top = 144.2
of x0 = 605.0 top = 144.2
FuPnrdeqsualificaPtiroonc x0 = 610.4 top = 144.2
u(Yre/Nm)enPtu x0 = 646.5 top = 144.2
Mbleictahtoiodn x0 = 665.6 top = 144.2
Award x0 = 689.3 top = 144.2
non x0 = 52.1 top = 150.9
consulting x0 = 61.2 top = 150.9
services x0 = 83.5 top = 150.9
82100000 x0 = 154.5 top = 150.9
0Advertising x0 = 211.0 top = 150.9
and x0 = 240.3 top = 150.9
publicity x0 = 249.1 top = 150.9
1 x0 = 372.2 top = 150.9
Each x0 = 406.0 top = 150.9
18300 x0 = 485.7 top = 150.9
18300 x0 = 533.3 top = 150.9
Local x0 = 589.8 top = 150.9
ResouNrces x0 = 601.5 top = 150.9
sb x0 = 637.3 top = 150.9
17-02-23 x0 = 668.6 top = 150.9
22-02-23 x0 = 696.1 top = 150.9
goods x0 = 52.1 top = 157.6
51000000 x0 = 154.5 top = 157.6
0Relief, x0 = 211.0 top = 157.6
repartriation x0 = 230.1 top = 157.6
and x0 = 257.6 top = 157.6
burial x0 = 266.5 top = 157.6
of x0 = 279.6 top = 157.6
destitutes x0 = 285.0 top = 157.6
2 x0 = 372.2 top = 157.6
Each x0 = 406.0 top = 157.6
25950 x0 = 485.7 top = 157.6
25950 x0 = 533.3 top = 157.6
Local x0 = 589.8 top = 157.6
ResouNrces x0 = 601.5 top = 157.6
sb x0 = 637.3 top = 157.6
09-03-23 x0 = 668.6 top = 157.6
14-03-23 x0 = 696.1 top = 157.6
goods x0 = 52.1 top = 164.4
49000000 x0 = 154.5 top = 164.4
0Staff x0 = 211.0 top = 164.4
welfare x0 = 226.6 top = 164.4
and x0 = 243.4 top = 164.4
recreation x0 = 252.3 top = 164.4
3 x0 = 372.2 top = 164.4
Each x0 = 406.0 top = 164.4
91080 x0 = 485.7 top = 164.4
91080 x0 = 533.3 top = 164.4
Local x0 = 589.8 top = 164.4
ResouNrces x0 = 601.5 top = 164.4

In [8]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[0]
    words = page.extract_words()

    targets = [
        "Class",
        "Description",
        "Total",
        "Source",
        "Procureme",
        "Award"
    ]

    for word in words:
        if any(target.lower() in word["text"].lower() for target in targets):
            print(
                word["text"],
                "x0 =", round(word["x0"], 1),
                "top =", round(word["top"], 1)
            )

Procurement x0 = 52.1 top = 90.4
Procurement x0 = 52.1 top = 103.9
Total x0 = 80.9 top = 110.6
Procurement x0 = 141.2 top = 124.0
Class x0 = 52.1 top = 144.2
AccountDescription x0 = 196.3 top = 144.2
Total x0 = 524.5 top = 144.2
Source x0 = 589.8 top = 144.2
Award x0 = 689.3 top = 144.2
Procurement x0 = 259.7 top = 177.8
bresources x0 = 639.2 top = 204.7
-Procurement x0 = 257.3 top = 218.2
equipment(procurement x0 = 237.3 top = 224.9
0procurement x0 = 211.0 top = 278.6
0Procurement x0 = 211.0 top = 285.4
0Procurement x0 = 211.0 top = 305.5
0procurement x0 = 211.0 top = 406.3
0procurement x0 = 211.0 top = 419.8
0procurement x0 = 211.0 top = 426.5
0Procurement x0 = 211.0 top = 440.0

Determing the position of the two pages

In [9]:
with pdfplumber.open(pdf_path) as pdf:
    for page_num, page in enumerate(pdf.pages, start=1):
        print(f"\n{'='*70}")
        print(f"PAGE {page_num}")
        print(f"{'='*70}")

        words = page.extract_words()

        for word in words[:120]:
            print(
                f"{word['text']:<30} "
                f"x0={word['x0']:.1f} "
                f"x1={word['x1']:.1f} "
                f"top={word['top']:.1f}"
            )

======================================================================
PAGE 1
======================================================================
Entity                         x0=52.1 x1=64.1 top=83.7
Chirundu                       x0=113.3 x1=132.1 top=83.7
Town                           x0=133.3 x1=144.6 top=83.7
Council                        x0=145.8 x1=160.9 top=83.7
Procurement                    x0=52.1 x1=79.2 top=90.4
Plan                           x0=80.4 x1=89.3 top=90.4
for                            x0=90.5 x1=96.4 top=90.4
year                           x0=97.7 x1=106.6 top=90.4
2023                           x0=164.5 x1=174.7 top=90.4
Version                        x0=52.1 x1=67.7 top=97.1
3                              x0=172.1 x1=174.7 top=97.1
Procurement                    x0=52.1 x1=79.2 top=103.9
Budget                         x0=80.4 x1=95.0 top=103.9
35673707.95                    x0=148.1 x1=174.7 top=103.9
ZMW                            x0=52.1 x1=63.3 top=110.6
Control                        x0=64.5 x1=79.6 top=110.6
Total                          x0=80.9 x1=91.2 top=110.6
35673707.95                    x0=148.1 x1=174.7 top=110.6
Date                           x0=52.1 x1=61.8 top=117.3
Last                           x0=63.0 x1=71.2 top=117.3
Updated                        x0=72.4 x1=90.1 top=117.3
26-06-23                       x0=143.8 x1=162.1 top=117.3
15:42                          x0=163.2 x1=174.6 top=117.3
Comments                       x0=52.1 x1=74.4 top=124.0
Consolidated                   x0=113.3 x1=140.1 top=124.0
Procurement                    x0=141.2 x1=168.4 top=124.0
Plan                           x0=169.5 x1=178.4 top=124.0
ZMW                            x0=461.4 x1=472.5 top=137.5
Estimated                      x0=473.7 x1=494.3 top=137.5
Budget                         x0=495.5 x1=510.2 top=137.5
FX                             x0=548.3 x1=553.2 top=137.5
Budget                         x0=554.4 x1=569.0 top=137.5
Amount                         x0=570.2 x1=586.8 top=137.5
Estimated                      x0=661.1 x1=681.7 top=137.5
dates                          x0=682.9 x1=694.1 top=137.5
Class                          x0=52.1 x1=62.2 top=144.2
UNSPSC                         x0=113.3 x1=129.7 top=144.2
IFMIS                          x0=177.0 x1=188.6 top=144.2
GL                             x0=189.7 x1=195.1 top=144.2
AccountDescription             x0=196.3 x1=239.4 top=144.2
Ref                            x0=341.2 x1=348.0 top=144.2
No                             x0=349.2 x1=355.1 top=144.2
Project                        x0=377.1 x1=391.7 top=144.2
CodeUnit                       x0=392.9 x1=414.8 top=144.2
of                             x0=416.0 x1=420.2 top=144.2
MeasureQuantityGOZ             x0=421.4 x1=470.3 top=144.2
Other                          x0=500.7 x1=512.7 top=144.2
Total                          x0=524.5 x1=534.8 top=144.2
CurrencyAmount                 x0=548.3 x1=582.6 top=144.2
Source                         x0=589.8 x1=603.8 top=144.2
of                             x0=605.0 x1=609.2 top=144.2
FuPnrdeqsualificaPtiroonc      x0=610.4 x1=646.5 top=144.2
u(Yre/Nm)enPtu                 x0=646.5 x1=666.3 top=144.2
Mbleictahtoiodn                x0=665.6 x1=684.1 top=144.2
Award                          x0=689.3 x1=702.6 top=144.2
non                            x0=52.1 x1=60.0 top=150.9
consulting                     x0=61.2 x1=82.3 top=150.9
services                       x0=83.5 x1=99.9 top=150.9
82100000                       x0=154.5 x1=174.7 top=150.9
0Advertising                   x0=211.0 x1=239.0 top=150.9
and                            x0=240.3 x1=247.9 top=150.9
publicity                      x0=249.1 x1=266.8 top=150.9
1                              x0=372.2 x1=374.7 top=150.9
Each                           x0=406.0 x1=415.7 top=150.9
18300                          x0=485.7 x1=498.3 top=150.9
18300                          x0=533.3 x1=545.9 top=150.9
Local                          x0=589.8 x1=600.3 top=150.9
ResouNrces                     x0=601.5 x1=622.4 top=150.9
sb                             x0=637.3 x1=641.9 top=150.9
17-02-23                       x0=668.6 x1=686.9 top=150.9
22-02-23                       x0=696.1 x1=714.4 top=150.9
goods                          x0=52.1 x1=64.4 top=157.6
51000000                       x0=154.5 x1=174.7 top=157.6
0Relief,                       x0=211.0 x1=228.9 top=157.6
repartriation                  x0=230.1 x1=256.4 top=157.6
and                            x0=257.6 x1=265.3 top=157.6
burial                         x0=266.5 x1=278.4 top=157.6
of                             x0=279.6 x1=283.7 top=157.6
destitutes                     x0=285.0 x1=305.4 top=157.6
2                              x0=372.2 x1=374.7 top=157.6
Each                           x0=406.0 x1=415.7 top=157.6
25950                          x0=485.7 x1=498.3 top=157.6
25950                          x0=533.3 x1=545.9 top=157.6
Local                          x0=589.8 x1=600.3 top=157.6
ResouNrces                     x0=601.5 x1=622.4 top=157.6
sb                             x0=637.3 x1=641.9 top=157.6
09-03-23                       x0=668.6 x1=686.9 top=157.6
14-03-23                       x0=696.1 x1=714.4 top=157.6
goods                          x0=52.1 x1=64.4 top=164.4
49000000                       x0=154.5 x1=174.7 top=164.4
0Staff                         x0=211.0 x1=225.4 top=164.4
welfare                        x0=226.6 x1=242.2 top=164.4
and                            x0=243.4 x1=251.1 top=164.4
recreation                     x0=252.3 x1=273.6 top=164.4
3                              x0=372.2 x1=374.7 top=164.4
Each                           x0=406.0 x1=415.7 top=164.4
91080                          x0=485.7 x1=498.3 top=164.4
91080                          x0=533.3 x1=545.9 top=164.4
Local                          x0=589.8 x1=600.3 top=164.4
ResouNrces                     x0=601.5 x1=622.4 top=164.4
sb                             x0=637.3 x1=641.9 top=164.4
14-03-23                       x0=668.6 x1=686.9 top=164.4
20-03-23                       x0=696.1 x1=714.4 top=164.4
non                            x0=52.1 x1=60.0 top=171.1
consulting                     x0=61.2 x1=82.3 top=171.1
services                       x0=83.5 x1=99.9 top=171.1
76121600                       x0=154.5 x1=174.7 top=171.1
0waste                         x0=211.0 x1=228.0 top=171.1
and                            x0=229.2 x1=236.9 top=171.1
refuse                         x0=238.1 x1=251.1 top=171.1
collection                     x0=252.3 x1=272.3 top=171.1
4                              x0=372.2 x1=374.7 top=171.1
Each                           x0=406.0 x1=415.7 top=171.1
580555                         x0=483.2 x1=498.3 top=171.1
580555                         x0=530.7 x1=545.9 top=171.1
Local                          x0=589.8 x1=600.3 top=171.1
ResouNrces                     x0=601.5 x1=622.4 top=171.1
sb                             x0=637.3 x1=641.9 top=171.1
10-01-23                       x0=668.6 x1=686.9 top=171.1
16-01-23                       x0=696.1 x1=714.4 top=171.1

======================================================================
PAGE 2
======================================================================
Start                          x0=52.1 x1=61.9 top=144.2
Public                         x0=81.4 x1=93.8 top=144.2
ViewP                          x0=95.0 x1=107.7 top=144.2
(uY/bNlic)                     x0=106.4 x1=117.6 top=144.2
ViewC                          x0=118.8 x1=131.6 top=144.2
JoumstimficeanttisonSource     x0=130.2 x1=166.7 top=144.2
Project                        x0=176.4 x1=191.1 top=144.2
ID                             x0=192.2 x1=196.7 top=144.2
URI                            x0=200.2 x1=207.5 top=144.2
Rationale                      x0=224.0 x1=243.4 top=144.2
Type                           x0=247.7 x1=257.6 top=144.2
of                             x0=258.8 x1=262.9 top=144.2
Entry                          x0=264.2 x1=275.1 top=144.2
24-02-23Y                      x0=60.7 x1=83.8 top=150.9
Monthly                        x0=128.9 x1=146.3 top=150.9
procurement                    x0=147.5 x1=174.6 top=150.9
16-03-23Y                      x0=60.7 x1=83.8 top=157.6
27-03-23Y                      x0=60.7 x1=83.8 top=164.4
quarterly                      x0=128.9 x1=147.8 top=164.4
procurement                    x0=149.0 x1=176.1 top=164.4
19-01-23Y                      x0=60.7 x1=83.8 top=171.1
weekly                         x0=128.9 x1=143.3 top=171.1
16-03-23Y                      x0=60.7 x1=83.8 top=177.8
30-01-23Y                      x0=60.7 x1=83.8 top=184.5
01-02-23Y                      x0=60.7 x1=83.8 top=191.2
monthly                        x0=128.9 x1=146.1 top=191.2
procurement                    x0=147.2 x1=174.4 top=191.2
27-04-23Y                      x0=60.7 x1=83.8 top=198.0
quarterly                      x0=128.9 x1=147.8 top=198.0
procurement(                   x0=149.0 x1=177.7 top=198.0
awaiting                       x0=178.9 x1=196.4 top=198.0
identification                 x0=197.6 x1=224.9 top=198.0
of                             x0=226.1 x1=230.3 top=198.0
the                            x0=231.5 x1=238.4 top=198.0
specific                       x0=239.5 x1=254.9 top=198.0
projects)                      x0=256.1 x1=274.2 top=198.0
28-03-23Y                      x0=60.7 x1=83.8 top=204.7
21-04-23Y                      x0=60.7 x1=83.8 top=211.4
27-01-23Y                      x0=60.7 x1=83.8 top=218.2
monthly                        x0=128.9 x1=146.1 top=218.2
procurement                    x0=147.2 x1=174.4 top=218.2
11-04-23Y                      x0=60.7 x1=83.8 top=224.9
quarterly                      x0=128.9 x1=147.8 top=224.9
procurement                    x0=149.0 x1=176.1 top=224.9
threshold                      x0=224.0 x1=243.6 top=224.9
18-04-23Y                      x0=60.7 x1=83.8 top=231.6
quarterly                      x0=128.9 x1=147.8 top=231.6
procurement                    x0=149.0 x1=176.1 top=231.6
threshold                      x0=224.0 x1=243.6 top=231.6
23-02-23Y                      x0=60.7 x1=83.8 top=238.3
quarterly                      x0=128.9 x1=147.8 top=238.3
procurement                    x0=149.0 x1=176.1 top=238.3
threshold                      x0=224.0 x1=243.6 top=238.3
14-03-23Y                      x0=60.7 x1=83.8 top=245.0
quarterly                      x0=128.9 x1=147.8 top=245.0
procurement                    x0=149.0 x1=176.1 top=245.0
threshold                      x0=224.0 x1=243.6 top=245.0
11-05-23Y                      x0=60.7 x1=83.8 top=251.8
threshold                      x0=224.0 x1=243.6 top=251.8
29-05-23Y                      x0=60.7 x1=83.8 top=258.5
quarterly                      x0=128.9 x1=147.8 top=258.5
procurement                    x0=149.0 x1=176.1 top=258.5
10-03-23Y                      x0=60.7 x1=83.8 top=265.2
quarterly                      x0=128.9 x1=147.8 top=265.2
procurement                    x0=149.0 x1=176.1 top=265.2
09-03-23Y                      x0=60.7 x1=83.8 top=271.9
18-04-23Y                      x0=60.7 x1=83.8 top=278.6
quarterly                      x0=128.9 x1=147.8 top=278.6
procurement                    x0=149.0 x1=176.1 top=278.6
10-02-23Y                      x0=60.7 x1=83.8 top=285.4
16-10-23Y                      x0=60.7 x1=83.8 top=292.1
06-04-23Y                      x0=60.7 x1=83.8 top=298.8
quarterly                      x0=128.9 x1=147.8 top=298.8
procurement                    x0=149.0 x1=176.1 top=298.8
27-04-23Y                      x0=60.7 x1=83.8 top=305.5
12-01-23Y                      x0=60.7 x1=83.8 top=312.2
Running                        x0=128.9 x1=145.8 top=312.2
Contract                       x0=147.0 x1=164.6 top=312.2
17-01-23Y                      x0=60.7 x1=83.8 top=319.0
15-06-23Y                      x0=60.7 x1=83.8 top=325.7
22-02-23Y                      x0=60.7 x1=83.8 top=332.4
12-10-23Y                      x0=60.7 x1=83.8 top=339.1
21-02-23Y                      x0=60.7 x1=83.8 top=345.9
14-04-23Y                      x0=60.7 x1=83.8 top=352.6
quarterly                      x0=128.9 x1=147.8 top=352.6
procurement                    x0=149.0 x1=176.1 top=352.6
25-04-23Y                      x0=60.7 x1=83.8 top=359.3
16-06-23Y                      x0=60.7 x1=83.8 top=366.0
05-05-23Y                      x0=60.7 x1=83.8 top=372.7
05-05-23Y                      x0=60.7 x1=83.8 top=379.4
23-02-23Y                      x0=60.7 x1=83.8 top=386.2
quarterly                      x0=128.9 x1=147.8 top=386.2
procurements                   x0=149.0 x1=178.1 top=386.2
08-08-23Y                      x0=60.7 x1=83.8 top=392.9
quarterly                      x0=128.9 x1=147.8 top=392.9
procurements                   x0=149.0 x1=178.1 top=392.9
16-06-23Y                      x0=60.7 x1=83.8 top=399.6
29-05-23Y                      x0=60.7 x1=83.8 top=406.3
Once                           x0=128.9 x1=139.6 top=406.3
off                            x0=140.8 x1=146.5 top=406.3
procurement                    x0=147.7 x1=174.8 top=406.3
08-07-23Y                      x0=60.7 x1=83.8 top=413.1
Once                           x0=128.9 x1=139.6 top=413.1
off                            x0=140.8 x1=146.5 top=413.1
procurement                    x0=147.7 x1=174.8 top=413.1
21-08-23Y                      x0=60.7 x1=83.8 top=419.8
Once                           x0=128.9 x1=139.6 top=419.8
off                            x0=140.8 x1=146.5 top=419.8
procurement                    x0=147.7 x1=174.8 top=419.8
30-08-23Y                      x0=60.7 x1=83.8 top=426.5
Once                           x0=128.9 x1=139.6 top=426.5
off                            x0=140.8 x1=146.5 top=426.5
procurement                    x0=147.7 x1=174.8 top=426.5
28-09-23Y                      x0=60.7 x1=83.8 top=433.2
18-08-23Y                      x0=60.7 x1=83.8 top=440.0
07-07-23Y                      x0=60.7 x1=83.8 top=446.7
10-10-23Y                      x0=60.7 x1=83.8 top=453.4
10-10-23Y                      x0=60.7 x1=83.8 top=460.1
09-11-23Y                      x0=60.7 x1=83.8 top=466.8
30-08-23Y                      x0=60.7 x1=83.8 top=473.6

In [10]:
import pdfplumber

with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[0]
    words = page.extract_words()

    # Show words around the table header
    for word in words:
        if 125 <= word["top"] <= 180:
            print(
                f"{word['text']:<35} "
                f"x0={word['x0']:.1f} "
                f"x1={word['x1']:.1f} "
                f"top={word['top']:.1f}"
            )

ZMW                                 x0=461.4 x1=472.5 top=137.5
Estimated                           x0=473.7 x1=494.3 top=137.5
Budget                              x0=495.5 x1=510.2 top=137.5
FX                                  x0=548.3 x1=553.2 top=137.5
Budget                              x0=554.4 x1=569.0 top=137.5
Amount                              x0=570.2 x1=586.8 top=137.5
Estimated                           x0=661.1 x1=681.7 top=137.5
dates                               x0=682.9 x1=694.1 top=137.5
Class                               x0=52.1 x1=62.2 top=144.2
UNSPSC                              x0=113.3 x1=129.7 top=144.2
IFMIS                               x0=177.0 x1=188.6 top=144.2
GL                                  x0=189.7 x1=195.1 top=144.2
AccountDescription                  x0=196.3 x1=239.4 top=144.2
Ref                                 x0=341.2 x1=348.0 top=144.2
No                                  x0=349.2 x1=355.1 top=144.2
Project                             x0=377.1 x1=391.7 top=144.2
CodeUnit                            x0=392.9 x1=414.8 top=144.2
of                                  x0=416.0 x1=420.2 top=144.2
MeasureQuantityGOZ                  x0=421.4 x1=470.3 top=144.2
Other                               x0=500.7 x1=512.7 top=144.2
Total                               x0=524.5 x1=534.8 top=144.2
CurrencyAmount                      x0=548.3 x1=582.6 top=144.2
Source                              x0=589.8 x1=603.8 top=144.2
of                                  x0=605.0 x1=609.2 top=144.2
FuPnrdeqsualificaPtiroonc           x0=610.4 x1=646.5 top=144.2
u(Yre/Nm)enPtu                      x0=646.5 x1=666.3 top=144.2
Mbleictahtoiodn                     x0=665.6 x1=684.1 top=144.2
Award                               x0=689.3 x1=702.6 top=144.2
non                                 x0=52.1 x1=60.0 top=150.9
consulting                          x0=61.2 x1=82.3 top=150.9
services                            x0=83.5 x1=99.9 top=150.9
82100000                            x0=154.5 x1=174.7 top=150.9
0Advertising                        x0=211.0 x1=239.0 top=150.9
and                                 x0=240.3 x1=247.9 top=150.9
publicity                           x0=249.1 x1=266.8 top=150.9
1                                   x0=372.2 x1=374.7 top=150.9
Each                                x0=406.0 x1=415.7 top=150.9
18300                               x0=485.7 x1=498.3 top=150.9
18300                               x0=533.3 x1=545.9 top=150.9
Local                               x0=589.8 x1=600.3 top=150.9
ResouNrces                          x0=601.5 x1=622.4 top=150.9
sb                                  x0=637.3 x1=641.9 top=150.9
17-02-23                            x0=668.6 x1=686.9 top=150.9
22-02-23                            x0=696.1 x1=714.4 top=150.9
goods                               x0=52.1 x1=64.4 top=157.6
51000000                            x0=154.5 x1=174.7 top=157.6
0Relief,                            x0=211.0 x1=228.9 top=157.6
repartriation                       x0=230.1 x1=256.4 top=157.6
and                                 x0=257.6 x1=265.3 top=157.6
burial                              x0=266.5 x1=278.4 top=157.6
of                                  x0=279.6 x1=283.7 top=157.6
destitutes                          x0=285.0 x1=305.4 top=157.6
2                                   x0=372.2 x1=374.7 top=157.6
Each                                x0=406.0 x1=415.7 top=157.6
25950                               x0=485.7 x1=498.3 top=157.6
25950                               x0=533.3 x1=545.9 top=157.6
Local                               x0=589.8 x1=600.3 top=157.6
ResouNrces                          x0=601.5 x1=622.4 top=157.6
sb                                  x0=637.3 x1=641.9 top=157.6
09-03-23                            x0=668.6 x1=686.9 top=157.6
14-03-23                            x0=696.1 x1=714.4 top=157.6
goods                               x0=52.1 x1=64.4 top=164.4
49000000                            x0=154.5 x1=174.7 top=164.4
0Staff                              x0=211.0 x1=225.4 top=164.4
welfare                             x0=226.6 x1=242.2 top=164.4
and                                 x0=243.4 x1=251.1 top=164.4
recreation                          x0=252.3 x1=273.6 top=164.4
3                                   x0=372.2 x1=374.7 top=164.4
Each                                x0=406.0 x1=415.7 top=164.4
91080                               x0=485.7 x1=498.3 top=164.4
91080                               x0=533.3 x1=545.9 top=164.4
Local                               x0=589.8 x1=600.3 top=164.4
ResouNrces                          x0=601.5 x1=622.4 top=164.4
sb                                  x0=637.3 x1=641.9 top=164.4
14-03-23                            x0=668.6 x1=686.9 top=164.4
20-03-23                            x0=696.1 x1=714.4 top=164.4
non                                 x0=52.1 x1=60.0 top=171.1
consulting                          x0=61.2 x1=82.3 top=171.1
services                            x0=83.5 x1=99.9 top=171.1
76121600                            x0=154.5 x1=174.7 top=171.1
0waste                              x0=211.0 x1=228.0 top=171.1
and                                 x0=229.2 x1=236.9 top=171.1
refuse                              x0=238.1 x1=251.1 top=171.1
collection                          x0=252.3 x1=272.3 top=171.1
4                                   x0=372.2 x1=374.7 top=171.1
Each                                x0=406.0 x1=415.7 top=171.1
580555                              x0=483.2 x1=498.3 top=171.1
580555                              x0=530.7 x1=545.9 top=171.1
Local                               x0=589.8 x1=600.3 top=171.1
ResouNrces                          x0=601.5 x1=622.4 top=171.1
sb                                  x0=637.3 x1=641.9 top=171.1
10-01-23                            x0=668.6 x1=686.9 top=171.1
16-01-23                            x0=696.1 x1=714.4 top=171.1
goods                               x0=52.1 x1=64.4 top=177.8
39110000                            x0=154.5 x1=174.7 top=177.8
0fixtures                           x0=211.0 x1=231.4 top=177.8
and                                 x0=232.6 x1=240.3 top=177.8
fittings                            x0=241.5 x1=255.8 top=177.8
(                                   x0=256.9 x1=258.5 top=177.8
Procurement                         x0=259.7 x1=286.8 top=177.8
of                                  x0=288.0 x1=292.1 top=177.8
Electricals                         x0=293.4 x1=314.1 top=177.8
and                                 x0=315.3 x1=323.0 top=177.8
carpenterly                         x0=324.2 x1=347.8 top=177.8
materials)5                         x0=349.0 x1=374.7 top=177.8
Each                                x0=406.0 x1=415.7 top=177.8
32400                               x0=485.7 x1=498.3 top=177.8
32400                               x0=533.3 x1=545.9 top=177.8
Local                               x0=589.8 x1=600.3 top=177.8
ResouNrces                          x0=601.5 x1=622.4 top=177.8
sb                                  x0=637.3 x1=641.9 top=177.8
09-03-23                            x0=668.6 x1=686.9 top=177.8
14-03-23                            x0=696.1 x1=714.4 top=177.8

Testing the extraction on one page

In [11]:
import pdfplumber
import pandas as pd

pdf_path = "2023-PROCUREMENT-PLAN.pdf"

with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[0]
    words = page.extract_words()

# Column boundaries
columns = {
    "Category": (50, 113),
    "Procurement item": (196, 341),
    "Estimated Amount": (524, 548),
    "Source of Funds": (589, 637),
    "Procurement Method": (637, 661),
    "Publication": (661, 695),
    "date": (695, 730)
}

# Group words into rows using their vertical position
rows = []

for word in words:
    top = word["top"]

    # Ignore everything before the table data
    if top < 165:
        continue

    # Find an existing row at approximately the same height
    matched_row = None

    for row in rows:
        if abs(row["top"] - top) <= 2:
            matched_row = row
            break

    if matched_row is None:
        matched_row = {
            "top": top,
            "words": []
        }
        rows.append(matched_row)

    matched_row["words"].append(word)


# Sort rows vertically
rows.sort(key=lambda x: x["top"])


# Extract the selected columns
extracted_rows = []

for row in rows:

    record = {}

    for column, (x_start, x_end) in columns.items():

        selected_words = [
            w["text"]
            for w in row["words"]
            if w["x0"] >= x_start and w["x0"] < x_end
        ]

        record[column] = " ".join(selected_words).strip()

    record["top"] = row["top"]

    extracted_rows.append(record)


df_test = pd.DataFrame(extracted_rows)

df_test.head(20)

,Category,Procurement item,Estimated Amount,Source of Funds,Procurement Method,Publication,date,top
0,non consulting services,0waste and refuse collection,580555,Local ResouNrces,sb,10-01-23,16-01-23,171.08
1,goods,0fixtures and fittings ( Procurement of Electr...,32400,Local ResouNrces,sb,09-03-23,14-03-23,177.80
2,non consulting services,0internet charges,74400,Local ResouNrces,db,22-01-23,25-01-23,184.52
3,non consulting services,0electricity charges,158400,Local ResouNrces,db,30-01-23,31-01-23,191.24
4,goods,0Utilization of CDF Funds -2023,17882261,CDF N,obn,17-03-23,14-04-23,197.96
5,goods,0construction of a double storey office block,250000,EqualisationN fund/local,s bresources,15-03-23,22-03-23,204.68
6,goods,0Maintenance and grading of roads,630000,Ward FundN,sb,20-03-23,11-04-24,211.43
7,goods,0make Zambia Clean -Procurement of refreshments,93900,Local ResouNrces,sb,20-01-23,24-01-23,218.15
8,goods,"0tools and equipment(procurement of slashers, ...",58670,Local ResouNrces,sb,03-04-23,06-04-23,224.87
9,goods,0Protective clothing,95525,Local ResouNrces,sb,12-04-23,14-04-23,231.59
10,goods,0Auto spares,100000,Local ResouNrces,sb,15-02-23,20-02-23,238.31
11,goods,0Tyres for motor vehicles,39000,Local ResouNrces,sb,03-03-23,07-03-23,245.03
12,goods,0Street light Equipment maintenence,137700,Local ResouNrces,sb,03-05-23,08-05-23,251.75
13,goods,0Road Mantenance Materials,294000,Local ResouNrces,sb,18-05-23,23-05-23,258.47
14,goods,0Various stationery,425292,Local ResouNrces,sb,03-03-23,07-03-23,265.19
15,goods,0office eqipment,40000,Local ResouNrces,sb,03-03-23,07-03-23,271.91
16,goods,0procurement of office furniture,229800,Local ResouNrces,sb,11-04-23,14-04-23,278.63
17,goods,"0Procurement of books, newspapers,magazines",11250,Local ResouNrces,sb,03-02-23,07-02-23,285.35
18,goods,0office fittings (uphostering of office tables...,2000,Local ResouNrces,sb,10-10-23,13-10-23,292.07
19,goods,0Building maintenance materials,74020,Local ResouNrces,sb,29-03-23,03-04-23,298.79

Clean the extracted DataFrame

In [15]:
def clean_source(value):
    if pd.isna(value):
        return ""

    value = str(value).strip()

    # Remove common OCR artifacts
    value = value.replace("N", " ")
    value = re.sub(r"\s+", " ", value).strip()

    # Local Resources
    if re.search(r"local\s*res", value, re.IGNORECASE):
        return "Local Resource"

    # Equalisation / Equalization OCR variations
    if re.search(r"equali[sz]a?tion", value, re.IGNORECASE):
        return "Equalisation"

    # CDF variations
    if re.search(r"\bC?DF\b", value, re.IGNORECASE):
        return "CDF"

    # Ward Fund
    if re.search(r"ward\s*fund", value, re.IGNORECASE):
        return "Ward Fund"

    return value

Check How many rows we extracted

In [18]:
print("Rows extracted:", len(df))

print("\nCategories:")
print(df["Category"].value_counts(dropna=False))

print("\nSources of Funds:")
print(df["Source of Funds"].value_counts(dropna=False))

print("\nProcurement Methods:")
print(df["Procurement Method"].value_counts(dropna=False))

Rows extracted: 46

Categories:
Category
goods                      29
works                      10
non consulting services     7
Name: count, dtype: int64

Sources of Funds:
Source of Funds
Local Resource        31
CDF                   10
Equalisation           1
Ward Fund              1
EqualizationN fund     1
EquilizationN fund     1
2022/2023 CNDF         1
Name: count, dtype: int64

Procurement Methods:
Procurement Method
sb              34
obn              8
db               3
s bresources     1
Name: count, dtype: int64

In [19]:
df["Source of Funds"] = df["Source of Funds"].apply(clean_source)

print(df["Source of Funds"].value_counts(dropna=False))

Source of Funds
Local Resource       31
CDF                  11
Equalisation          2
Ward Fund             1
Equilization fund     1
Name: count, dtype: int64

In [20]:
def clean_source(value):
    if pd.isna(value):
        return ""

    value = str(value).strip()

    # Normalize OCR artifacts
    value = re.sub(r"\s+", " ", value)

    # Local Resources
    if re.search(r"local\s*res", value, re.IGNORECASE):
        return "Local Resource"

    # Equalisation / Equalization variations
    if re.search(r"equali[sz]ation", value, re.IGNORECASE):
        return "Equalisation"

    # Year-based CDF, e.g. 2022/2023 CNDF
    if re.search(r"\d{4}/\d{4}\s*C?N?DF", value, re.IGNORECASE):
        match = re.search(r"\d{4}/\d{4}", value)
        return f"{match.group()} CDF"

    # Normal CDF
    if re.search(r"\bC?N?DF\b", value, re.IGNORECASE):
        return "CDF"

    # Ward Fund
    if re.search(r"ward\s*fund", value, re.IGNORECASE):
        return "Ward Fund"

    return value

In [21]:
df["Source of Funds"] = df["Source of Funds"].apply(clean_source)

In [22]:
def clean_method(value):
    if pd.isna(value):
        return ""

    value = str(value).strip().lower()

    # OCR/column overlap
    if "sb" in value:
        return "sb"

    if "obn" in value:
        return "obn"

    if value == "db":
        return "db"

    return value


df["Procurement Method"] = df["Procurement Method"].apply(clean_method)

In [23]:
print(df["Procurement Method"].value_counts(dropna=False))

Procurement Method
sb              34
obn              8
db               3
s bresources     1
Name: count, dtype: int64

In [24]:
print(
    df[
        df["Source of Funds"].str.contains(
            "Equal|Equil|equil",
            case=False,
            na=False
        )
    ][
        ["Procurement item", "Source of Funds"]
    ]
)

                                    Procurement item    Source of Funds
5       construction of a double storey office block       Equalisation
35             procurement of a block making machine       Equalisation
36  Construction of ablution block at the truck park  Equilization fund

In [25]:
def clean_source(value):
    if pd.isna(value):
        return ""

    value = str(value).strip()

    # Remove common OCR artifacts
    value = re.sub(r"\s+", " ", value)

    # Local Resources
    if re.search(r"local\s*res", value, re.IGNORECASE):
        return "Local Resource"

    # Equalisation / Equalization / Equilization variations
    if re.search(r"equali[sz]ation|equilization", value, re.IGNORECASE):
        return "Equalisation"

    # Year-based CDF
    if re.search(r"\d{4}/\d{4}\s*C?N?DF", value, re.IGNORECASE):
        match = re.search(r"\d{4}/\d{4}", value)
        return f"{match.group()} CDF"

    # Normal CDF
    if re.search(r"\bC?N?DF\b", value, re.IGNORECASE):
        return "CDF"

    # Ward Fund
    if re.search(r"ward\s*fund", value, re.IGNORECASE):
        return "Ward Fund"

    return value


df["Source of Funds"] = df["Source of Funds"].apply(clean_source)

In [26]:
print(df["Source of Funds"].value_counts(dropna=False))

Source of Funds
Local Resource    31
CDF               11
Equalisation       3
Ward Fund          1
Name: count, dtype: int64

Clean procurement method

In [27]:
def clean_method(value):
    if pd.isna(value):
        return ""

    value = str(value).strip().lower()

    # Correct column overlap
    if "sb" in value:
        return "sb"

    if "obn" in value:
        return "obn"

    if "db" in value:
        return "db"

    return value


df["Procurement Method"] = df["Procurement Method"].apply(clean_method)

print(df["Procurement Method"].value_counts(dropna=False))

Procurement Method
sb              34
obn              8
db               3
s bresources     1
Name: count, dtype: int64

Inspect page 2

In [28]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[1]
    words = page.extract_words()

# Use the same column boundaries
columns = {
    "Category": (50, 113),
    "Procurement item": (196, 341),
    "Estimated Amount": (524, 548),
    "Source of Funds": (589, 637),
    "Procurement Method": (637, 661),
    "Publication": (661, 695),
    "date": (695, 730)
}

rows = []

for word in words:

    top = word["top"]

    # Ignore page header
    if top < 100:
        continue

    matched_row = None

    for row in rows:
        if abs(row["top"] - top) <= 2:
            matched_row = row
            break

    if matched_row is None:
        matched_row = {
            "top": top,
            "words": []
        }
        rows.append(matched_row)

    matched_row["words"].append(word)


rows.sort(key=lambda x: x["top"])

page2_records = []

for row in rows:

    record = {}

    for column, (x_start, x_end) in columns.items():

        selected_words = [
            w["text"]
            for w in row["words"]
            if w["x0"] >= x_start and w["x0"] < x_end
        ]

        record[column] = " ".join(selected_words).strip()

    record["top"] = row["top"]

    page2_records.append(record)


df_page2 = pd.DataFrame(page2_records)

df_page2.head(20)

,Category,Procurement item,Estimated Amount,Source of Funds,Procurement Method,Publication,date,top
0,Start Public ViewP (uY/bNlic),URI Rationale Type of Entry,,,,,,144.20
1,24-02-23Y,,,,,,,150.92
2,16-03-23Y,,,,,,,157.64
3,27-03-23Y,,,,,,,164.36
4,19-01-23Y,,,,,,,171.08
5,16-03-23Y,,,,,,,177.80
6,30-01-23Y,,,,,,,184.52
7,01-02-23Y,,,,,,,191.24
8,27-04-23Y,identification of the specific projects),,,,,,197.96
9,28-03-23Y,,,,,,,204.68
10,21-04-23Y,,,,,,,211.43
11,27-01-23Y,,,,,,,218.15
12,11-04-23Y,threshold,,,,,,224.87
13,18-04-23Y,threshold,,,,,,231.59
14,23-02-23Y,threshold,,,,,,238.31
15,14-03-23Y,threshold,,,,,,245.03
16,11-05-23Y,threshold,,,,,,251.75
17,29-05-23Y,,,,,,,258.47
18,10-03-23Y,,,,,,,265.19
19,09-03-23Y,,,,,,,271.91

Inspecting page 2 layout

In [29]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[1]
    words = page.extract_words()

    # Show the first 100 words of page 2 with coordinates
    for word in words[:100]:
        print(
            f"{word['text']:<35} "
            f"x0={word['x0']:.1f} "
            f"x1={word['x1']:.1f} "
            f"top={word['top']:.1f}"
        )

Start                               x0=52.1 x1=61.9 top=144.2
Public                              x0=81.4 x1=93.8 top=144.2
ViewP                               x0=95.0 x1=107.7 top=144.2
(uY/bNlic)                          x0=106.4 x1=117.6 top=144.2
ViewC                               x0=118.8 x1=131.6 top=144.2
JoumstimficeanttisonSource          x0=130.2 x1=166.7 top=144.2
Project                             x0=176.4 x1=191.1 top=144.2
ID                                  x0=192.2 x1=196.7 top=144.2
URI                                 x0=200.2 x1=207.5 top=144.2
Rationale                           x0=224.0 x1=243.4 top=144.2
Type                                x0=247.7 x1=257.6 top=144.2
of                                  x0=258.8 x1=262.9 top=144.2
Entry                               x0=264.2 x1=275.1 top=144.2
24-02-23Y                           x0=60.7 x1=83.8 top=150.9
Monthly                             x0=128.9 x1=146.3 top=150.9
procurement                         x0=147.5 x1=174.6 top=150.9
16-03-23Y                           x0=60.7 x1=83.8 top=157.6
27-03-23Y                           x0=60.7 x1=83.8 top=164.4
quarterly                           x0=128.9 x1=147.8 top=164.4
procurement                         x0=149.0 x1=176.1 top=164.4
19-01-23Y                           x0=60.7 x1=83.8 top=171.1
weekly                              x0=128.9 x1=143.3 top=171.1
16-03-23Y                           x0=60.7 x1=83.8 top=177.8
30-01-23Y                           x0=60.7 x1=83.8 top=184.5
01-02-23Y                           x0=60.7 x1=83.8 top=191.2
monthly                             x0=128.9 x1=146.1 top=191.2
procurement                         x0=147.2 x1=174.4 top=191.2
27-04-23Y                           x0=60.7 x1=83.8 top=198.0
quarterly                           x0=128.9 x1=147.8 top=198.0
procurement(                        x0=149.0 x1=177.7 top=198.0
awaiting                            x0=178.9 x1=196.4 top=198.0
identification                      x0=197.6 x1=224.9 top=198.0
of                                  x0=226.1 x1=230.3 top=198.0
the                                 x0=231.5 x1=238.4 top=198.0
specific                            x0=239.5 x1=254.9 top=198.0
projects)                           x0=256.1 x1=274.2 top=198.0
28-03-23Y                           x0=60.7 x1=83.8 top=204.7
21-04-23Y                           x0=60.7 x1=83.8 top=211.4
27-01-23Y                           x0=60.7 x1=83.8 top=218.2
monthly                             x0=128.9 x1=146.1 top=218.2
procurement                         x0=147.2 x1=174.4 top=218.2
11-04-23Y                           x0=60.7 x1=83.8 top=224.9
quarterly                           x0=128.9 x1=147.8 top=224.9
procurement                         x0=149.0 x1=176.1 top=224.9
threshold                           x0=224.0 x1=243.6 top=224.9
18-04-23Y                           x0=60.7 x1=83.8 top=231.6
quarterly                           x0=128.9 x1=147.8 top=231.6
procurement                         x0=149.0 x1=176.1 top=231.6
threshold                           x0=224.0 x1=243.6 top=231.6
23-02-23Y                           x0=60.7 x1=83.8 top=238.3
quarterly                           x0=128.9 x1=147.8 top=238.3
procurement                         x0=149.0 x1=176.1 top=238.3
threshold                           x0=224.0 x1=243.6 top=238.3
14-03-23Y                           x0=60.7 x1=83.8 top=245.0
quarterly                           x0=128.9 x1=147.8 top=245.0
procurement                         x0=149.0 x1=176.1 top=245.0
threshold                           x0=224.0 x1=243.6 top=245.0
11-05-23Y                           x0=60.7 x1=83.8 top=251.8
threshold                           x0=224.0 x1=243.6 top=251.8
29-05-23Y                           x0=60.7 x1=83.8 top=258.5
quarterly                           x0=128.9 x1=147.8 top=258.5
procurement                         x0=149.0 x1=176.1 top=258.5
10-03-23Y                           x0=60.7 x1=83.8 top=265.2
quarterly                           x0=128.9 x1=147.8 top=265.2
procurement                         x0=149.0 x1=176.1 top=265.2
09-03-23Y                           x0=60.7 x1=83.8 top=271.9
18-04-23Y                           x0=60.7 x1=83.8 top=278.6
quarterly                           x0=128.9 x1=147.8 top=278.6
procurement                         x0=149.0 x1=176.1 top=278.6
10-02-23Y                           x0=60.7 x1=83.8 top=285.4
16-10-23Y                           x0=60.7 x1=83.8 top=292.1
06-04-23Y                           x0=60.7 x1=83.8 top=298.8
quarterly                           x0=128.9 x1=147.8 top=298.8
procurement                         x0=149.0 x1=176.1 top=298.8
27-04-23Y                           x0=60.7 x1=83.8 top=305.5
12-01-23Y                           x0=60.7 x1=83.8 top=312.2
Running                             x0=128.9 x1=145.8 top=312.2
Contract                            x0=147.0 x1=164.6 top=312.2
17-01-23Y                           x0=60.7 x1=83.8 top=319.0
15-06-23Y                           x0=60.7 x1=83.8 top=325.7
22-02-23Y                           x0=60.7 x1=83.8 top=332.4
12-10-23Y                           x0=60.7 x1=83.8 top=339.1
21-02-23Y                           x0=60.7 x1=83.8 top=345.9
14-04-23Y                           x0=60.7 x1=83.8 top=352.6
quarterly                           x0=128.9 x1=147.8 top=352.6
procurement                         x0=149.0 x1=176.1 top=352.6
25-04-23Y                           x0=60.7 x1=83.8 top=359.3
16-06-23Y                           x0=60.7 x1=83.8 top=366.0
05-05-23Y                           x0=60.7 x1=83.8 top=372.7
05-05-23Y                           x0=60.7 x1=83.8 top=379.4
23-02-23Y                           x0=60.7 x1=83.8 top=386.2
quarterly                           x0=128.9 x1=147.8 top=386.2
procurements                        x0=149.0 x1=178.1 top=386.2
08-08-23Y                           x0=60.7 x1=83.8 top=392.9
quarterly                           x0=128.9 x1=147.8 top=392.9
procurements                        x0=149.0 x1=178.1 top=392.9
16-06-23Y                           x0=60.7 x1=83.8 top=399.6
29-05-23Y                           x0=60.7 x1=83.8 top=406.3
Once                                x0=128.9 x1=139.6 top=406.3
off                                 x0=140.8 x1=146.5 top=406.3

Find last procurement row

In [30]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[0]
    words = page.extract_words()

# Print words from the bottom part of page 1
for word in words:
    if word["top"] > 430:
        print(
            f"{word['text']:<45} "
            f"x0={word['x0']:.1f} "
            f"x1={word['x1']:.1f} "
            f"top={word['top']:.1f}"
        )

works                                         x0=52.1 x1=64.4 top=433.2
72130000                                      x0=154.5 x1=174.7 top=433.2
0Construction                                 x0=211.0 x1=242.2 top=433.2
of                                            x0=243.4 x1=247.6 top=433.2
3                                             x0=248.8 x1=251.3 top=433.2
sanitation                                    x0=252.5 x1=272.9 top=433.2
facilities                                    x0=274.1 x1=291.1 top=433.2
at                                            x0=292.3 x1=296.4 top=433.2
Mission,                                      x0=297.6 x1=314.7 top=433.2
T-Junction                                    x0=315.8 x1=336.9 top=433.2
and                                           x0=338.1 x1=345.8 top=433.2
Yellow                                        x0=347.0 x1=360.5 top=433.2
Jack4e3t                                      x0=361.7 x1=374.7 top=433.2
Each                                          x0=406.0 x1=415.7 top=433.2
1597084.53                                    x0=474.3 x1=498.3 top=433.2
1597085                                       x0=528.2 x1=545.9 top=433.2
2023                                          x0=589.8 x1=599.9 top=433.2
CDF                                           x0=601.1 x1=609.1 top=433.2
N                                             x0=613.5 x1=616.8 top=433.2
obn                                           x0=637.3 x1=645.2 top=433.2
18-08-23                                      x0=668.6 x1=686.9 top=433.2
15-09-23                                      x0=696.1 x1=714.4 top=433.2
works                                         x0=52.1 x1=64.4 top=440.0
25161507                                      x0=154.5 x1=174.7 top=440.0
0Procurement                                  x0=211.0 x1=243.0 top=440.0
of                                            x0=244.2 x1=248.4 top=440.0
desks                                         x0=249.6 x1=261.0 top=440.0
for                                           x0=262.1 x1=268.0 top=440.0
various                                       x0=269.3 x1=284.2 top=440.0
Schools                                       x0=285.3 x1=300.9 top=440.0
44                                            x0=369.7 x1=374.7 top=440.0
Each                                          x0=406.0 x1=415.7 top=440.0
1032000                                       x0=480.7 x1=498.3 top=440.0
1032000                                       x0=528.2 x1=545.9 top=440.0
2023                                          x0=589.8 x1=599.9 top=440.0
CDF                                           x0=601.1 x1=609.1 top=440.0
N                                             x0=613.5 x1=616.8 top=440.0
obn                                           x0=637.3 x1=645.2 top=440.0
07-07-23                                      x0=668.6 x1=686.9 top=440.0
04-08-23                                      x0=696.1 x1=714.4 top=440.0
works                                         x0=52.1 x1=64.4 top=446.7
72130000                                      x0=154.5 x1=174.7 top=446.7
0construction                                 x0=211.0 x1=241.7 top=446.7
of                                            x0=242.9 x1=247.1 top=446.7
martenity                                     x0=249.5 x1=269.8 top=446.7
wings                                         x0=271.0 x1=282.8 top=446.7
at                                            x0=283.9 x1=288.0 top=446.7
Chibende                                      x0=289.2 x1=308.6 top=446.7
Clinic                                        x0=309.8 x1=320.8 top=446.7
45                                            x0=369.7 x1=374.7 top=446.7
Each                                          x0=406.0 x1=415.7 top=446.7
983302.99                                     x0=476.8 x1=498.3 top=446.7
983303                                        x0=530.7 x1=545.9 top=446.7
2023                                          x0=589.8 x1=599.9 top=446.7
CDF                                           x0=601.1 x1=609.1 top=446.7
N                                             x0=613.5 x1=616.8 top=446.7
sb                                            x0=637.3 x1=641.9 top=446.7
13-06-23                                      x0=668.6 x1=686.9 top=446.7
23-06-23                                      x0=696.1 x1=714.4 top=446.7
works                                         x0=52.1 x1=64.4 top=453.4
72130000                                      x0=154.5 x1=174.7 top=453.4
0drilling                                     x0=211.0 x1=230.2 top=453.4
and                                           x0=231.4 x1=239.1 top=453.4
equipping                                     x0=240.2 x1=260.7 top=453.4
of                                            x0=262.0 x1=266.1 top=453.4
solar                                         x0=267.3 x1=277.3 top=453.4
powered                                       x0=278.5 x1=296.8 top=453.4
borehle                                       x0=298.0 x1=314.0 top=453.4
at                                            x0=315.2 x1=319.3 top=453.4
Nabbanda                                      x0=320.5 x1=341.5 top=453.4
Clinic                                        x0=342.7 x1=353.7 top=453.4
46                                            x0=369.7 x1=374.7 top=453.4
Each                                          x0=406.0 x1=415.7 top=453.4
351033                                        x0=483.2 x1=498.3 top=453.4
351033                                        x0=530.7 x1=545.9 top=453.4
2023                                          x0=589.8 x1=599.9 top=453.4
CDF                                           x0=601.1 x1=609.1 top=453.4
N                                             x0=613.5 x1=616.8 top=453.4
sb                                            x0=637.3 x1=641.9 top=453.4
18-09-23                                      x0=668.6 x1=686.9 top=453.4
29-09-23                                      x0=696.1 x1=714.4 top=453.4
works                                         x0=52.1 x1=64.4 top=460.1
72130000                                      x0=154.5 x1=174.7 top=460.1
0water                                        x0=211.0 x1=227.9 top=460.1
reticulation                                  x0=229.1 x1=252.9 top=460.1
in                                            x0=254.0 x1=257.9 top=460.1
Kanengumbo,                                   x0=259.1 x1=287.6 top=460.1
kandunga                                      x0=288.7 x1=308.7 top=460.1
and                                           x0=309.9 x1=317.6 top=460.1
mandenga                                      x0=318.8 x1=340.5 top=460.1
village                                       x0=341.7 x1=354.9 top=460.1
47                                            x0=369.7 x1=374.7 top=460.1
Each                                          x0=406.0 x1=415.7 top=460.1
946394.18                                     x0=476.8 x1=498.3 top=460.1
946394.2                                      x0=526.9 x1=545.9 top=460.1
2023                                          x0=589.8 x1=599.9 top=460.1
CDF                                           x0=601.1 x1=609.1 top=460.1
N                                             x0=613.5 x1=616.8 top=460.1
sb                                            x0=637.3 x1=641.9 top=460.1
18-09-23                                      x0=668.6 x1=686.9 top=460.1
29-09-23                                      x0=696.1 x1=714.4 top=460.1
works                                         x0=52.1 x1=64.4 top=466.8
72130000                                      x0=154.5 x1=174.7 top=466.8
0water                                        x0=211.0 x1=227.9 top=466.8
reticulation                                  x0=229.1 x1=252.9 top=466.8
in                                            x0=254.0 x1=257.9 top=466.8
chilindi,                                     x0=259.1 x1=275.2 top=466.8
machavika,                                    x0=276.3 x1=299.4 top=466.8
chibulameenda                                 x0=300.6 x1=332.2 top=466.8
from                                          x0=333.4 x1=343.4 top=466.8
siamaundu                                     x0=344.7 x1=367.2 top=466.8
t4o8siabulendo                                x0=368.4 x1=395.2 top=466.8
Each                                          x0=406.0 x1=415.7 top=466.8
1910044.5                                     x0=476.8 x1=498.3 top=466.8
1910044                                       x0=528.2 x1=545.9 top=466.8
2023                                          x0=589.8 x1=599.9 top=466.8
CDF                                           x0=601.1 x1=609.1 top=466.8
N                                             x0=613.5 x1=616.8 top=466.8
obn                                           x0=637.3 x1=645.2 top=466.8
29-09-23                                      x0=668.6 x1=686.9 top=466.8
27-10-23                                      x0=696.1 x1=714.4 top=466.8
works                                         x0=52.1 x1=64.4 top=473.6
72130000                                      x0=154.5 x1=174.7 top=473.6
0Construction                                 x0=211.0 x1=242.2 top=473.6
of                                            x0=243.4 x1=247.6 top=473.6
a                                             x0=248.8 x1=251.2 top=473.6
domitory,                                     x0=252.4 x1=272.6 top=473.6
Cooking                                       x0=273.7 x1=290.1 top=473.6
area                                          x0=291.3 x1=300.5 top=473.6
and                                           x0=301.6 x1=309.3 top=473.6
drilling                                      x0=310.5 x1=324.8 top=473.6
and                                           x0=326.0 x1=333.6 top=473.6
equipping                                     x0=334.8 x1=355.3 top=473.6
of                                            x0=356.5 x1=360.7 top=473.6
a                                             x0=361.9 x1=364.3 top=473.6
so4lo9r                                       x0=365.5 x1=375.7 top=473.6
borehole                                      x0=376.9 x1=395.5 top=473.6
at                                            x0=396.7 x1=400.8 top=473.6
NgE'aocmhbe                                   x0=402.0 x1=420.6 top=473.6
Ilende                                        x0=421.8 x1=434.6 top=473.6
Secondary                                     x0=435.8 x1=457.1 top=473.6
School                                        x0=458.3 x1=471.9 top=473.6
2146000                                       x0=480.7 x1=498.3 top=473.6
2146000                                       x0=528.2 x1=545.9 top=473.6
2022/2023                                     x0=589.8 x1=611.9 top=473.6
CNDF                                          x0=613.1 x1=621.1 top=473.6
obn                                           x0=637.3 x1=645.2 top=473.6
17-07-23                                      x0=668.6 x1=686.9 top=473.6
18-08-23                                      x0=696.1 x1=714.4 top=473.6

RE-EXCRATION OF PAGE 1 THAT IS CLEAN

In [31]:
import pdfplumber
import pandas as pd
import re

pdf_path = "2023-PROCUREMENT-PLAN.pdf"

# =========================================================
# 1. Read page 1
# =========================================================

with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[0]
    words = page.extract_words()


# =========================================================
# 2. Define the useful columns
# =========================================================

columns = {
    "Category": (50, 113),
    "Procurement item": (196, 341),
    "Estimated Amount": (524, 548),
    "Source of Funds": (589, 637),
    "Procurement Method": (637, 661),
    "Publication": (661, 695),
    "date": (695, 730)
}


# =========================================================
# 3. Group words into physical rows
# =========================================================

rows = []

for word in words:

    top = word["top"]

    # Skip document title/header area
    if top < 165:
        continue

    matched_row = None

    for row in rows:
        if abs(row["top"] - top) <= 2:
            matched_row = row
            break

    if matched_row is None:
        matched_row = {
            "top": top,
            "words": []
        }

        rows.append(matched_row)

    matched_row["words"].append(word)


rows.sort(key=lambda x: x["top"])


# =========================================================
# 4. Extract the columns
# =========================================================

records = []

for row in rows:

    record = {}

    for column, (x_start, x_end) in columns.items():

        selected_words = [
            w["text"]
            for w in row["words"]
            if w["x0"] >= x_start and w["x0"] < x_end
        ]

        record[column] = " ".join(selected_words).strip()

    records.append(record)


df_2023 = pd.DataFrame(records)


# =========================================================
# 5. Remove rows that aren't procurement records
# =========================================================

valid_categories = [
    "goods",
    "works",
    "non consulting services",
    "consulting services"
]

df_2023["Category"] = (
    df_2023["Category"]
    .str.strip()
    .str.lower()
)

df_2023 = df_2023[
    df_2023["Category"].isin(valid_categories)
].copy()


# =========================================================
# 6. Clean Procurement item
# =========================================================

df_2023["Procurement item"] = (
    df_2023["Procurement item"]
    .str.replace(r"^0+", "", regex=True)
    .str.strip()
)


# =========================================================
# 7. Clean Estimated Amount
# =========================================================

df_2023["Estimated Amount"] = (
    df_2023["Estimated Amount"]
    .str.replace(",", "", regex=False)
    .str.replace(r"[^\d.]", "", regex=True)
)

df_2023["Estimated Amount"] = pd.to_numeric(
    df_2023["Estimated Amount"],
    errors="coerce"
)


# =========================================================
# 8. Clean Source of Funds
# =========================================================

def clean_source(value):

    if pd.isna(value):
        return ""

    value = str(value).strip()

    # Remove common OCR spacing
    value = re.sub(r"\s+", " ", value)

    # Local Resources
    if re.search(r"local\s*res", value, re.IGNORECASE):
        return "Local Resource"

    # Equalisation / Equalization / Equilization
    if re.search(
        r"equalisation|equalization|equilization",
        value,
        re.IGNORECASE
    ):
        return "Equalisation"

    # Year-based CDF
    match = re.search(
        r"(\d{4}/\d{4})\s*C?N?DF",
        value,
        re.IGNORECASE
    )

    if match:
        return f"{match.group(1)} CDF"

    # Normal CDF
    if re.search(r"\bC?N?DF\b", value, re.IGNORECASE):
        return "CDF"

    # Ward Fund
    if re.search(r"ward\s*fund", value, re.IGNORECASE):
        return "Ward Fund"

    return value


df_2023["Source of Funds"] = (
    df_2023["Source of Funds"]
    .apply(clean_source)
)


# =========================================================
# 9. Clean Procurement Method
# =========================================================

def clean_method(value):

    if pd.isna(value):
        return ""

    value = str(value).strip().lower()

    # Column overlap / OCR artifacts
    if "obn" in value:
        return "obn"

    if "db" in value:
        return "db"

    if "sb" in value:
        return "sb"

    return value


df_2023["Procurement Method"] = (
    df_2023["Procurement Method"]
    .apply(clean_method)
)


# =========================================================
# 10. Use AWARD as the final date
# =========================================================

df_2023["date"] = pd.to_datetime(
    df_2023["date"],
    format="%d-%m-%y",
    errors="coerce"
)


# =========================================================
# 11. Select final schema
# =========================================================

df_2023 = df_2023[
    [
        "Category",
        "Procurement item",
        "Estimated Amount",
        "Source of Funds",
        "Procurement Method",
        "date"
    ]
].reset_index(drop=True)


# =========================================================
# 12. Display result
# =========================================================

print("Total procurement records:", len(df_2023))

display(df_2023)

Total procurement records: 46

,Category,Procurement item,Estimated Amount,Source of Funds,Procurement Method,date
0,non consulting services,waste and refuse collection,580555.0,Local Resource,sb,2023-01-16
1,goods,fixtures and fittings ( Procurement of Electri...,32400.0,Local Resource,sb,2023-03-14
2,non consulting services,internet charges,74400.0,Local Resource,db,2023-01-25
3,non consulting services,electricity charges,158400.0,Local Resource,db,2023-01-31
4,goods,Utilization of CDF Funds -2023,17882261.0,CDF,obn,2023-04-14
5,goods,construction of a double storey office block,250000.0,Equalisation,s bresources,2023-03-22
6,goods,Maintenance and grading of roads,630000.0,Ward Fund,sb,2024-04-11
7,goods,make Zambia Clean -Procurement of refreshments,93900.0,Local Resource,sb,2023-01-24
8,goods,"tools and equipment(procurement of slashers, h...",58670.0,Local Resource,sb,2023-04-06
9,goods,Protective clothing,95525.0,Local Resource,sb,2023-04-14
10,goods,Auto spares,100000.0,Local Resource,sb,2023-02-20
11,goods,Tyres for motor vehicles,39000.0,Local Resource,sb,2023-03-07
12,goods,Street light Equipment maintenence,137700.0,Local Resource,sb,2023-05-08
13,goods,Road Mantenance Materials,294000.0,Local Resource,sb,2023-05-23
14,goods,Various stationery,425292.0,Local Resource,sb,2023-03-07
15,goods,office eqipment,40000.0,Local Resource,sb,2023-03-07
16,goods,procurement of office furniture,229800.0,Local Resource,sb,2023-04-14
17,goods,"Procurement of books, newspapers,magazines",11250.0,Local Resource,sb,2023-02-07
18,goods,office fittings (uphostering of office tables ...,2000.0,Local Resource,sb,2023-10-13
19,goods,Building maintenance materials,74020.0,Local Resource,sb,2023-04-03
20,goods,Procurement of various materials for labour day,588800.0,Local Resource,sb,2023-04-24
21,goods,"Petrol,oil and lubricants for local and travel...",200160.0,Local Resource,sb,2023-01-09
22,goods,cleaning materials,32700.0,Local Resource,sb,2023-01-13
23,non consulting services,printing,7000.0,Local Resource,sb,2023-06-13
24,non consulting services,Data processing services,73500.0,Local Resource,db,2023-02-20
25,goods,public functions and ceremonies,113700.0,Local Resource,sb,2023-10-09
26,works,bush clearing and grass cutting,67840.0,Local Resource,sb,2023-02-17
27,goods,"computers,periferials,equipment",143001.0,Local Resource,sb,2023-04-11
28,goods,"Refrigerator, TV, CVR, Cameras",41500.0,Local Resource,sb,2023-04-21
29,non consulting services,"Telephone,fax,telex,radio",7000.0,Local Resource,sb,2023-06-13
30,goods,water treatment chimicals,278100.0,Local Resource,sb,2023-05-02
31,goods,water reticulations,95830.0,Local Resource,sb,2023-05-02
32,goods,"Conference,Serminars and workshops",59040.0,Local Resource,sb,2023-02-21
33,non consulting services,survey and mapping,41460.0,Local Resource,sb,2023-08-04
34,works,"Construction of a staff house, ablution block ...",1211835.0,CDF,obn,2023-05-26
35,goods,procurement of a block making machine,800000.0,Equalisation,sb,2023-05-24
36,works,Construction of ablution block at the truck park,150000.0,Equalisation,sb,2023-07-26
37,goods,procurement of an Ambulance,1789320.0,CDF,obn,2023-08-08
38,goods,procurement of a garbage compactor truck,1808560.0,CDF,obn,2023-08-18
39,works,Construction of 3 sanitation facilities at Mis...,1597085.0,CDF,obn,2023-09-15
40,works,Procurement of desks for various Schools,1032000.0,CDF,obn,2023-08-04
41,works,construction of martenity wings at Chibende Cl...,983303.0,CDF,sb,2023-06-23
42,works,drilling and equipping of solar powered borehl...,351033.0,CDF,sb,2023-09-29
43,works,"water reticulation in Kanengumbo, kandunga and...",946394.2,CDF,sb,2023-09-29
44,works,"water reticulation in chilindi, machavika, chi...",1910044.0,CDF,obn,2023-10-27
45,works,"Construction of a domitory, Cooking area and d...",2146000.0,2022/2023 CDF,obn,2023-08-18

FINAL CLEANUP

In [32]:
# Fix the remaining contaminated procurement method
df_2023["Procurement Method"] = (
    df_2023["Procurement Method"]
    .str.lower()
    .str.strip()
)

df_2023.loc[
    df_2023["Procurement Method"].str.contains(
        "s bresources",
        na=False
    ),
    "Procurement Method"
] = "sb"


# Make sure the final column order is correct
df_2023 = df_2023[
    [
        "Category",
        "Procurement item",
        "Estimated Amount",
        "Source of Funds",
        "Procurement Method",
        "date"
    ]
].copy()


# Final validation
print("Number of records:", len(df_2023))
print("\nColumns:")
print(df_2023.columns.tolist())

print("\nProcurement methods:")
print(df_2023["Procurement Method"].value_counts())

print("\nSources of funds:")
print(df_2023["Source of Funds"].value_counts())

Number of records: 46

Columns:
['Category', 'Procurement item', 'Estimated Amount', 'Source of Funds', 'Procurement Method', 'date']

Procurement methods:
Procurement Method
sb     35
obn     8
db      3
Name: count, dtype: int64

Sources of funds:
Source of Funds
Local Resource    31
CDF               10
Equalisation       3
Ward Fund          1
2022/2023 CDF      1
Name: count, dtype: int64

EXPORT THE 2023 CSV

In [33]:
output_file = "chirundu_procurement_2023.csv"

df_2023.to_csv(
    output_file,
    sep="|",
    index=False
)

print(f"Saved successfully: {output_file}")

Saved successfully: chirundu_procurement_2023.csv