1.INSPECTION OF THE PDF STRUCTURE FILE

In [1]:
import pdfplumber

pdf_path = "2025-ANNUAL-PROCUREMENT-PLAN.pdf"

with pdfplumber.open(pdf_path) as pdf:
    print("Number of pages:", len(pdf.pages))

    for i, page in enumerate(pdf.pages, start=1):
        text = page.extract_text()

        print("\n" + "=" * 70)
        print(f"PAGE {i}")
        print("=" * 70)

        if text:
            print(text[:3000])
        else:
            print("No text extracted.")

Number of pages: 3

======================================================================
PAGE 1
======================================================================
2025 ANNUAL PROCUREMENT PLAN CHIRUNDU
A B C D E F G H I J K L M
1 Entity Chirundu Town Council
2 Procurement Plan for year 2025
3 Version 1
4 Procurement Budget 42,455,237.45
5 ZMW Control Total 42,455,237.45
6 Date Last Updated 1/7/2025
7 Comments
8
9 ZMW Estimated Budget FX Budget Amount
10 Class UNSPSC IFMIS GL Account Description Ref No Project Code Unit of Measure Quantity GOZ Other Total Currency Amount
11 goods 43210000 0 Procurement of compu1ter peripherals, equipments and accessories Each 784,850.00 784,850.00
12 goods 14111509 0 Procurement of office 2stationery, tonners, books, files and other acceEssaocrhies 1,000,000.00 1,000,000.00
13 goods 44000000 0 Procurement of Office3 equipment and accessories and supplies Each 722,100.00 722,100.00
14 goods 15100000 0 Procurement of fuels f4or council operations Each 913,400.00 913,400.00
15 goods 15100000 0 Procurement of fuels f5or council operations under the 2025 CDF Each 3,278,013.69 3,278,013.69
16 goods 26111601 0 Procurement of an ele6ctricity generator under supply and delivery Each 500,000.00 500,000.00
17 goods 26111601 0 Procurement of 2 gene7rator with 500W and a medium Each 67,600.00 67,600.00
18 consulting services 72000000 0 Repair and maintenan8ce of infrastructure Each 134,900.00 134,900.00
19 non consulting services 84111501 0 Procurement of accou9nting system Each 37,000.00 37,000.00
20 goods 27110000 0 Procurement of hand t1o0ols and personal protective equipments Each 1,000,000.00 1,000,000.00
21 goods 27000000 0 Procurement of tools a1n1d general machinery under Cash for work Each 600,000.00 600,000.00
22 goods 53103000 0 Procurement of T Shir1ts2 and Banners ( events) Each 230,450.00 230,450.00
23 goods 49000000 0 Procurement of sports1 a3ttires and recreation Each 37,600.00 33,600.00
24 consulting services 82100000 0 Procurement of adver1ts4, sound systems and communication servicesE daechvices 111,700.00 111,700.00
25 non consulting services 80141604 0 Procurement of Brand1in5g naming services and communication Each 245,851.03 245,851.03
26 non consulting services 60104909 0 Procurement of Zesco1 u6nits (electricity) Each 158,400.00 158,400.00
27 consulting services 92101600 0 Procurement of fire se1rv7ices (attires, tools and associate accessoriesE)ach 234,700.00 234,700.00
28 works 93140000 0 Procurement of WDC 1p8rojects in Njame (Community and Social SerivEeasc)h 135,875.68 135,875.68
29 works 93140000 0 Procurement of Comm1u9nity Projects under the 2025 CDF Each ########### 18,654,678.04
30 goods 47000000 0 Procurement of Cleani2n0g materials for the institution (equipment and Esuapcphlies) 51,540.00 51,540.00
31 consulting services 81112201 0 Servicing of the procur2e1ment unit photocopy machine (maintenance)Each 30,000.00 30,000.00
32 goods 15121520 0 Procurement of genera2l2 purpose lubricants Each 473,000.00 473,000.00
33 works 72131700 0 Construction of an Abl2u3tion Block at the Double Storey Building opposEitaec Chhirundu Boarder Post 90,000.00 90,000.00


======================================================================
PAGE 2
======================================================================
2025 ANNUAL PROCUREMENT PLAN CHIRUNDU
N O P Q R S T U V W X Y Z
1
2
3
4
5
6
7
8
9 Estimated dates
10 Source of Funds Prequalification (Y/N) Procurement Method Publication Award Start Public View (Y/N) Public View Justification Comments Source Project ID URI Rationale
11 Local resources N sb 2/3/2025 3/3/2025 3/10/2025Y Monthly procurements
12 Local resources N sb 1/13/2025 1/20/2025 1/21/2025Y Monthly procurements
13 Local resources N sb 1/13/2025 1/21/2025 1/22/2025Y Monthly procurements
14 Local resources N db 1/6/2025 1/13/2025 1/14/2025Y Running Contract
15 2025 CDF N db 3/4/2025 3/7/2025 3/10/2025Y Running Contract
16 Local resources N sb 2/3/2025 3/10/2025 3/31/2025Y
17 Local resources N sb 2/3/2025 2/10/2025 2/24/2025Y
18 Local resources N sb 3/17/2025 3/24/2025 4/1/2025Y
19 Local resources N sb 1/15/2025 1/27/2025 1/31/2025Y
20 Local resources N sb 2/10/2025 3/10/2025 3/17/2025Y Quartely procurements
21 Grant N sb 2/10/2025 2/20/2025 2/25/2025Y Quartely procurements
22 Local resources N sb 3/3/2025 3/5/2025 3/7/2025Y Quartely procurements
23 Local resources N sb 5/5/2025 5/12/2025 5/13/2025Y
24 Local resources N sb 1/21/2025 1/28/2025 2/10/2025Y Quartely Procurements
25 2025 CDF N sb 1/7/2025 1/29/2025 2/24/2025Y
26 Local resources N db 1/8/2025 1/13/2025 1/15/2025Y Monthly procurements
27 Local resources N sb 2/24/2025 2/28/2025 3/6/2025Y Monthly procurements
28 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
29 2025 CDF N obn 2/10/2025 5/15/2025 6/2/2025Y community projects yet to be identified
30 Local resources N sb 1/7/2025 1/10/2025 1/13/2025Y Monthly procurements
31 Local resources N sb 2/24/2025 2/28/2025 3/5/2025Y Quartely procurements
32 Local resources N sb 4/7/2025 4/11/2025 4/28/2025Y Quartely procurements
33 Local resources N sb 2/3/2025 2/10/2025 2/24/2025Y
34 Local resources N sb 5/5/2025 5/12/2025 5/26/2025Y
35 Local resources N sb 3/24/2025 3/28/2025 3/31/2025Y Quartely procurements
36 Grant and locally generated fundNs obn 3/31/2025 6/9/2025 6/30/2025Y Quartely procurements
37 2023 CDF project N sb 2/3/2025 2/10/2025 2/24/2025Y
38 Local resources N obn 4/16/2025 6/20/2025 7/14/2025Y
39 Local resources N sb 6/9/2025 6/16/2025 6/30/2025Y
40 Local resources N sb 7/21/2025 7/31/2025 8/14/2025Y
41 Local resources N sb 8/11/2025 8/20/2025 9/1/2025Y
42 Local resources N sb 8/18/2025 8/27/2025 9/8/2025Y
43 Local resources N sb 4/14/2025 4/21/2025 4/30/2025Y
44 Local resources N sb 4/14/2025 4/21/2025 4/30/2025Y
45 Local resources N sb 4/28/2025 5/15/2025 5/20/2025Y
46 Local resources N sb 6/9/2025 6/13/2025 6/10/2025Y
47 Local resources N sb 5/26/2025 6/4/2025 6/11/2025Y
48 Local resources N sb 1/15/2025 1/31/2025 2/18/2025Y Quarterly procurements
49 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
50 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
51 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
52 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
53 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
54 Local res

======================================================================
PAGE 3
======================================================================
2025 ANNUAL PROCUREMENT PLAN CHIRUNDU
AA
1
2
3
4
5
6
7
8
9
10 Type of Entry
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29 M
30
31
32
33
34
35
36 M
37
38 M
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
Page 3

INSPECTION OF PAGE 2

In [2]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[1]

    print("=" * 80)
    print("PAGE 2")
    print("=" * 80)

    text = page.extract_text()

    if text:
        print(text)
    else:
        print("No text extracted.")

================================================================================
PAGE 2
================================================================================
2025 ANNUAL PROCUREMENT PLAN CHIRUNDU
N O P Q R S T U V W X Y Z
1
2
3
4
5
6
7
8
9 Estimated dates
10 Source of Funds Prequalification (Y/N) Procurement Method Publication Award Start Public View (Y/N) Public View Justification Comments Source Project ID URI Rationale
11 Local resources N sb 2/3/2025 3/3/2025 3/10/2025Y Monthly procurements
12 Local resources N sb 1/13/2025 1/20/2025 1/21/2025Y Monthly procurements
13 Local resources N sb 1/13/2025 1/21/2025 1/22/2025Y Monthly procurements
14 Local resources N db 1/6/2025 1/13/2025 1/14/2025Y Running Contract
15 2025 CDF N db 3/4/2025 3/7/2025 3/10/2025Y Running Contract
16 Local resources N sb 2/3/2025 3/10/2025 3/31/2025Y
17 Local resources N sb 2/3/2025 2/10/2025 2/24/2025Y
18 Local resources N sb 3/17/2025 3/24/2025 4/1/2025Y
19 Local resources N sb 1/15/2025 1/27/2025 1/31/2025Y
20 Local resources N sb 2/10/2025 3/10/2025 3/17/2025Y Quartely procurements
21 Grant N sb 2/10/2025 2/20/2025 2/25/2025Y Quartely procurements
22 Local resources N sb 3/3/2025 3/5/2025 3/7/2025Y Quartely procurements
23 Local resources N sb 5/5/2025 5/12/2025 5/13/2025Y
24 Local resources N sb 1/21/2025 1/28/2025 2/10/2025Y Quartely Procurements
25 2025 CDF N sb 1/7/2025 1/29/2025 2/24/2025Y
26 Local resources N db 1/8/2025 1/13/2025 1/15/2025Y Monthly procurements
27 Local resources N sb 2/24/2025 2/28/2025 3/6/2025Y Monthly procurements
28 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
29 2025 CDF N obn 2/10/2025 5/15/2025 6/2/2025Y community projects yet to be identified
30 Local resources N sb 1/7/2025 1/10/2025 1/13/2025Y Monthly procurements
31 Local resources N sb 2/24/2025 2/28/2025 3/5/2025Y Quartely procurements
32 Local resources N sb 4/7/2025 4/11/2025 4/28/2025Y Quartely procurements
33 Local resources N sb 2/3/2025 2/10/2025 2/24/2025Y
34 Local resources N sb 5/5/2025 5/12/2025 5/26/2025Y
35 Local resources N sb 3/24/2025 3/28/2025 3/31/2025Y Quartely procurements
36 Grant and locally generated fundNs obn 3/31/2025 6/9/2025 6/30/2025Y Quartely procurements
37 2023 CDF project N sb 2/3/2025 2/10/2025 2/24/2025Y
38 Local resources N obn 4/16/2025 6/20/2025 7/14/2025Y
39 Local resources N sb 6/9/2025 6/16/2025 6/30/2025Y
40 Local resources N sb 7/21/2025 7/31/2025 8/14/2025Y
41 Local resources N sb 8/11/2025 8/20/2025 9/1/2025Y
42 Local resources N sb 8/18/2025 8/27/2025 9/8/2025Y
43 Local resources N sb 4/14/2025 4/21/2025 4/30/2025Y
44 Local resources N sb 4/14/2025 4/21/2025 4/30/2025Y
45 Local resources N sb 4/28/2025 5/15/2025 5/20/2025Y
46 Local resources N sb 6/9/2025 6/13/2025 6/10/2025Y
47 Local resources N sb 5/26/2025 6/4/2025 6/11/2025Y
48 Local resources N sb 1/15/2025 1/31/2025 2/18/2025Y Quarterly procurements
49 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
50 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
51 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
52 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
53 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
54 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
55 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
56 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
57 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
58 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
59 Local resources N sb 3/17/2025 3/31/2025 4/2/2025Y
60 Local resources N sb 2/10/2025 3/10/2025 3/17/2025Y Quartely procurements
Page 2

INSPECTION OF COODINATES

In [3]:
with pdfplumber.open(pdf_path) as pdf:
    for page_number in [1, 2]:
        page = pdf.pages[page_number - 1]

        print("\n" + "=" * 80)
        print(f"PAGE {page_number} — HEADER / COORDINATES")
        print("=" * 80)

        words = page.extract_words()

        for word in words:
            if word["top"] < 200:
                print(
                    f"{word['text']:<30} "
                    f"x0={word['x0']:.1f} "
                    f"x1={word['x1']:.1f} "
                    f"top={word['top']:.1f}"
                )

================================================================================
PAGE 1 — HEADER / COORDINATES
================================================================================
2025                           x0=426.2 x1=441.0 top=38.6
ANNUAL                         x0=442.9 x1=469.9 top=38.6
PROCUREMENT                    x0=471.8 x1=524.0 top=38.6
PLAN                           x0=526.1 x1=543.5 top=38.6
CHIRUNDU                       x0=545.4 x1=580.7 top=38.6
A                              x0=132.9 x1=137.3 top=44.2
B                              x0=251.3 x1=255.7 top=44.2
C                              x0=324.3 x1=329.1 top=44.2
D                              x0=392.0 x1=396.7 top=44.2
E                              x0=459.8 x1=464.2 top=44.2
F                              x0=529.6 x1=533.7 top=44.2
G                              x0=595.0 x1=600.2 top=44.2
H                              x0=653.7 x1=658.5 top=44.2
I                              x0=705.2 x1=707.1 top=44.2
J                              x0=749.9 x1=753.2 top=44.2
K                              x0=800.6 x1=805.0 top=44.2
L                              x0=856.3 x1=860.0 top=44.2
M                              x0=921.7 x1=927.2 top=44.2
1                              x0=46.2 x1=49.9 top=52.7
Entity                         x0=56.0 x1=74.3 top=52.9
Chirundu                       x0=216.1 x1=243.3 top=52.9
Town                           x0=245.2 x1=261.5 top=52.9
Council                        x0=263.5 x1=285.8 top=52.9
2                              x0=46.2 x1=49.9 top=61.0
Procurement                    x0=56.0 x1=96.9 top=61.1
Plan                           x0=99.3 x1=113.0 top=61.1
for                            x0=115.3 x1=123.9 top=61.1
year                           x0=126.2 x1=139.4 top=61.1
2025                           x0=216.1 x1=231.0 top=60.8
3                              x0=46.2 x1=49.9 top=69.3
Version                        x0=56.0 x1=80.2 top=69.4
1                              x0=216.1 x1=219.8 top=69.1
4                              x0=46.2 x1=49.9 top=77.6
Procurement                    x0=56.0 x1=96.9 top=77.7
Budget                         x0=99.3 x1=121.8 top=77.7
42,455,237.45                  x0=216.1 x1=259.0 top=77.4
5                              x0=46.2 x1=49.9 top=85.9
ZMW                            x0=56.0 x1=72.0 top=86.0
Control                        x0=74.0 x1=97.4 top=86.0
Total                          x0=99.8 x1=115.5 top=86.0
42,455,237.45                  x0=216.1 x1=259.0 top=85.6
6                              x0=46.2 x1=49.9 top=94.2
Date                           x0=56.0 x1=70.5 top=94.3
Last                           x0=72.4 x1=85.8 top=94.3
Updated                        x0=88.1 x1=114.4 top=94.3
1/7/2025                       x0=216.1 x1=242.2 top=93.9
7                              x0=46.2 x1=49.9 top=102.4
Comments                       x0=56.0 x1=90.2 top=102.6
8                              x0=46.2 x1=49.9 top=110.7
9                              x0=46.2 x1=49.9 top=119.0
ZMW                            x0=726.2 x1=739.3 top=118.8
Estimated                      x0=740.9 x1=767.3 top=118.8
Budget                         x0=768.9 x1=787.9 top=118.8
FX                             x0=872.5 x1=879.6 top=118.8
Budget                         x0=881.2 x1=900.1 top=118.8
Amount                         x0=901.7 x1=922.5 top=118.8
10                             x0=44.3 x1=51.7 top=127.3
Class                          x0=125.8 x1=143.2 top=127.8
UNSPSC                         x0=239.3 x1=267.0 top=127.8
IFMIS                          x0=297.4 x1=315.3 top=127.8
GL                             x0=317.3 x1=326.2 top=127.8
Account                        x0=328.6 x1=354.7 top=127.8
Description                    x0=375.5 x1=412.0 top=127.8
Ref                            x0=450.8 x1=461.1 top=127.8
No                             x0=463.5 x1=471.9 top=127.8
Project                        x0=510.7 x1=532.9 top=127.8
Code                           x0=535.2 x1=551.8 top=127.8
Unit                           x0=572.1 x1=584.7 top=127.8
of                             x0=587.1 x1=593.0 top=127.8
Measure                        x0=595.3 x1=622.5 top=127.8
Quantity                       x0=642.1 x1=669.0 top=127.8
GOZ                            x0=698.4 x1=713.0 top=127.8
Other                          x0=742.2 x1=759.7 top=127.8
Total                          x0=794.4 x1=810.1 top=127.8
Currency                       x0=843.1 x1=872.0 top=127.8
Amount                         x0=911.5 x1=936.2 top=127.8
11                             x0=44.3 x1=51.7 top=135.6
goods                          x0=56.0 x1=74.2 top=135.6
43210000                       x0=216.1 x1=245.8 top=135.6
0                              x0=292.9 x1=296.5 top=135.6
Procurement                    x0=362.6 x1=400.9 top=135.6
of                             x0=402.9 x1=408.5 top=135.6
compu1ter                      x0=410.5 x1=438.5 top=135.6
peripherals,                   x0=440.4 x1=475.3 top=135.6
equipments                     x0=477.3 x1=512.0 top=135.6
and                            x0=514.0 x1=525.1 top=135.6
accessories                    x0=527.0 x1=562.4 top=135.6
Each                           x0=567.5 x1=582.7 top=135.6
784,850.00                     x0=693.3 x1=726.8 top=135.6
784,850.00                     x0=795.9 x1=829.4 top=135.6
12                             x0=44.3 x1=51.7 top=143.8
goods                          x0=56.0 x1=74.2 top=143.8
14111509                       x0=216.1 x1=245.8 top=143.8
0                              x0=292.9 x1=296.5 top=143.8
Procurement                    x0=362.6 x1=400.9 top=143.8
of                             x0=402.9 x1=408.5 top=143.8
office                         x0=410.5 x1=426.6 top=143.8
2stationery,                   x0=428.1 x1=459.5 top=143.8
tonners,                       x0=461.5 x1=485.7 top=143.8
books,                         x0=487.7 x1=507.4 top=143.8
files                          x0=509.4 x1=521.2 top=143.8
and                            x0=523.2 x1=534.3 top=143.8
other                          x0=536.2 x1=551.5 top=143.8
acceEssaocrhies                x0=553.5 x1=588.9 top=143.8
1,000,000.00                   x0=687.7 x1=726.8 top=143.8
1,000,000.00                   x0=790.3 x1=829.4 top=143.8
13                             x0=44.3 x1=51.7 top=152.1
goods                          x0=56.0 x1=74.2 top=152.1
44000000                       x0=216.1 x1=245.8 top=152.1
0                              x0=292.9 x1=296.5 top=152.1
Procurement                    x0=362.6 x1=400.9 top=152.1
of                             x0=402.9 x1=408.5 top=152.1
Office3                        x0=410.5 x1=431.8 top=152.1
equipment                      x0=430.1 x1=461.4 top=152.1
and                            x0=463.4 x1=474.5 top=152.1
accessories                    x0=476.5 x1=511.9 top=152.1
and                            x0=513.9 x1=525.0 top=152.1
supplies                       x0=526.9 x1=551.3 top=152.1
Each                           x0=567.5 x1=582.7 top=152.1
722,100.00                     x0=693.3 x1=726.8 top=152.1
722,100.00                     x0=795.9 x1=829.4 top=152.1
14                             x0=44.3 x1=51.7 top=160.4
goods                          x0=56.0 x1=74.2 top=160.4
15100000                       x0=216.1 x1=245.8 top=160.4
0                              x0=292.9 x1=296.5 top=160.4
Procurement                    x0=362.6 x1=400.9 top=160.4
of                             x0=402.9 x1=408.5 top=160.4
fuels                          x0=410.5 x1=424.5 top=160.4
f4or                           x0=426.4 x1=434.2 top=160.4
council                        x0=436.2 x1=457.1 top=160.4
operations                     x0=458.9 x1=490.2 top=160.4
Each                           x0=567.5 x1=582.7 top=160.4
913,400.00                     x0=693.3 x1=726.8 top=160.4
913,400.00                     x0=795.9 x1=829.4 top=160.4
15                             x0=44.3 x1=51.7 top=168.7
goods                          x0=56.0 x1=74.2 top=168.7
15100000                       x0=216.1 x1=245.8 top=168.7
0                              x0=292.9 x1=296.5 top=168.7
Procurement                    x0=362.6 x1=400.9 top=168.7
of                             x0=402.9 x1=408.5 top=168.7
fuels                          x0=410.5 x1=424.5 top=168.7
f5or                           x0=426.4 x1=434.2 top=168.7
council                        x0=436.2 x1=457.1 top=168.7
operations                     x0=458.9 x1=490.2 top=168.7
under                          x0=492.2 x1=509.2 top=168.7
the                            x0=511.2 x1=520.5 top=168.7
2025                           x0=522.5 x1=537.3 top=168.7
CDF                            x0=539.3 x1=552.9 top=168.7
Each                           x0=567.5 x1=582.7 top=168.7
3,278,013.69                   x0=687.7 x1=726.8 top=168.7
3,278,013.69                   x0=790.3 x1=829.4 top=168.7
16                             x0=44.3 x1=51.7 top=177.0
goods                          x0=56.0 x1=74.2 top=177.0
26111601                       x0=216.1 x1=245.8 top=177.0
0                              x0=292.9 x1=296.5 top=177.0
Procurement                    x0=362.6 x1=400.9 top=177.0
of                             x0=402.9 x1=408.5 top=177.0
an                             x0=410.5 x1=417.9 top=177.0
ele6ctricity                   x0=419.8 x1=447.8 top=177.0
generator                      x0=449.6 x1=478.3 top=177.0
under                          x0=480.3 x1=497.4 top=177.0
supply                         x0=499.4 x1=518.5 top=177.0
and                            x0=520.3 x1=531.4 top=177.0
delivery                       x0=533.4 x1=556.5 top=177.0
Each                           x0=567.5 x1=582.7 top=177.0
500,000.00                     x0=693.3 x1=726.8 top=177.0
500,000.00                     x0=795.9 x1=829.4 top=177.0
17                             x0=44.3 x1=51.7 top=185.3
goods                          x0=56.0 x1=74.2 top=185.3
26111601                       x0=216.1 x1=245.8 top=185.3
0                              x0=292.9 x1=296.5 top=185.3
Procurement                    x0=362.6 x1=400.9 top=185.3
of                             x0=402.9 x1=408.5 top=185.3
2                              x0=410.5 x1=414.2 top=185.3
gene7rator                     x0=416.1 x1=444.8 top=185.3
with                           x0=446.8 x1=458.6 top=185.3
500W                           x0=462.5 x1=479.8 top=185.3
and                            x0=482.2 x1=493.3 top=185.3
a                              x0=495.3 x1=499.0 top=185.3
medium                         x0=500.9 x1=524.8 top=185.3
Each                           x0=567.5 x1=582.7 top=185.3
67,600.00                      x0=697.1 x1=726.9 top=185.3
67,600.00                      x0=799.7 x1=829.5 top=185.3
18                             x0=44.3 x1=51.7 top=193.6
consulting                     x0=56.0 x1=86.1 top=193.6
services                       x0=88.0 x1=112.8 top=193.6
72000000                       x0=216.1 x1=245.8 top=193.6
0                              x0=292.9 x1=296.5 top=193.6
Repair                         x0=362.6 x1=382.3 top=193.6
and                            x0=384.2 x1=395.3 top=193.6
maintenan8ce                   x0=397.3 x1=435.7 top=193.6
of                             x0=437.7 x1=443.2 top=193.6
infrastructure                 x0=445.2 x1=484.6 top=193.6
Each                           x0=567.5 x1=582.7 top=193.6
134,900.00                     x0=693.3 x1=726.8 top=193.6
134,900.00                     x0=795.9 x1=829.4 top=193.6

================================================================================
PAGE 2 — HEADER / COORDINATES
================================================================================
2025                           x0=426.2 x1=441.0 top=38.6
ANNUAL                         x0=442.9 x1=469.9 top=38.6
PROCUREMENT                    x0=471.8 x1=524.0 top=38.6
PLAN                           x0=526.1 x1=543.5 top=38.6
CHIRUNDU                       x0=545.4 x1=580.7 top=38.6
N                              x0=116.8 x1=121.5 top=44.2
O                              x0=206.4 x1=211.6 top=44.2
P                              x0=301.1 x1=305.5 top=44.2
Q                              x0=385.2 x1=390.4 top=44.2
R                              x0=442.9 x1=447.6 top=44.2
S                              x0=489.2 x1=493.6 top=44.2
T                              x0=547.6 x1=551.7 top=44.2
U                              x0=631.4 x1=636.2 top=44.2
V                              x0=710.0 x1=714.4 top=44.2
W                              x0=766.2 x1=772.4 top=44.2
X                              x0=822.0 x1=826.4 top=44.2
Y                              x0=869.3 x1=873.7 top=44.2
Z                              x0=916.8 x1=920.8 top=44.2
1                              x0=62.8 x1=66.4 top=52.7
2                              x0=62.8 x1=66.4 top=61.0
3                              x0=62.8 x1=66.4 top=69.3
4                              x0=62.8 x1=66.4 top=77.6
5                              x0=62.8 x1=66.4 top=85.9
6                              x0=62.8 x1=66.4 top=94.2
7                              x0=62.8 x1=66.4 top=102.4
8                              x0=62.8 x1=66.4 top=110.7
9                              x0=62.8 x1=66.4 top=119.0
Estimated                      x0=407.9 x1=439.6 top=119.5
dates                          x0=441.9 x1=459.0 top=119.5
10                             x0=60.8 x1=68.2 top=127.3
Source                         x0=92.4 x1=115.0 top=127.8
of                             x0=117.0 x1=122.9 top=127.8
Funds                          x0=125.2 x1=144.8 top=127.8
Prequalification               x0=174.5 x1=224.5 top=127.8
(Y/N)                          x0=226.8 x1=242.6 top=127.8
Procurement                    x0=269.4 x1=310.3 top=127.8
Method                         x0=312.7 x1=336.1 top=127.8
Publication                    x0=369.4 x1=405.2 top=127.8
Award                          x0=434.6 x1=454.7 top=127.8
Start                          x0=483.4 x1=498.3 top=127.8
Public                         x0=521.7 x1=541.4 top=127.8
View                           x0=543.7 x1=558.6 top=127.8
(Y/N)                          x0=561.1 x1=576.8 top=127.8
Public                         x0=593.8 x1=613.5 top=127.8
View                           x0=615.9 x1=630.7 top=127.8
Justification                  x0=633.2 x1=672.5 top=127.8
Comments                       x0=694.5 x1=728.7 top=127.8
Source                         x0=757.9 x1=780.5 top=127.8
Project                        x0=808.2 x1=830.4 top=127.8
ID                             x0=832.7 x1=839.4 top=127.8
URI                            x0=865.4 x1=876.9 top=127.8
Rationale                      x0=903.4 x1=933.5 top=127.8
11                             x0=60.8 x1=68.2 top=135.6
Local                          x0=72.6 x1=88.6 top=135.6
resources                      x0=90.3 x1=119.7 top=135.6
N                              x0=167.8 x1=172.5 top=135.6
sb                             x0=252.3 x1=259.3 top=135.6
2/3/2025                       x0=392.3 x1=418.4 top=135.6
3/3/2025                       x0=442.0 x1=468.1 top=135.6
3/10/2025Y                     x0=481.0 x1=518.2 top=135.6
Monthly                        x0=681.8 x1=705.1 top=135.6
procurements                   x0=707.0 x1=748.0 top=135.6
12                             x0=60.8 x1=68.2 top=143.8
Local                          x0=72.6 x1=88.6 top=143.8
resources                      x0=90.3 x1=119.7 top=143.8
N                              x0=167.8 x1=172.5 top=143.8
sb                             x0=252.3 x1=259.3 top=143.8
1/13/2025                      x0=388.6 x1=418.4 top=143.8
1/20/2025                      x0=438.3 x1=468.1 top=143.8
1/21/2025Y                     x0=481.0 x1=518.2 top=143.8
Monthly                        x0=681.8 x1=705.1 top=143.8
procurements                   x0=707.0 x1=748.0 top=143.8
13                             x0=60.8 x1=68.2 top=152.1
Local                          x0=72.6 x1=88.6 top=152.1
resources                      x0=90.3 x1=119.7 top=152.1
N                              x0=167.8 x1=172.5 top=152.1
sb                             x0=252.3 x1=259.3 top=152.1
1/13/2025                      x0=388.6 x1=418.4 top=152.1
1/21/2025                      x0=438.3 x1=468.1 top=152.1
1/22/2025Y                     x0=481.0 x1=518.2 top=152.1
Monthly                        x0=681.8 x1=705.1 top=152.1
procurements                   x0=707.0 x1=748.0 top=152.1
14                             x0=60.8 x1=68.2 top=160.4
Local                          x0=72.6 x1=88.6 top=160.4
resources                      x0=90.3 x1=119.7 top=160.4
N                              x0=167.8 x1=172.5 top=160.4
db                             x0=252.3 x1=259.6 top=160.4
1/6/2025                       x0=392.3 x1=418.4 top=160.4
1/13/2025                      x0=438.3 x1=468.1 top=160.4
1/14/2025Y                     x0=481.0 x1=518.2 top=160.4
Running                        x0=681.8 x1=706.7 top=160.4
Contract                       x0=708.7 x1=734.0 top=160.4
15                             x0=60.8 x1=68.2 top=168.7
2025                           x0=72.6 x1=87.4 top=168.7
CDF                            x0=89.4 x1=103.0 top=168.7
N                              x0=167.8 x1=172.5 top=168.7
db                             x0=252.3 x1=259.6 top=168.7
3/4/2025                       x0=392.3 x1=418.4 top=168.7
3/7/2025                       x0=442.0 x1=468.1 top=168.7
3/10/2025Y                     x0=481.0 x1=518.2 top=168.7
Running                        x0=681.8 x1=706.7 top=168.7
Contract                       x0=708.7 x1=734.0 top=168.7
16                             x0=60.8 x1=68.2 top=177.0
Local                          x0=72.6 x1=88.6 top=177.0
resources                      x0=90.3 x1=119.7 top=177.0
N                              x0=167.8 x1=172.5 top=177.0
sb                             x0=252.3 x1=259.3 top=177.0
2/3/2025                       x0=392.3 x1=418.4 top=177.0
3/10/2025                      x0=438.3 x1=468.1 top=177.0
3/31/2025Y                     x0=481.0 x1=518.2 top=177.0
17                             x0=60.8 x1=68.2 top=185.3
Local                          x0=72.6 x1=88.6 top=185.3
resources                      x0=90.3 x1=119.7 top=185.3
N                              x0=167.8 x1=172.5 top=185.3
sb                             x0=252.3 x1=259.3 top=185.3
2/3/2025                       x0=392.3 x1=418.4 top=185.3
2/10/2025                      x0=438.3 x1=468.1 top=185.3
2/24/2025Y                     x0=481.0 x1=518.2 top=185.3
18                             x0=60.8 x1=68.2 top=193.6
Local                          x0=72.6 x1=88.6 top=193.6
resources                      x0=90.3 x1=119.7 top=193.6
N                              x0=167.8 x1=172.5 top=193.6
sb                             x0=252.3 x1=259.3 top=193.6
3/17/2025                      x0=388.6 x1=418.4 top=193.6
3/24/2025                      x0=438.3 x1=468.1 top=193.6
4/1/2025Y                      x0=484.8 x1=518.2 top=193.6

GET ONLY THE COLUMN HEADERS

In [4]:
with pdfplumber.open(pdf_path) as pdf:

    # PAGE 1
    page1 = pdf.pages[0]
    words1 = page1.extract_words()

    print("=" * 80)
    print("PAGE 1 — IMPORTANT HEADERS")
    print("=" * 80)

    for word in words1:
        if 95 <= word["top"] <= 150:
            print(
                f"{word['text']:<30} "
                f"x0={word['x0']:.1f} "
                f"x1={word['x1']:.1f} "
                f"top={word['top']:.1f}"
            )

    # PAGE 2
    page2 = pdf.pages[1]
    words2 = page2.extract_words()

    print("\n" + "=" * 80)
    print("PAGE 2 — IMPORTANT HEADERS")
    print("=" * 80)

    for word in words2:
        if 95 <= word["top"] <= 150:
            print(
                f"{word['text']:<30} "
                f"x0={word['x0']:.1f} "
                f"x1={word['x1']:.1f} "
                f"top={word['top']:.1f}"
            )

================================================================================
PAGE 1 — IMPORTANT HEADERS
================================================================================
7                              x0=46.2 x1=49.9 top=102.4
Comments                       x0=56.0 x1=90.2 top=102.6
8                              x0=46.2 x1=49.9 top=110.7
9                              x0=46.2 x1=49.9 top=119.0
ZMW                            x0=726.2 x1=739.3 top=118.8
Estimated                      x0=740.9 x1=767.3 top=118.8
Budget                         x0=768.9 x1=787.9 top=118.8
FX                             x0=872.5 x1=879.6 top=118.8
Budget                         x0=881.2 x1=900.1 top=118.8
Amount                         x0=901.7 x1=922.5 top=118.8
10                             x0=44.3 x1=51.7 top=127.3
Class                          x0=125.8 x1=143.2 top=127.8
UNSPSC                         x0=239.3 x1=267.0 top=127.8
IFMIS                          x0=297.4 x1=315.3 top=127.8
GL                             x0=317.3 x1=326.2 top=127.8
Account                        x0=328.6 x1=354.7 top=127.8
Description                    x0=375.5 x1=412.0 top=127.8
Ref                            x0=450.8 x1=461.1 top=127.8
No                             x0=463.5 x1=471.9 top=127.8
Project                        x0=510.7 x1=532.9 top=127.8
Code                           x0=535.2 x1=551.8 top=127.8
Unit                           x0=572.1 x1=584.7 top=127.8
of                             x0=587.1 x1=593.0 top=127.8
Measure                        x0=595.3 x1=622.5 top=127.8
Quantity                       x0=642.1 x1=669.0 top=127.8
GOZ                            x0=698.4 x1=713.0 top=127.8
Other                          x0=742.2 x1=759.7 top=127.8
Total                          x0=794.4 x1=810.1 top=127.8
Currency                       x0=843.1 x1=872.0 top=127.8
Amount                         x0=911.5 x1=936.2 top=127.8
11                             x0=44.3 x1=51.7 top=135.6
goods                          x0=56.0 x1=74.2 top=135.6
43210000                       x0=216.1 x1=245.8 top=135.6
0                              x0=292.9 x1=296.5 top=135.6
Procurement                    x0=362.6 x1=400.9 top=135.6
of                             x0=402.9 x1=408.5 top=135.6
compu1ter                      x0=410.5 x1=438.5 top=135.6
peripherals,                   x0=440.4 x1=475.3 top=135.6
equipments                     x0=477.3 x1=512.0 top=135.6
and                            x0=514.0 x1=525.1 top=135.6
accessories                    x0=527.0 x1=562.4 top=135.6
Each                           x0=567.5 x1=582.7 top=135.6
784,850.00                     x0=693.3 x1=726.8 top=135.6
784,850.00                     x0=795.9 x1=829.4 top=135.6
12                             x0=44.3 x1=51.7 top=143.8
goods                          x0=56.0 x1=74.2 top=143.8
14111509                       x0=216.1 x1=245.8 top=143.8
0                              x0=292.9 x1=296.5 top=143.8
Procurement                    x0=362.6 x1=400.9 top=143.8
of                             x0=402.9 x1=408.5 top=143.8
office                         x0=410.5 x1=426.6 top=143.8
2stationery,                   x0=428.1 x1=459.5 top=143.8
tonners,                       x0=461.5 x1=485.7 top=143.8
books,                         x0=487.7 x1=507.4 top=143.8
files                          x0=509.4 x1=521.2 top=143.8
and                            x0=523.2 x1=534.3 top=143.8
other                          x0=536.2 x1=551.5 top=143.8
acceEssaocrhies                x0=553.5 x1=588.9 top=143.8
1,000,000.00                   x0=687.7 x1=726.8 top=143.8
1,000,000.00                   x0=790.3 x1=829.4 top=143.8

================================================================================
PAGE 2 — IMPORTANT HEADERS
================================================================================
7                              x0=62.8 x1=66.4 top=102.4
8                              x0=62.8 x1=66.4 top=110.7
9                              x0=62.8 x1=66.4 top=119.0
Estimated                      x0=407.9 x1=439.6 top=119.5
dates                          x0=441.9 x1=459.0 top=119.5
10                             x0=60.8 x1=68.2 top=127.3
Source                         x0=92.4 x1=115.0 top=127.8
of                             x0=117.0 x1=122.9 top=127.8
Funds                          x0=125.2 x1=144.8 top=127.8
Prequalification               x0=174.5 x1=224.5 top=127.8
(Y/N)                          x0=226.8 x1=242.6 top=127.8
Procurement                    x0=269.4 x1=310.3 top=127.8
Method                         x0=312.7 x1=336.1 top=127.8
Publication                    x0=369.4 x1=405.2 top=127.8
Award                          x0=434.6 x1=454.7 top=127.8
Start                          x0=483.4 x1=498.3 top=127.8
Public                         x0=521.7 x1=541.4 top=127.8
View                           x0=543.7 x1=558.6 top=127.8
(Y/N)                          x0=561.1 x1=576.8 top=127.8
Public                         x0=593.8 x1=613.5 top=127.8
View                           x0=615.9 x1=630.7 top=127.8
Justification                  x0=633.2 x1=672.5 top=127.8
Comments                       x0=694.5 x1=728.7 top=127.8
Source                         x0=757.9 x1=780.5 top=127.8
Project                        x0=808.2 x1=830.4 top=127.8
ID                             x0=832.7 x1=839.4 top=127.8
URI                            x0=865.4 x1=876.9 top=127.8
Rationale                      x0=903.4 x1=933.5 top=127.8
11                             x0=60.8 x1=68.2 top=135.6
Local                          x0=72.6 x1=88.6 top=135.6
resources                      x0=90.3 x1=119.7 top=135.6
N                              x0=167.8 x1=172.5 top=135.6
sb                             x0=252.3 x1=259.3 top=135.6
2/3/2025                       x0=392.3 x1=418.4 top=135.6
3/3/2025                       x0=442.0 x1=468.1 top=135.6
3/10/2025Y                     x0=481.0 x1=518.2 top=135.6
Monthly                        x0=681.8 x1=705.1 top=135.6
procurements                   x0=707.0 x1=748.0 top=135.6
12                             x0=60.8 x1=68.2 top=143.8
Local                          x0=72.6 x1=88.6 top=143.8
resources                      x0=90.3 x1=119.7 top=143.8
N                              x0=167.8 x1=172.5 top=143.8
sb                             x0=252.3 x1=259.3 top=143.8
1/13/2025                      x0=388.6 x1=418.4 top=143.8
1/20/2025                      x0=438.3 x1=468.1 top=143.8
1/21/2025Y                     x0=481.0 x1=518.2 top=143.8
Monthly                        x0=681.8 x1=705.1 top=143.8
procurements                   x0=707.0 x1=748.0 top=143.8

INSPECTION OF THE COMPLETE PROCUREMENT ROW

In [5]:
with pdfplumber.open(pdf_path) as pdf:

    page = pdf.pages[0]
    words = page.extract_words()

    print("=" * 100)
    print("PAGE 1 — ROW 11")
    print("=" * 100)

    for word in words:
        if 135 <= word["top"] <= 150:
            print(
                f"{word['text']:<35} "
                f"x0={word['x0']:.1f} "
                f"x1={word['x1']:.1f} "
                f"top={word['top']:.1f}"
            )

====================================================================================================
PAGE 1 — ROW 11
====================================================================================================
11                                  x0=44.3 x1=51.7 top=135.6
goods                               x0=56.0 x1=74.2 top=135.6
43210000                            x0=216.1 x1=245.8 top=135.6
0                                   x0=292.9 x1=296.5 top=135.6
Procurement                         x0=362.6 x1=400.9 top=135.6
of                                  x0=402.9 x1=408.5 top=135.6
compu1ter                           x0=410.5 x1=438.5 top=135.6
peripherals,                        x0=440.4 x1=475.3 top=135.6
equipments                          x0=477.3 x1=512.0 top=135.6
and                                 x0=514.0 x1=525.1 top=135.6
accessories                         x0=527.0 x1=562.4 top=135.6
Each                                x0=567.5 x1=582.7 top=135.6
784,850.00                          x0=693.3 x1=726.8 top=135.6
784,850.00                          x0=795.9 x1=829.4 top=135.6
12                                  x0=44.3 x1=51.7 top=143.8
goods                               x0=56.0 x1=74.2 top=143.8
14111509                            x0=216.1 x1=245.8 top=143.8
0                                   x0=292.9 x1=296.5 top=143.8
Procurement                         x0=362.6 x1=400.9 top=143.8
of                                  x0=402.9 x1=408.5 top=143.8
office                              x0=410.5 x1=426.6 top=143.8
2stationery,                        x0=428.1 x1=459.5 top=143.8
tonners,                            x0=461.5 x1=485.7 top=143.8
books,                              x0=487.7 x1=507.4 top=143.8
files                               x0=509.4 x1=521.2 top=143.8
and                                 x0=523.2 x1=534.3 top=143.8
other                               x0=536.2 x1=551.5 top=143.8
acceEssaocrhies                     x0=553.5 x1=588.9 top=143.8
1,000,000.00                        x0=687.7 x1=726.8 top=143.8
1,000,000.00                        x0=790.3 x1=829.4 top=143.8

INSPECTION OF PAGE 2 COODINATES

In [6]:
with pdfplumber.open(pdf_path) as pdf:

    page = pdf.pages[1]
    words = page.extract_words()

    print("=" * 100)
    print("PAGE 2 — ROW 11")
    print("=" * 100)

    for word in words:
        if 135 <= word["top"] <= 150:
            print(
                f"{word['text']:<35} "
                f"x0={word['x0']:.1f} "
                f"x1={word['x1']:.1f} "
                f"top={word['top']:.1f}"
            )

====================================================================================================
PAGE 2 — ROW 11
====================================================================================================
11                                  x0=60.8 x1=68.2 top=135.6
Local                               x0=72.6 x1=88.6 top=135.6
resources                           x0=90.3 x1=119.7 top=135.6
N                                   x0=167.8 x1=172.5 top=135.6
sb                                  x0=252.3 x1=259.3 top=135.6
2/3/2025                            x0=392.3 x1=418.4 top=135.6
3/3/2025                            x0=442.0 x1=468.1 top=135.6
3/10/2025Y                          x0=481.0 x1=518.2 top=135.6
Monthly                             x0=681.8 x1=705.1 top=135.6
procurements                        x0=707.0 x1=748.0 top=135.6
12                                  x0=60.8 x1=68.2 top=143.8
Local                               x0=72.6 x1=88.6 top=143.8
resources                           x0=90.3 x1=119.7 top=143.8
N                                   x0=167.8 x1=172.5 top=143.8
sb                                  x0=252.3 x1=259.3 top=143.8
1/13/2025                           x0=388.6 x1=418.4 top=143.8
1/20/2025                           x0=438.3 x1=468.1 top=143.8
1/21/2025Y                          x0=481.0 x1=518.2 top=143.8
Monthly                             x0=681.8 x1=705.1 top=143.8
procurements                        x0=707.0 x1=748.0 top=143.8

EXTRACTION OF PAGE 1

In [3]:
import pdfplumber
import pandas as pd
import re

pdf_path = "2025-ANNUAL-PROCUREMENT-PLAN.pdf"

# Page 1
with pdfplumber.open(pdf_path) as pdf:
    page1 = pdf.pages[0]
    words1 = page1.extract_words()

# Column boundaries for Page 1
columns_page1 = {
    "Category": (50, 210),
    "Procurement item": (350, 566),
    "Estimated Amount": (790, 840)
}

# Group words by row
rows_page1 = []

for word in words1:

    # Ignore header information
    if word["top"] < 130:
        continue

    matched_row = None

    for row in rows_page1:
        if abs(row["top"] - word["top"]) <= 2:
            matched_row = row
            break

    if matched_row is None:
        matched_row = {
            "top": word["top"],
            "words": []
        }
        rows_page1.append(matched_row)

    matched_row["words"].append(word)

rows_page1.sort(key=lambda x: x["top"])

# Extract required fields
records_page1 = []

for row in rows_page1:

    record = {}

    for column, (x_start, x_end) in columns_page1.items():

        selected_words = [
            w["text"]
            for w in row["words"]
            if x_start <= w["x0"] < x_end
        ]

        record[column] = " ".join(selected_words).strip()

    records_page1.append(record)

df_page1 = pd.DataFrame(records_page1)

print(df_page1.head(10).to_string(index=False))
print("\nNumber of extracted rows:", len(df_page1))

               Category                                                                   Procurement item Estimated Amount
                  goods                   Procurement of compu1ter peripherals, equipments and accessories       784,850.00
                  goods Procurement of office 2stationery, tonners, books, files and other acceEssaocrhies     1,000,000.00
                  goods                      Procurement of Office3 equipment and accessories and supplies       722,100.00
                  goods                                       Procurement of fuels f4or council operations       913,400.00
                  goods                    Procurement of fuels f5or council operations under the 2025 CDF     3,278,013.69
                  goods                 Procurement of an ele6ctricity generator under supply and delivery       500,000.00
                  goods                                 Procurement of 2 gene7rator with 500W and a medium        67,600.00
    consulting services                                          Repair and maintenan8ce of infrastructure       134,900.00
non consulting services                                                  Procurement of accou9nting system        37,000.00
                  goods                     Procurement of hand t1o0ols and personal protective equipments     1,000,000.00

Number of extracted rows: 51

IDENTIFYING THE 51ST ROW

In [4]:
print(df_page1.to_string(index=True))

                   Category                                                                    Procurement item Estimated Amount
0                     goods                    Procurement of compu1ter peripherals, equipments and accessories       784,850.00
1                     goods  Procurement of office 2stationery, tonners, books, files and other acceEssaocrhies     1,000,000.00
2                     goods                       Procurement of Office3 equipment and accessories and supplies       722,100.00
3                     goods                                        Procurement of fuels f4or council operations       913,400.00
4                     goods                     Procurement of fuels f5or council operations under the 2025 CDF     3,278,013.69
5                     goods                  Procurement of an ele6ctricity generator under supply and delivery       500,000.00
6                     goods                                  Procurement of 2 gene7rator with 500W and a medium        67,600.00
7       consulting services                                           Repair and maintenan8ce of infrastructure       134,900.00
8   non consulting services                                                   Procurement of accou9nting system        37,000.00
9                     goods                      Procurement of hand t1o0ols and personal protective equipments     1,000,000.00
10                    goods                    Procurement of tools a1n1d general machinery under Cash for work       600,000.00
11                    goods                                     Procurement of T Shir1ts2 and Banners ( events)       230,450.00
12                    goods                                      Procurement of sports1 a3ttires and recreation        33,600.00
13      consulting services                 Procurement of adver1ts4, sound systems and communication servicesE       111,700.00
14  non consulting services                         Procurement of Brand1in5g naming services and communication       245,851.03
15  non consulting services                                          Procurement of Zesco1 u6nits (electricity)       158,400.00
16      consulting services       Procurement of fire se1rv7ices (attires, tools and associate accessoriesE)ach       234,700.00
17                    works           Procurement of WDC 1p8rojects in Njame (Community and Social SerivEeasc)h       135,875.68
18                    works                              Procurement of Comm1u9nity Projects under the 2025 CDF
19                    goods              Procurement of Cleani2n0g materials for the institution (equipment and        51,540.00
20      consulting services             Servicing of the procur2e1ment unit photocopy machine (maintenance)Each        30,000.00
21                    goods                                         Procurement of genera2l2 purpose lubricants       473,000.00
22                    works       Construction of an Abl2u3tion Block at the Double Storey Building opposEitaec        90,000.00
23                    works                                                       Construction of an Aba2t4toir       300,000.00
24                    goods                             Vehicles maintenance2 a5nd servicing /plant maintenance       525,000.00
25                    works                                              Paving of the township2 6roads (1,6km)     5,240,000.00
26                    works             Construction of the com27pletion of Chibende Rural Health Centre undeEr       538,726.57
27                    works                                                Construction of the Co2m8munity Hall     2,000,000.00
28                    works                                            Boreholes,pumps and 2w9ater reticulation       290,100.00
29                    works                                          Construction of a Sola3r 0powered Borehole       800,000.00
30                    works                            Construction of (1) Abl3u1tion Block at Mission Hospital       300,000.00
31                    works                                                  Rehabilitation of towns3h2ip roads       200,000.00
32                    works                            Construction of a VIP L3a3trine Toilet at M15 Checkpoint        50,000.00
33                    works                                                Construction of Kaban3a4na Truckpark       535,959.96
34                    works                                      Installation and mainte3n5ance of streetlights       137,700.00
35                    goods                                                    Repair of heavy duty e3q6uipment        50,000.00
36                    goods                          Intergrity committee S3ta7tionery, attires and accessories       110,025.00
37  non consulting services             Conference hiring for 3C8ouncil meeting and refreshments for differentE       270,530.00
38                    works             Procurement of WDC 3p9rojects in Chirundu West (Community and SocEiaacl       135,875.68
39                    works         Procurement of WDC 4p0rojects in Chirundu Central (Community and SEoacciahl       135,875.68
40                    works                  Procurement of WDC 4p1rojects in Chirundu Kanyanga (Community anEd       135,875.68
41                    works          Procurement of WDC 4p2rojects in Chirundu Lusitu (Community and SoEcaiaclh       135,875.68
42                    works                 Procurement of WDC 4p3rojects in Chirundu Ibbwemunyama (CommunEitay       135,875.68
43                    works                  Procurement of WDC 4p4rojects in Chirundu Sikoongo (Community andE       135,875.68
44                    works                     Procurement of WDC 4p5rojects in Chirundu Musaya (Community and       135,875.68
45                    works                Procurement of WDC 4p6rojects in Chirundu Kapululira (Community andE       135,875.68
46                    works                 Procurement of WDC 4p7rojects in Chirundu Mushungu (Community anEda       135,875.68
47                    works               Procurement of WDC 4p8rojects in Chirundu Nkandabwe (Community aEnadc       135,875.68
48                    works                  Procurement of WDC 4p9rojects in Chirundu Ngombe ilede (CommunityE       135,875.68
49                    goods       Procurement of hand t5o0ols and personal protective equipments AdditiEoancahl       124,905.00
50                                                                                                       Page 1

SINCE 50 [blank] Page [blank] ,LETS REMOVE THE FOOTER

In [5]:
df_page1 = df_page1[
    df_page1["Category"].notna() &
    (df_page1["Category"].str.strip() != "")
].copy()

df_page1 = df_page1.reset_index(drop=True)

print("Number of procurement records:", len(df_page1))

Number of procurement records: 50

EXTRACTION OF PAGE 2

In [6]:
# Page 2
with pdfplumber.open(pdf_path) as pdf:
    page2 = pdf.pages[1]
    words2 = page2.extract_words()

# Column boundaries for Page 2
columns_page2 = {
    "Source of Funds": (60, 150),
    "Procurement Method": (240, 270),
    "date": (480, 520)
}

# Group words by row
rows_page2 = []

for word in words2:

    # Ignore header information
    if word["top"] < 130:
        continue

    matched_row = None

    for row in rows_page2:
        if abs(row["top"] - word["top"]) <= 2:
            matched_row = row
            break

    if matched_row is None:
        matched_row = {
            "top": word["top"],
            "words": []
        }
        rows_page2.append(matched_row)

    matched_row["words"].append(word)

rows_page2.sort(key=lambda x: x["top"])

# Extract fields
records_page2 = []

for row in rows_page2:

    record = {}

    for column, (x_start, x_end) in columns_page2.items():

        selected_words = [
            w["text"]
            for w in row["words"]
            if x_start <= w["x0"] < x_end
        ]

        record[column] = " ".join(selected_words).strip()

    records_page2.append(record)

df_page2 = pd.DataFrame(records_page2)

print(df_page2.head(10).to_string(index=False))
print("\nNumber of extracted rows:", len(df_page2))

   Source of Funds Procurement Method       date
11 Local resources                 sb 3/10/2025Y
12 Local resources                 sb 1/21/2025Y
13 Local resources                 sb 1/22/2025Y
14 Local resources                 db 1/14/2025Y
       15 2025 CDF                 db 3/10/2025Y
16 Local resources                 sb 3/31/2025Y
17 Local resources                 sb 2/24/2025Y
18 Local resources                 sb  4/1/2025Y
19 Local resources                 sb 1/31/2025Y
20 Local resources                 sb 3/17/2025Y

Number of extracted rows: 51

REMOVE THE PAGE 2 FOOTER

In [7]:
df_page2 = df_page2[
    df_page2["Source of Funds"].notna() &
    (df_page2["Source of Funds"].str.strip() != "")
].copy()

df_page2 = df_page2.reset_index(drop=True)

print("Number of procurement records:", len(df_page2))

Number of procurement records: 50

CLEAN THE START DATE

In [8]:
df_page2["date"] = (
    df_page2["date"]
    .str.replace(r"Y$", "", regex=True)
    .str.strip()
)

df_page2["date"] = pd.to_datetime(
    df_page2["date"],
    format="%m/%d/%Y",
    errors="coerce"
)

print(df_page2.head(10).to_string(index=False))

   Source of Funds Procurement Method       date
11 Local resources                 sb 2025-03-10
12 Local resources                 sb 2025-01-21
13 Local resources                 sb 2025-01-22
14 Local resources                 db 2025-01-14
       15 2025 CDF                 db 2025-03-10
16 Local resources                 sb 2025-03-31
17 Local resources                 sb 2025-02-24
18 Local resources                 sb 2025-04-01
19 Local resources                 sb 2025-01-31
20 Local resources                 sb 2025-03-17

CHECKING BOTH SIDES BEFORE MERGING

In [9]:
print("Page 1 records:", len(df_page1))
print("Page 2 records:", len(df_page2))

Page 1 records: 50
Page 2 records: 50

In [10]:
df_2025 = pd.concat(
    [
        df_page1,
        df_page2
    ],
    axis=1
)

print("Number of records:", len(df_2025))
print("\nColumns:")
print(df_2025.columns.tolist())

print("\nFirst 10 records:")
print(df_2025.head(10).to_string(index=False))

Number of records: 50

Columns:
['Category', 'Procurement item', 'Estimated Amount', 'Source of Funds', 'Procurement Method', 'date']

First 10 records:
               Category                                                                   Procurement item Estimated Amount    Source of Funds Procurement Method       date
                  goods                   Procurement of compu1ter peripherals, equipments and accessories       784,850.00 11 Local resources                 sb 2025-03-10
                  goods Procurement of office 2stationery, tonners, books, files and other acceEssaocrhies     1,000,000.00 12 Local resources                 sb 2025-01-21
                  goods                      Procurement of Office3 equipment and accessories and supplies       722,100.00 13 Local resources                 sb 2025-01-22
                  goods                                       Procurement of fuels f4or council operations       913,400.00 14 Local resources                 db 2025-01-14
                  goods                    Procurement of fuels f5or council operations under the 2025 CDF     3,278,013.69        15 2025 CDF                 db 2025-03-10
                  goods                 Procurement of an ele6ctricity generator under supply and delivery       500,000.00 16 Local resources                 sb 2025-03-31
                  goods                                 Procurement of 2 gene7rator with 500W and a medium        67,600.00 17 Local resources                 sb 2025-02-24
    consulting services                                          Repair and maintenan8ce of infrastructure       134,900.00 18 Local resources                 sb 2025-04-01
non consulting services                                                  Procurement of accou9nting system        37,000.00 19 Local resources                 sb 2025-01-31
                  goods                     Procurement of hand t1o0ols and personal protective equipments     1,000,000.00 20 Local resources                 sb 2025-03-17

LET'S FIRST INSPECT ALL DESCRIPTION

In [11]:
for i, item in enumerate(df_2025["Procurement item"], start=1):
    print(f"{i:02d}. {item}")

01. Procurement of compu1ter peripherals, equipments and accessories
02. Procurement of office 2stationery, tonners, books, files and other acceEssaocrhies
03. Procurement of Office3 equipment and accessories and supplies
04. Procurement of fuels f4or council operations
05. Procurement of fuels f5or council operations under the 2025 CDF
06. Procurement of an ele6ctricity generator under supply and delivery
07. Procurement of 2 gene7rator with 500W and a medium
08. Repair and maintenan8ce of infrastructure
09. Procurement of accou9nting system
10. Procurement of hand t1o0ols and personal protective equipments
11. Procurement of tools a1n1d general machinery under Cash for work
12. Procurement of T Shir1ts2 and Banners ( events)
13. Procurement of sports1 a3ttires and recreation
14. Procurement of adver1ts4, sound systems and communication servicesE
15. Procurement of Brand1in5g naming services and communication
16. Procurement of Zesco1 u6nits (electricity)
17. Procurement of fire se1rv7ices (attires, tools and associate accessoriesE)ach
18. Procurement of WDC 1p8rojects in Njame (Community and Social SerivEeasc)h
19. Procurement of Comm1u9nity Projects under the 2025 CDF
20. Procurement of Cleani2n0g materials for the institution (equipment and
21. Servicing of the procur2e1ment unit photocopy machine (maintenance)Each
22. Procurement of genera2l2 purpose lubricants
23. Construction of an Abl2u3tion Block at the Double Storey Building opposEitaec
24. Construction of an Aba2t4toir
25. Vehicles maintenance2 a5nd servicing /plant maintenance
26. Paving of the township2 6roads (1,6km)
27. Construction of the com27pletion of Chibende Rural Health Centre undeEr
28. Construction of the Co2m8munity Hall
29. Boreholes,pumps and 2w9ater reticulation
30. Construction of a Sola3r 0powered Borehole
31. Construction of (1) Abl3u1tion Block at Mission Hospital
32. Rehabilitation of towns3h2ip roads
33. Construction of a VIP L3a3trine Toilet at M15 Checkpoint
34. Construction of Kaban3a4na Truckpark
35. Installation and mainte3n5ance of streetlights
36. Repair of heavy duty e3q6uipment
37. Intergrity committee S3ta7tionery, attires and accessories
38. Conference hiring for 3C8ouncil meeting and refreshments for differentE
39. Procurement of WDC 3p9rojects in Chirundu West (Community and SocEiaacl
40. Procurement of WDC 4p0rojects in Chirundu Central (Community and SEoacciahl
41. Procurement of WDC 4p1rojects in Chirundu Kanyanga (Community anEd
42. Procurement of WDC 4p2rojects in Chirundu Lusitu (Community and SoEcaiaclh
43. Procurement of WDC 4p3rojects in Chirundu Ibbwemunyama (CommunEitay
44. Procurement of WDC 4p4rojects in Chirundu Sikoongo (Community andE
45. Procurement of WDC 4p5rojects in Chirundu Musaya (Community and
46. Procurement of WDC 4p6rojects in Chirundu Kapululira (Community andE
47. Procurement of WDC 4p7rojects in Chirundu Mushungu (Community anEda
48. Procurement of WDC 4p8rojects in Chirundu Nkandabwe (Community aEnadc
49. Procurement of WDC 4p9rojects in Chirundu Ngombe ilede (CommunityE
50. Procurement of hand t5o0ols and personal protective equipments AdditiEoancahl

50 rows without truncation

In [12]:
for start in range(0, 50, 10):
    print(f"\n{'='*80}")
    print(f"ROWS {start + 1} - {min(start + 10, 50)}")
    print(f"{'='*80}")

    for i in range(start, min(start + 10, 50)):
        print(f"{i + 1:02d}. {df_2025['Procurement item'].iloc[i]}")

================================================================================
ROWS 1 - 10
================================================================================
01. Procurement of compu1ter peripherals, equipments and accessories
02. Procurement of office 2stationery, tonners, books, files and other acceEssaocrhies
03. Procurement of Office3 equipment and accessories and supplies
04. Procurement of fuels f4or council operations
05. Procurement of fuels f5or council operations under the 2025 CDF
06. Procurement of an ele6ctricity generator under supply and delivery
07. Procurement of 2 gene7rator with 500W and a medium
08. Repair and maintenan8ce of infrastructure
09. Procurement of accou9nting system
10. Procurement of hand t1o0ols and personal protective equipments

================================================================================
ROWS 11 - 20
================================================================================
11. Procurement of tools a1n1d general machinery under Cash for work
12. Procurement of T Shir1ts2 and Banners ( events)
13. Procurement of sports1 a3ttires and recreation
14. Procurement of adver1ts4, sound systems and communication servicesE
15. Procurement of Brand1in5g naming services and communication
16. Procurement of Zesco1 u6nits (electricity)
17. Procurement of fire se1rv7ices (attires, tools and associate accessoriesE)ach
18. Procurement of WDC 1p8rojects in Njame (Community and Social SerivEeasc)h
19. Procurement of Comm1u9nity Projects under the 2025 CDF
20. Procurement of Cleani2n0g materials for the institution (equipment and

================================================================================
ROWS 21 - 30
================================================================================
21. Servicing of the procur2e1ment unit photocopy machine (maintenance)Each
22. Procurement of genera2l2 purpose lubricants
23. Construction of an Abl2u3tion Block at the Double Storey Building opposEitaec
24. Construction of an Aba2t4toir
25. Vehicles maintenance2 a5nd servicing /plant maintenance
26. Paving of the township2 6roads (1,6km)
27. Construction of the com27pletion of Chibende Rural Health Centre undeEr
28. Construction of the Co2m8munity Hall
29. Boreholes,pumps and 2w9ater reticulation
30. Construction of a Sola3r 0powered Borehole

================================================================================
ROWS 31 - 40
================================================================================
31. Construction of (1) Abl3u1tion Block at Mission Hospital
32. Rehabilitation of towns3h2ip roads
33. Construction of a VIP L3a3trine Toilet at M15 Checkpoint
34. Construction of Kaban3a4na Truckpark
35. Installation and mainte3n5ance of streetlights
36. Repair of heavy duty e3q6uipment
37. Intergrity committee S3ta7tionery, attires and accessories
38. Conference hiring for 3C8ouncil meeting and refreshments for differentE
39. Procurement of WDC 3p9rojects in Chirundu West (Community and SocEiaacl
40. Procurement of WDC 4p0rojects in Chirundu Central (Community and SEoacciahl

================================================================================
ROWS 41 - 50
================================================================================
41. Procurement of WDC 4p1rojects in Chirundu Kanyanga (Community anEd
42. Procurement of WDC 4p2rojects in Chirundu Lusitu (Community and SoEcaiaclh
43. Procurement of WDC 4p3rojects in Chirundu Ibbwemunyama (CommunEitay
44. Procurement of WDC 4p4rojects in Chirundu Sikoongo (Community andE
45. Procurement of WDC 4p5rojects in Chirundu Musaya (Community and
46. Procurement of WDC 4p6rojects in Chirundu Kapululira (Community andE
47. Procurement of WDC 4p7rojects in Chirundu Mushungu (Community anEda
48. Procurement of WDC 4p8rojects in Chirundu Nkandabwe (Community aEnadc
49. Procurement of WDC 4p9rojects in Chirundu Ngombe ilede (CommunityE
50. Procurement of hand t5o0ols and personal protective equipments AdditiEoancahl

Number cleaning map

In [13]:
df_2025_clean = df_2025.copy()

ref_fixes = {
    1: ("compu1ter", "computer"),
    2: ("2stationery", "stationery"),
    3: ("Office3", "Office"),
    4: ("f4or", "for"),
    5: ("f5or", "for"),
    6: ("ele6ctricity", "electricity"),
    7: ("gene7rator", "generator"),
    8: ("maintenan8ce", "maintenance"),
    9: ("accou9nting", "accounting"),
    10: ("t1o0ols", "tools"),
    11: ("a1n1d", "and"),
    12: ("Shir1ts2", "Shirts"),
    13: ("sports1 a3ttires", "sports attires"),
    14: ("adver1ts4", "adverts"),
    15: ("Brand1in5g", "Branding"),
    16: ("Zesco1 u6nits", "Zesco units"),
    17: ("se1rv7ices", "services"),
}

for ref_no, (bad, good) in ref_fixes.items():
    df_2025_clean.loc[
        df_2025_clean.index == ref_no - 1,
        "Procurement item"
    ] = df_2025_clean.loc[
        df_2025_clean.index == ref_no - 1,
        "Procurement item"
    ].str.replace(bad, good, regex=False)

for i in range(17):
    print(f"{i+1:02d}. {df_2025_clean['Procurement item'].iloc[i]}")

01. Procurement of computer peripherals, equipments and accessories
02. Procurement of office stationery, tonners, books, files and other acceEssaocrhies
03. Procurement of Office equipment and accessories and supplies
04. Procurement of fuels for council operations
05. Procurement of fuels for council operations under the 2025 CDF
06. Procurement of an electricity generator under supply and delivery
07. Procurement of 2 generator with 500W and a medium
08. Repair and maintenance of infrastructure
09. Procurement of accounting system
10. Procurement of hand tools and personal protective equipments
11. Procurement of tools and general machinery under Cash for work
12. Procurement of T Shirts and Banners ( events)
13. Procurement of sports attires and recreation
14. Procurement of adverts, sound systems and communication servicesE
15. Procurement of Branding naming services and communication
16. Procurement of Zesco units (electricity)
17. Procurement of fire services (attires, tools and associate accessoriesE)ach

In [14]:
description_fixes = {
    2: {
        "acceEssaocrhies": "accessories"
    },
    14: {
        "servicesE": "services"
    },
    17: {
        "accessoriesE)ach": "accessories"
    }
}

for ref_no, fixes in description_fixes.items():
    for bad, good in fixes.items():
        df_2025_clean.loc[
            df_2025_clean.index == ref_no - 1,
            "Procurement item"
        ] = df_2025_clean.loc[
            df_2025_clean.index == ref_no - 1,
            "Procurement item"
        ].str.replace(bad, good, regex=False)

for i in range(17):
    print(f"{i+1:02d}. {df_2025_clean['Procurement item'].iloc[i]}")

01. Procurement of computer peripherals, equipments and accessories
02. Procurement of office stationery, tonners, books, files and other accessories
03. Procurement of Office equipment and accessories and supplies
04. Procurement of fuels for council operations
05. Procurement of fuels for council operations under the 2025 CDF
06. Procurement of an electricity generator under supply and delivery
07. Procurement of 2 generator with 500W and a medium
08. Repair and maintenance of infrastructure
09. Procurement of accounting system
10. Procurement of hand tools and personal protective equipments
11. Procurement of tools and general machinery under Cash for work
12. Procurement of T Shirts and Banners ( events)
13. Procurement of sports attires and recreation
14. Procurement of adverts, sound systems and communication services
15. Procurement of Branding naming services and communication
16. Procurement of Zesco units (electricity)
17. Procurement of fire services (attires, tools and associate accessories

In [15]:
for i in range(17, 30):
    print(f"{i+1:02d}. {df_2025['Procurement item'].iloc[i]}")

18. Procurement of WDC 1p8rojects in Njame (Community and Social SerivEeasc)h
19. Procurement of Comm1u9nity Projects under the 2025 CDF
20. Procurement of Cleani2n0g materials for the institution (equipment and
21. Servicing of the procur2e1ment unit photocopy machine (maintenance)Each
22. Procurement of genera2l2 purpose lubricants
23. Construction of an Abl2u3tion Block at the Double Storey Building opposEitaec
24. Construction of an Aba2t4toir
25. Vehicles maintenance2 a5nd servicing /plant maintenance
26. Paving of the township2 6roads (1,6km)
27. Construction of the com27pletion of Chibende Rural Health Centre undeEr
28. Construction of the Co2m8munity Hall
29. Boreholes,pumps and 2w9ater reticulation
30. Construction of a Sola3r 0powered Borehole

More cleaning on the parts that are corrupt

In [16]:
description_fixes = {
    18: {
        "WDC 1p8rojects": "WDC projects",
        "SerivEeasc)h": "Services)"
    },
    19: {
        "Comm1u9nity": "Community"
    },
    20: {
        "Cleani2n0g": "Cleaning"
    },
    21: {
        "procur2e1ment": "procurement",
        "Each": ""
    },
    22: {
        "genera2l2": "general"
    },
    23: {
        "Abl2u3tion": "Ablution",
        "opposEitaec": "opposite"
    },
    24: {
        "Aba2t4toir": "Abattoir"
    },
    25: {
        "maintenance2 a5nd": "maintenance and"
    },
    26: {
        "township2 6roads": "township roads"
    },
    27: {
        "com27pletion": "completion",
        "undeEr": "under"
    },
    28: {
        "Co2m8munity": "Community"
    },
    29: {
        "2w9ater": "water"
    },
    30: {
        "Sola3r 0powered": "Solar powered"
    }
}

for ref_no, fixes in description_fixes.items():
    for bad, good in fixes.items():
        df_2025_clean.loc[
            df_2025_clean.index == ref_no - 1,
            "Procurement item"
        ] = df_2025_clean.loc[
            df_2025_clean.index == ref_no - 1,
            "Procurement item"
        ].str.replace(bad, good, regex=False)

for i in range(17, 30):
    print(f"{i+1:02d}. {df_2025_clean['Procurement item'].iloc[i]}")

18. Procurement of WDC projects in Njame (Community and Social Services)
19. Procurement of Community Projects under the 2025 CDF
20. Procurement of Cleaning materials for the institution (equipment and
21. Servicing of the procurement unit photocopy machine (maintenance)
22. Procurement of general purpose lubricants
23. Construction of an Ablution Block at the Double Storey Building opposite
24. Construction of an Abattoir
25. Vehicles maintenance and servicing /plant maintenance
26. Paving of the township roads (1,6km)
27. Construction of the completion of Chibende Rural Health Centre under
28. Construction of the Community Hall
29. Boreholes,pumps and water reticulation
30. Construction of a Solar powered Borehole

now cleaning rows 31-40

In [17]:
for i in range(30, 40):
    print(f"{i+1:02d}. {df_2025['Procurement item'].iloc[i]}")

31. Construction of (1) Abl3u1tion Block at Mission Hospital
32. Rehabilitation of towns3h2ip roads
33. Construction of a VIP L3a3trine Toilet at M15 Checkpoint
34. Construction of Kaban3a4na Truckpark
35. Installation and mainte3n5ance of streetlights
36. Repair of heavy duty e3q6uipment
37. Intergrity committee S3ta7tionery, attires and accessories
38. Conference hiring for 3C8ouncil meeting and refreshments for differentE
39. Procurement of WDC 3p9rojects in Chirundu West (Community and SocEiaacl
40. Procurement of WDC 4p0rojects in Chirundu Central (Community and SEoacciahl

In [18]:
description_fixes = {
    31: {
        "Abl3u1tion": "Ablution"
    },
    32: {
        "towns3h2ip": "township"
    },
    33: {
        "L3a3trine": "Latrine"
    },
    34: {
        "Kaban3a4na": "Kabana"
    },
    35: {
        "mainte3n5ance": "maintenance"
    },
    36: {
        "e3q6uipment": "equipment"
    },
    37: {
        "S3ta7tionery": "Stationery"
    },
    38: {
        "3C8ouncil": "Council",
        "differentE": "different"
    },
    39: {
        "WDC 3p9rojects": "WDC projects",
        "SocEiaacl": "Social"
    },
    40: {
        "WDC 4p0rojects": "WDC projects",
        "SEoacciahl": "Social"
    }
}

for ref_no, fixes in description_fixes.items():
    for bad, good in fixes.items():
        df_2025_clean.loc[
            df_2025_clean.index == ref_no - 1,
            "Procurement item"
        ] = df_2025_clean.loc[
            df_2025_clean.index == ref_no - 1,
            "Procurement item"
        ].str.replace(bad, good, regex=False)

for i in range(30, 40):
    print(f"{i+1:02d}. {df_2025_clean['Procurement item'].iloc[i]}")

31. Construction of (1) Ablution Block at Mission Hospital
32. Rehabilitation of township roads
33. Construction of a VIP Latrine Toilet at M15 Checkpoint
34. Construction of Kabana Truckpark
35. Installation and maintenance of streetlights
36. Repair of heavy duty equipment
37. Intergrity committee Stationery, attires and accessories
38. Conference hiring for Council meeting and refreshments for different
39. Procurement of WDC projects in Chirundu West (Community and Social
40. Procurement of WDC projects in Chirundu Central (Community and Social

cleaning 41-50

In [19]:
for i in range(40, 50):
    print(f"{i+1:02d}. {df_2025['Procurement item'].iloc[i]}")

41. Procurement of WDC 4p1rojects in Chirundu Kanyanga (Community anEd
42. Procurement of WDC 4p2rojects in Chirundu Lusitu (Community and SoEcaiaclh
43. Procurement of WDC 4p3rojects in Chirundu Ibbwemunyama (CommunEitay
44. Procurement of WDC 4p4rojects in Chirundu Sikoongo (Community andE
45. Procurement of WDC 4p5rojects in Chirundu Musaya (Community and
46. Procurement of WDC 4p6rojects in Chirundu Kapululira (Community andE
47. Procurement of WDC 4p7rojects in Chirundu Mushungu (Community anEda
48. Procurement of WDC 4p8rojects in Chirundu Nkandabwe (Community aEnadc
49. Procurement of WDC 4p9rojects in Chirundu Ngombe ilede (CommunityE
50. Procurement of hand t5o0ols and personal protective equipments AdditiEoancahl

In [20]:
description_fixes = {
    41: {
        "WDC 4p1rojects": "WDC projects",
        "anEd": "and"
    },
    42: {
        "WDC 4p2rojects": "WDC projects",
        "SoEcaiaclh": "Social"
    },
    43: {
        "WDC 4p3rojects": "WDC projects",
        "CommunEitay": "Community"
    },
    44: {
        "WDC 4p4rojects": "WDC projects",
        "andE": "and"
    },
    45: {
        "WDC 4p5rojects": "WDC projects"
    },
    46: {
        "WDC 4p6rojects": "WDC projects",
        "andE": "and"
    },
    47: {
        "WDC 4p7rojects": "WDC projects",
        "anEda": "and"
    },
    48: {
        "WDC 4p8rojects": "WDC projects",
        "aEnadc": "and"
    },
    49: {
        "WDC 4p9rojects": "WDC projects",
        "CommunityE": "Community"
    },
    50: {
        "t5o0ols": "tools",
        "AdditiEoancahl": "Additional"
    }
}

for ref_no, fixes in description_fixes.items():
    for bad, good in fixes.items():
        df_2025_clean.loc[
            df_2025_clean.index == ref_no - 1,
            "Procurement item"
        ] = df_2025_clean.loc[
            df_2025_clean.index == ref_no - 1,
            "Procurement item"
        ].str.replace(bad, good, regex=False)

for i in range(40, 50):
    print(f"{i+1:02d}. {df_2025_clean['Procurement item'].iloc[i]}")

41. Procurement of WDC projects in Chirundu Kanyanga (Community and
42. Procurement of WDC projects in Chirundu Lusitu (Community and Social
43. Procurement of WDC projects in Chirundu Ibbwemunyama (Community
44. Procurement of WDC projects in Chirundu Sikoongo (Community and
45. Procurement of WDC projects in Chirundu Musaya (Community and
46. Procurement of WDC projects in Chirundu Kapululira (Community and
47. Procurement of WDC projects in Chirundu Mushungu (Community and
48. Procurement of WDC projects in Chirundu Nkandabwe (Community and
49. Procurement of WDC projects in Chirundu Ngombe ilede (Community
50. Procurement of hand tools and personal protective equipments Additional

SOURCE OF FUNDS

In [21]:
df_2025_clean["Source of Funds"].value_counts(dropna=False)

Source of Funds
11 Local resources                1
12 Local resources                1
13 Local resources                1
14 Local resources                1
15 2025 CDF                       1
16 Local resources                1
17 Local resources                1
18 Local resources                1
19 Local resources                1
20 Local resources                1
21 Grant                          1
22 Local resources                1
23 Local resources                1
24 Local resources                1
25 2025 CDF                       1
26 Local resources                1
27 Local resources                1
28 Local resources                1
29 2025 CDF                       1
30 Local resources                1
31 Local resources                1
32 Local resources                1
33 Local resources                1
34 Local resources                1
35 Local resources                1
36 Grant and locally generated    1
37 2023 CDF project               1
38 Local resources                1
39 Local resources                1
40 Local resources                1
41 Local resources                1
42 Local resources                1
43 Local resources                1
44 Local resources                1
45 Local resources                1
46 Local resources                1
47 Local resources                1
48 Local resources                1
49 Local resources                1
50 Local resources                1
51 Local resources                1
52 Local resources                1
53 Local resources                1
54 Local resources                1
55 Local resources                1
56 Local resources                1
57 Local resources                1
58 Local resources                1
59 Local resources                1
60 Local resources                1
Name: count, dtype: int64

STANDARDIZE SOURCE OF FUNDS

In [22]:
df_2025_clean["Source of Funds"] = (
    df_2025_clean["Source of Funds"]
    .str.strip()
    .replace({
        "Local resources": "Local Resource"
    })
)

df_2025_clean["Source of Funds"].value_counts(dropna=False)

Source of Funds
11 Local resources                1
12 Local resources                1
13 Local resources                1
14 Local resources                1
15 2025 CDF                       1
16 Local resources                1
17 Local resources                1
18 Local resources                1
19 Local resources                1
20 Local resources                1
21 Grant                          1
22 Local resources                1
23 Local resources                1
24 Local resources                1
25 2025 CDF                       1
26 Local resources                1
27 Local resources                1
28 Local resources                1
29 2025 CDF                       1
30 Local resources                1
31 Local resources                1
32 Local resources                1
33 Local resources                1
34 Local resources                1
35 Local resources                1
36 Grant and locally generated    1
37 2023 CDF project               1
38 Local resources                1
39 Local resources                1
40 Local resources                1
41 Local resources                1
42 Local resources                1
43 Local resources                1
44 Local resources                1
45 Local resources                1
46 Local resources                1
47 Local resources                1
48 Local resources                1
49 Local resources                1
50 Local resources                1
51 Local resources                1
52 Local resources                1
53 Local resources                1
54 Local resources                1
55 Local resources                1
56 Local resources                1
57 Local resources                1
58 Local resources                1
59 Local resources                1
60 Local resources                1
Name: count, dtype: int64

CHECK PROCUREMENT METHOD

In [23]:
df_2025_clean["Procurement Method"].value_counts(dropna=False)

Procurement Method
sb     44
db      3
obn     3
Name: count, dtype: int64

CLEANING OF PROCUREMENT RECORDS

In [24]:
df_2025_clean["Procurement Method"] = (
    df_2025_clean["Procurement Method"]
    .str.strip()
    .str.lower()
)

df_2025_clean["Procurement Method"].value_counts(dropna=False)

Procurement Method
sb     44
db      3
obn     3
Name: count, dtype: int64

CONVERTING TO ACTUAL NUMERIC VALUES

In [25]:
df_2025_clean["Estimated Amount"] = (
    df_2025_clean["Estimated Amount"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df_2025_clean["Estimated Amount"] = pd.to_numeric(
    df_2025_clean["Estimated Amount"],
    errors="coerce"
)

df_2025_clean["Estimated Amount"].head(10)

0     784850.00
1    1000000.00
2     722100.00
3     913400.00
4    3278013.69
5     500000.00
6      67600.00
7     134900.00
8      37000.00
9    1000000.00
Name: Estimated Amount, dtype: float64

CHECKING THE FAILED AMOUNT

In [26]:
print("Total records:", len(df_2025_clean))
print("Missing amounts:", df_2025_clean["Estimated Amount"].isna().sum())

Total records: 50
Missing amounts: 1

IDENTIFYING THE MISSING AMOUNT ON THE PROCUREMENT ITEM

In [27]:
missing_amount = df_2025_clean[
    df_2025_clean["Estimated Amount"].isna()
]

missing_amount[
    [
        "Category",
        "Procurement item",
        "Source of Funds",
        "Procurement Method",
        "date"
    ]
]

,Category,Procurement item,Source of Funds,Procurement Method,date
18,works,Procurement of Community Projects under the 20...,29 2025 CDF,obn,2025-06-02

INSPECTION OF THE EXTRACTION OF THE PARTICULAR FIELD

In [28]:
df_page1.iloc[28]

Category                                               works
Procurement item    Boreholes,pumps and 2w9ater reticulation
Estimated Amount                                  290,100.00
Name: 28, dtype: str

NOW THAT WE HAVE FOUND THE MISSING AMOUNT ADD IT TOTHE MISSING ENTRY

In [29]:
df_2025_clean.loc[28, "Estimated Amount"] = 290100.00

VARIFYING IF WE HAVE ENTERED IT

In [30]:
print("Missing amounts:", df_2025_clean["Estimated Amount"].isna().sum())

Missing amounts: 1

In [31]:
df_2025_clean.iloc[28]

Category                                               works
Procurement item      Boreholes,pumps and water reticulation
Estimated Amount                                    290100.0
Source of Funds                           39 Local resources
Procurement Method                                        sb
date                                     2025-06-30 00:00:00
Name: 28, dtype: object

In [32]:
df_2025_clean.iloc[28, df_2025_clean.columns.get_loc("Estimated Amount")] = 290100.00

In [33]:
print("Missing amounts:", df_2025_clean["Estimated Amount"].isna().sum())

Missing amounts: 1

IDENTIFYING WHERE THE MISSING VALUE IS

In [34]:
df_2025_clean[df_2025_clean["Estimated Amount"].isna()]

,Category,Procurement item,Estimated Amount,Source of Funds,Procurement Method,date
18,works,Procurement of Community Projects under the 20...,NaN,29 2025 CDF,obn,2025-06-02

INSPECT THE SURROUNDING PAGE

In [35]:
df_page1.iloc[25:32]

,Category,Procurement item,Estimated Amount
25,works,"Paving of the township2 6roads (1,6km)","5,240,000.00"
26,works,Construction of the com27pletion of Chibende R...,"538,726.57"
27,works,Construction of the Co2m8munity Hall,"2,000,000.00"
28,works,"Boreholes,pumps and 2w9ater reticulation","290,100.00"
29,works,Construction of a Sola3r 0powered Borehole,"800,000.00"
30,works,Construction of (1) Abl3u1tion Block at Missio...,"300,000.00"
31,works,Rehabilitation of towns3h2ip roads,"200,000.00"

In [36]:
df_page2.iloc[25:32]

                   Source of Funds Procurement Method       date
25  36 Grant and locally generated                obn 2025-06-30
26             37 2023 CDF project                 sb 2025-02-24
27              38 Local resources                obn 2025-07-14
28              39 Local resources                 sb 2025-06-30
29              40 Local resources                 sb 2025-08-14
30              41 Local resources                 sb 2025-09-01
31              42 Local resources                 sb 2025-09-08

In [37]:
df_page2["Source of Funds"].head(50).to_string()

'0                 11 Local resources\n1                 12 Local resources\n2                 13 Local resources\n3                 14 Local resources\n4                        15 2025 CDF\n5                 16 Local resources\n6                 17 Local resources\n7                 18 Local resources\n8                 19 Local resources\n9                 20 Local resources\n10                          21 Grant\n11                22 Local resources\n12                23 Local resources\n13                24 Local resources\n14                       25 2025 CDF\n15                26 Local resources\n16                27 Local resources\n17                28 Local resources\n18                       29 2025 CDF\n19                30 Local resources\n20                31 Local resources\n21                32 Local resources\n22                33 Local resources\n23                34 Local resources\n24                35 Local resources\n25    36 Grant and locally generated\n26               37 2023 CDF project\n27                38 Local resources\n28                39 Local resources\n29                40 Local resources\n30                41 Local resources\n31                42 Local resources\n32                43 Local resources\n33                44 Local resources\n34                45 Local resources\n35                46 Local resources\n36                47 Local resources\n37                48 Local resources\n38                49 Local resources\n39                50 Local resources\n40                51 Local resources\n41                52 Local resources\n42                53 Local resources\n43                54 Local resources\n44                55 Local resources\n45                56 Local resources\n46                57 Local resources\n47                58 Local resources\n48                59 Local resources\n49                60 Local resources'

In [38]:
df_page1 = df_page1.copy()

df_page1["Ref No"] = range(11, 61)

EXTRACTION THE REF NO.FROM PAGE 2

In [39]:
df_page2 = df_page2.copy()

df_page2["Ref No"] = (
    df_page2["Source of Funds"]
    .str.extract(r"^\s*(\d+)")
    .astype(int)
)

REMOVE THE REFERENCE NUMBER FROM SOURCE OF FUNDS

In [40]:
df_page2["Source of Funds"] = (
    df_page2["Source of Funds"]
    .str.replace(r"^\s*\d+\s*", "", regex=True)
    .str.strip()
)

CHECK

In [41]:
df_page2[["Ref No", "Source of Funds"]].head(20)

    Ref No  Source of Funds
0       11  Local resources
1       12  Local resources
2       13  Local resources
3       14  Local resources
4       15         2025 CDF
5       16  Local resources
6       17  Local resources
7       18  Local resources
8       19  Local resources
9       20  Local resources
10      21            Grant
11      22  Local resources
12      23  Local resources
13      24  Local resources
14      25         2025 CDF
15      26  Local resources
16      27  Local resources
17      28  Local resources
18      29         2025 CDF
19      30  Local resources

CHECKING THAT BOTH PAGES HAVE THE SAME REF NO

In [42]:
print("Page 1:", df_page1["Ref No"].min(), "to", df_page1["Ref No"].max())
print("Page 2:", df_page2["Ref No"].min(), "to", df_page2["Ref No"].max())

print("Page 1 records:", len(df_page1))
print("Page 2 records:", len(df_page2))

Page 1: 11 to 60
Page 2: 11 to 60
Page 1 records: 50
Page 2 records: 50

MARGING PAGE 1 AND PAGE 2 USING REF NO

In [43]:
df_2025_fixed = pd.merge(
    df_page1,
    df_page2[["Ref No", "Source of Funds", "Procurement Method", "date"]],
    on="Ref No",
    how="inner"
)

CHECKING

In [44]:
print("Records:", len(df_2025_fixed))
print(df_2025_fixed.head())

Records: 50
  Category                                   Procurement item  \
0    goods  Procurement of compu1ter peripherals, equipmen...
1    goods  Procurement of office 2stationery, tonners, bo...
2    goods  Procurement of Office3 equipment and accessori...
3    goods       Procurement of fuels f4or council operations
4    goods  Procurement of fuels f5or council operations u...

  Estimated Amount  Ref No  Source of Funds Procurement Method       date
0       784,850.00      11  Local resources                 sb 2025-03-10
1     1,000,000.00      12  Local resources                 sb 2025-01-21
2       722,100.00      13  Local resources                 sb 2025-01-22
3       913,400.00      14  Local resources                 db 2025-01-14
4     3,278,013.69      15         2025 CDF                 db 2025-03-10

SELECTION OF THE NEEDED DATA

In [45]:
df_2025_clean = df_2025_fixed[
    [
        "Category",
        "Procurement item",
        "Estimated Amount",
        "Source of Funds",
        "Procurement Method",
        "date"
    ]
].copy()

CLEAN SOURCE OF FUNDS

In [46]:
df_2025_clean["Source of Funds"] = (
    df_2025_clean["Source of Funds"]
    .str.strip()
    .replace({
        "Local resources": "Local Resource"
    })
)

SET AMOUNT TO NUMERIC

In [47]:
df_2025_clean["Estimated Amount"] = (
    df_2025_clean["Estimated Amount"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df_2025_clean["Estimated Amount"] = pd.to_numeric(
    df_2025_clean["Estimated Amount"],
    errors="coerce"
)

In [48]:
df_2025_fixed[df_2025_fixed["Ref No"] == 29]

,Category,Procurement item,Estimated Amount,Ref No,Source of Funds,Procurement Method,date
18,works,Procurement of Comm1u9nity Projects under the ...,,29,2025 CDF,obn,2025-06-02

In [49]:
df_page1["Ref No"] = range(11, 61)

In [50]:
df_page1.iloc[28]

Category                                               works
Procurement item    Boreholes,pumps and 2w9ater reticulation
Estimated Amount                                  290,100.00
Ref No                                                    39
Name: 28, dtype: object

In [51]:
df_page1[
    (df_page1["Ref No"] >= 25) &
    (df_page1["Ref No"] <= 31)
][["Ref No", "Category", "Procurement item", "Estimated Amount"]]

,Ref No,Category,Procurement item,Estimated Amount
14,25,non consulting services,Procurement of Brand1in5g naming services and ...,"245,851.03"
15,26,non consulting services,Procurement of Zesco1 u6nits (electricity),"158,400.00"
16,27,consulting services,"Procurement of fire se1rv7ices (attires, tools...","234,700.00"
17,28,works,Procurement of WDC 1p8rojects in Njame (Commun...,"135,875.68"
18,29,works,Procurement of Comm1u9nity Projects under the ...,
19,30,goods,Procurement of Cleani2n0g materials for the in...,"51,540.00"
20,31,consulting services,Servicing of the procur2e1ment unit photocopy ...,"30,000.00"

In [52]:
# Find the original PDF row corresponding to Ref No. 29
row_29 = df_page1[df_page1["Ref No"] == 29]

print(row_29.to_string(index=False))

Category                                       Procurement item Estimated Amount  Ref No
   works Procurement of Comm1u9nity Projects under the 2025 CDF                       29

In [53]:
with pdfplumber.open(pdf_path) as pdf:
    page1 = pdf.pages[0]
    words1 = page1.extract_words()

# Show words around the row corresponding to Ref No. 29
for word in words1:
    if 0 <= word["top"] <= 600:
        print(word["text"], " | x0:", round(word["x0"], 1), "top:", round(word["top"], 1))

2025  | x0: 426.2 top: 38.6
ANNUAL  | x0: 442.9 top: 38.6
PROCUREMENT  | x0: 471.8 top: 38.6
PLAN  | x0: 526.1 top: 38.6
CHIRUNDU  | x0: 545.4 top: 38.6
A  | x0: 132.9 top: 44.2
B  | x0: 251.3 top: 44.2
C  | x0: 324.3 top: 44.2
D  | x0: 392.0 top: 44.2
E  | x0: 459.8 top: 44.2
F  | x0: 529.6 top: 44.2
G  | x0: 595.0 top: 44.2
H  | x0: 653.7 top: 44.2
I  | x0: 705.2 top: 44.2
J  | x0: 749.9 top: 44.2
K  | x0: 800.6 top: 44.2
L  | x0: 856.3 top: 44.2
M  | x0: 921.7 top: 44.2
1  | x0: 46.2 top: 52.7
Entity  | x0: 56.0 top: 52.9
Chirundu  | x0: 216.1 top: 52.9
Town  | x0: 245.2 top: 52.9
Council  | x0: 263.5 top: 52.9
2  | x0: 46.2 top: 61.0
Procurement  | x0: 56.0 top: 61.1
Plan  | x0: 99.3 top: 61.1
for  | x0: 115.3 top: 61.1
year  | x0: 126.2 top: 61.1
2025  | x0: 216.1 top: 60.8
3  | x0: 46.2 top: 69.3
Version  | x0: 56.0 top: 69.4
1  | x0: 216.1 top: 69.1
4  | x0: 46.2 top: 77.6
Procurement  | x0: 56.0 top: 77.7
Budget  | x0: 99.3 top: 77.7
42,455,237.45  | x0: 216.1 top: 77.4
5  | x0: 46.2 top: 85.9
ZMW  | x0: 56.0 top: 86.0
Control  | x0: 74.0 top: 86.0
Total  | x0: 99.8 top: 86.0
42,455,237.45  | x0: 216.1 top: 85.6
6  | x0: 46.2 top: 94.2
Date  | x0: 56.0 top: 94.3
Last  | x0: 72.4 top: 94.3
Updated  | x0: 88.1 top: 94.3
1/7/2025  | x0: 216.1 top: 93.9
7  | x0: 46.2 top: 102.4
Comments  | x0: 56.0 top: 102.6
8  | x0: 46.2 top: 110.7
9  | x0: 46.2 top: 119.0
ZMW  | x0: 726.2 top: 118.8
Estimated  | x0: 740.9 top: 118.8
Budget  | x0: 768.9 top: 118.8
FX  | x0: 872.5 top: 118.8
Budget  | x0: 881.2 top: 118.8
Amount  | x0: 901.7 top: 118.8
10  | x0: 44.3 top: 127.3
Class  | x0: 125.8 top: 127.8
UNSPSC  | x0: 239.3 top: 127.8
IFMIS  | x0: 297.4 top: 127.8
GL  | x0: 317.3 top: 127.8
Account  | x0: 328.6 top: 127.8
Description  | x0: 375.5 top: 127.8
Ref  | x0: 450.8 top: 127.8
No  | x0: 463.5 top: 127.8
Project  | x0: 510.7 top: 127.8
Code  | x0: 535.2 top: 127.8
Unit  | x0: 572.1 top: 127.8
of  | x0: 587.1 top: 127.8
Measure  | x0: 595.3 top: 127.8
Quantity  | x0: 642.1 top: 127.8
GOZ  | x0: 698.4 top: 127.8
Other  | x0: 742.2 top: 127.8
Total  | x0: 794.4 top: 127.8
Currency  | x0: 843.1 top: 127.8
Amount  | x0: 911.5 top: 127.8
11  | x0: 44.3 top: 135.6
goods  | x0: 56.0 top: 135.6
43210000  | x0: 216.1 top: 135.6
0  | x0: 292.9 top: 135.6
Procurement  | x0: 362.6 top: 135.6
of  | x0: 402.9 top: 135.6
compu1ter  | x0: 410.5 top: 135.6
peripherals,  | x0: 440.4 top: 135.6
equipments  | x0: 477.3 top: 135.6
and  | x0: 514.0 top: 135.6
accessories  | x0: 527.0 top: 135.6
Each  | x0: 567.5 top: 135.6
784,850.00  | x0: 693.3 top: 135.6
784,850.00  | x0: 795.9 top: 135.6
12  | x0: 44.3 top: 143.8
goods  | x0: 56.0 top: 143.8
14111509  | x0: 216.1 top: 143.8
0  | x0: 292.9 top: 143.8
Procurement  | x0: 362.6 top: 143.8
of  | x0: 402.9 top: 143.8
office  | x0: 410.5 top: 143.8
2stationery,  | x0: 428.1 top: 143.8
tonners,  | x0: 461.5 top: 143.8
books,  | x0: 487.7 top: 143.8
files  | x0: 509.4 top: 143.8
and  | x0: 523.2 top: 143.8
other  | x0: 536.2 top: 143.8
acceEssaocrhies  | x0: 553.5 top: 143.8
1,000,000.00  | x0: 687.7 top: 143.8
1,000,000.00  | x0: 790.3 top: 143.8
13  | x0: 44.3 top: 152.1
goods  | x0: 56.0 top: 152.1
44000000  | x0: 216.1 top: 152.1
0  | x0: 292.9 top: 152.1
Procurement  | x0: 362.6 top: 152.1
of  | x0: 402.9 top: 152.1
Office3  | x0: 410.5 top: 152.1
equipment  | x0: 430.1 top: 152.1
and  | x0: 463.4 top: 152.1
accessories  | x0: 476.5 top: 152.1
and  | x0: 513.9 top: 152.1
supplies  | x0: 526.9 top: 152.1
Each  | x0: 567.5 top: 152.1
722,100.00  | x0: 693.3 top: 152.1
722,100.00  | x0: 795.9 top: 152.1
14  | x0: 44.3 top: 160.4
goods  | x0: 56.0 top: 160.4
15100000  | x0: 216.1 top: 160.4
0  | x0: 292.9 top: 160.4
Procurement  | x0: 362.6 top: 160.4
of  | x0: 402.9 top: 160.4
fuels  | x0: 410.5 top: 160.4
f4or  | x0: 426.4 top: 160.4
council  | x0: 436.2 top: 160.4
operations  | x0: 458.9 top: 160.4
Each  | x0: 567.5 top: 160.4
913,400.00  | x0: 693.3 top: 160.4
913,400.00  | x0: 795.9 top: 160.4
15  | x0: 44.3 top: 168.7
goods  | x0: 56.0 top: 168.7
15100000  | x0: 216.1 top: 168.7
0  | x0: 292.9 top: 168.7
Procurement  | x0: 362.6 top: 168.7
of  | x0: 402.9 top: 168.7
fuels  | x0: 410.5 top: 168.7
f5or  | x0: 426.4 top: 168.7
council  | x0: 436.2 top: 168.7
operations  | x0: 458.9 top: 168.7
under  | x0: 492.2 top: 168.7
the  | x0: 511.2 top: 168.7
2025  | x0: 522.5 top: 168.7
CDF  | x0: 539.3 top: 168.7
Each  | x0: 567.5 top: 168.7
3,278,013.69  | x0: 687.7 top: 168.7
3,278,013.69  | x0: 790.3 top: 168.7
16  | x0: 44.3 top: 177.0
goods  | x0: 56.0 top: 177.0
26111601  | x0: 216.1 top: 177.0
0  | x0: 292.9 top: 177.0
Procurement  | x0: 362.6 top: 177.0
of  | x0: 402.9 top: 177.0
an  | x0: 410.5 top: 177.0
ele6ctricity  | x0: 419.8 top: 177.0
generator  | x0: 449.6 top: 177.0
under  | x0: 480.3 top: 177.0
supply  | x0: 499.4 top: 177.0
and  | x0: 520.3 top: 177.0
delivery  | x0: 533.4 top: 177.0
Each  | x0: 567.5 top: 177.0
500,000.00  | x0: 693.3 top: 177.0
500,000.00  | x0: 795.9 top: 177.0
17  | x0: 44.3 top: 185.3
goods  | x0: 56.0 top: 185.3
26111601  | x0: 216.1 top: 185.3
0  | x0: 292.9 top: 185.3
Procurement  | x0: 362.6 top: 185.3
of  | x0: 402.9 top: 185.3
2  | x0: 410.5 top: 185.3
gene7rator  | x0: 416.1 top: 185.3
with  | x0: 446.8 top: 185.3
500W  | x0: 462.5 top: 185.3
and  | x0: 482.2 top: 185.3
a  | x0: 495.3 top: 185.3
medium  | x0: 500.9 top: 185.3
Each  | x0: 567.5 top: 185.3
67,600.00  | x0: 697.1 top: 185.3
67,600.00  | x0: 799.7 top: 185.3
18  | x0: 44.3 top: 193.6
consulting  | x0: 56.0 top: 193.6
services  | x0: 88.0 top: 193.6
72000000  | x0: 216.1 top: 193.6
0  | x0: 292.9 top: 193.6
Repair  | x0: 362.6 top: 193.6
and  | x0: 384.2 top: 193.6
maintenan8ce  | x0: 397.3 top: 193.6
of  | x0: 437.7 top: 193.6
infrastructure  | x0: 445.2 top: 193.6
Each  | x0: 567.5 top: 193.6
134,900.00  | x0: 693.3 top: 193.6
134,900.00  | x0: 795.9 top: 193.6
19  | x0: 44.3 top: 201.8
non  | x0: 56.0 top: 201.8
consulting  | x0: 69.1 top: 201.8
services  | x0: 101.1 top: 201.8
84111501  | x0: 216.1 top: 201.8
0  | x0: 292.9 top: 201.8
Procurement  | x0: 362.6 top: 201.8
of  | x0: 402.9 top: 201.8
accou9nting  | x0: 410.5 top: 201.8
system  | x0: 444.9 top: 201.8
Each  | x0: 567.5 top: 201.8
37,000.00  | x0: 697.1 top: 201.8
37,000.00  | x0: 799.7 top: 201.8
20  | x0: 44.3 top: 210.1
goods  | x0: 56.0 top: 210.1
27110000  | x0: 216.1 top: 210.1
0  | x0: 292.9 top: 210.1
Procurement  | x0: 362.6 top: 210.1
of  | x0: 402.9 top: 210.1
hand  | x0: 410.5 top: 210.1
t1o0ols  | x0: 427.3 top: 210.1
and  | x0: 443.2 top: 210.1
personal  | x0: 456.3 top: 210.1
protective  | x0: 483.7 top: 210.1
equipments  | x0: 514.9 top: 210.1
Each  | x0: 567.5 top: 210.1
1,000,000.00  | x0: 687.7 top: 210.1
1,000,000.00  | x0: 790.3 top: 210.1
21  | x0: 44.3 top: 218.4
goods  | x0: 56.0 top: 218.4
27000000  | x0: 216.1 top: 218.4
0  | x0: 292.9 top: 218.4
Procurement  | x0: 362.6 top: 218.4
of  | x0: 402.9 top: 218.4
tools  | x0: 410.5 top: 218.4
a1n1d  | x0: 426.4 top: 218.4
general  | x0: 439.5 top: 218.4
machinery  | x0: 463.6 top: 218.4
under  | x0: 496.4 top: 218.4
Cash  | x0: 515.4 top: 218.4
for  | x0: 532.9 top: 218.4
work  | x0: 542.7 top: 218.4
Each  | x0: 567.5 top: 218.4
600,000.00  | x0: 693.3 top: 218.4
600,000.00  | x0: 795.9 top: 218.4
22  | x0: 44.3 top: 226.7
goods  | x0: 56.0 top: 226.7
53103000  | x0: 216.1 top: 226.7
0  | x0: 292.9 top: 226.7
Procurement  | x0: 362.6 top: 226.7
of  | x0: 402.9 top: 226.7
T  | x0: 410.5 top: 226.7
Shir1ts2  | x0: 416.6 top: 226.7
and  | x0: 435.7 top: 226.7
Banners  | x0: 448.8 top: 226.7
(  | x0: 475.6 top: 226.7
events)  | x0: 479.8 top: 226.7
Each  | x0: 567.5 top: 226.7
230,450.00  | x0: 693.3 top: 226.7
230,450.00  | x0: 795.9 top: 226.7
23  | x0: 44.3 top: 235.0
goods  | x0: 56.0 top: 235.0
49000000  | x0: 216.1 top: 235.0
0  | x0: 292.9 top: 235.0
Procurement  | x0: 362.6 top: 235.0
of  | x0: 402.9 top: 235.0
sports1  | x0: 410.5 top: 235.0
a3ttires  | x0: 430.7 top: 235.0
and  | x0: 451.1 top: 235.0
recreation  | x0: 464.1 top: 235.0
Each  | x0: 567.5 top: 235.0
37,600.00  | x0: 697.1 top: 235.0
33,600.00  | x0: 799.7 top: 235.0
24  | x0: 44.3 top: 243.2
consulting  | x0: 56.0 top: 243.2
services  | x0: 88.0 top: 243.2
82100000  | x0: 216.1 top: 243.2
0  | x0: 292.9 top: 243.2
Procurement  | x0: 362.6 top: 243.2
of  | x0: 402.9 top: 243.2
adver1ts4,  | x0: 412.4 top: 243.2
sound  | x0: 438.4 top: 243.2
systems  | x0: 458.5 top: 243.2
and  | x0: 485.0 top: 243.2
communication  | x0: 498.1 top: 243.2
servicesE  | x0: 545.3 top: 243.2
daechvices  | x0: 572.0 top: 243.2
111,700.00  | x0: 693.3 top: 243.2
111,700.00  | x0: 795.9 top: 243.2
25  | x0: 44.3 top: 251.5
non  | x0: 56.0 top: 251.5
consulting  | x0: 69.1 top: 251.5
services  | x0: 101.1 top: 251.5
80141604  | x0: 216.1 top: 251.5
0  | x0: 292.9 top: 251.5
Procurement  | x0: 362.6 top: 251.5
of  | x0: 402.9 top: 251.5
Brand1in5g  | x0: 410.5 top: 251.5
naming  | x0: 439.2 top: 251.5
services  | x0: 463.2 top: 251.5
and  | x0: 489.9 top: 251.5
communication  | x0: 503.0 top: 251.5
Each  | x0: 567.5 top: 251.5
245,851.03  | x0: 693.3 top: 251.5
245,851.03  | x0: 795.9 top: 251.5
26  | x0: 44.3 top: 259.8
non  | x0: 56.0 top: 259.8
consulting  | x0: 69.1 top: 259.8
services  | x0: 101.1 top: 259.8
60104909  | x0: 216.1 top: 259.8
0  | x0: 292.9 top: 259.8
Procurement  | x0: 362.6 top: 259.8
of  | x0: 402.9 top: 259.8
Zesco1  | x0: 410.5 top: 259.8
u6nits  | x0: 430.6 top: 259.8
(electricity)  | x0: 446.8 top: 259.8
Each  | x0: 567.5 top: 259.8
158,400.00  | x0: 693.3 top: 259.8
158,400.00  | x0: 795.9 top: 259.8
27  | x0: 44.3 top: 268.1
consulting  | x0: 56.0 top: 268.1
services  | x0: 88.0 top: 268.1
92101600  | x0: 216.1 top: 268.1
0  | x0: 292.9 top: 268.1
Procurement  | x0: 362.6 top: 268.1
of  | x0: 402.9 top: 268.1
fire  | x0: 410.5 top: 268.1
se1rv7ices  | x0: 421.9 top: 268.1
(attires,  | x0: 448.5 top: 268.1
tools  | x0: 473.1 top: 268.1
and  | x0: 489.0 top: 268.1
associate  | x0: 502.1 top: 268.1
accessoriesE)ach  | x0: 532.4 top: 268.1
234,700.00  | x0: 693.3 top: 268.1
234,700.00  | x0: 795.9 top: 268.1
28  | x0: 44.3 top: 276.4
works  | x0: 56.0 top: 276.4
93140000  | x0: 216.1 top: 276.4
0  | x0: 292.9 top: 276.4
Procurement  | x0: 362.6 top: 276.4
of  | x0: 402.9 top: 276.4
WDC  | x0: 410.5 top: 276.4
1p8rojects  | x0: 428.1 top: 276.4
in  | x0: 454.2 top: 276.4
Njame  | x0: 461.4 top: 276.4
(Community  | x0: 482.7 top: 276.4
and  | x0: 520.8 top: 276.4
Social  | x0: 533.9 top: 276.4
SerivEeasc)h  | x0: 553.9 top: 276.4
135,875.68  | x0: 693.3 top: 276.4
135,875.68  | x0: 795.9 top: 276.4
29  | x0: 44.3 top: 284.7
works  | x0: 56.0 top: 284.7
93140000  | x0: 216.1 top: 284.7
0  | x0: 292.9 top: 284.7
Procurement  | x0: 362.6 top: 284.7
of  | x0: 402.9 top: 284.7
Comm1u9nity  | x0: 410.5 top: 284.7
Projects  | x0: 446.3 top: 284.7
under  | x0: 472.5 top: 284.7
the  | x0: 491.6 top: 284.7
2025  | x0: 502.8 top: 284.7
CDF  | x0: 519.6 top: 284.7
Each  | x0: 567.5 top: 284.7
###########  | x0: 685.7 top: 284.7
18,654,678.04  | x0: 786.6 top: 284.7
30  | x0: 44.3 top: 292.9
goods  | x0: 56.0 top: 292.9
47000000  | x0: 216.1 top: 292.9
0  | x0: 292.9 top: 292.9
Procurement  | x0: 362.6 top: 292.9
of  | x0: 402.9 top: 292.9
Cleani2n0g  | x0: 410.5 top: 292.9
materials  | x0: 438.6 top: 292.9
for  | x0: 467.7 top: 292.9
the  | x0: 477.6 top: 292.9
institution  | x0: 488.8 top: 292.9
(equipment  | x0: 519.3 top: 292.9
and  | x0: 554.9 top: 292.9
Esuapcphlies)  | x0: 567.5 top: 292.9
51,540.00  | x0: 697.1 top: 292.9
51,540.00  | x0: 799.7 top: 292.9
31  | x0: 44.3 top: 301.2
consulting  | x0: 56.0 top: 301.2
services  | x0: 88.0 top: 301.2
81112201  | x0: 216.1 top: 301.2
0  | x0: 292.9 top: 301.2
Servicing  | x0: 362.6 top: 301.2
of  | x0: 392.3 top: 301.2
the  | x0: 399.8 top: 301.2
procur2e1ment  | x0: 411.1 top: 301.2
unit  | x0: 450.7 top: 301.2
photocopy  | x0: 463.5 top: 301.2
machine  | x0: 496.2 top: 301.2
(maintenance)Each  | x0: 523.6 top: 301.2
30,000.00  | x0: 697.1 top: 301.2
30,000.00  | x0: 799.7 top: 301.2
32  | x0: 44.3 top: 309.5
goods  | x0: 56.0 top: 309.5
15121520  | x0: 216.1 top: 309.5
0  | x0: 292.9 top: 309.5
Procurement  | x0: 362.6 top: 309.5
of  | x0: 402.9 top: 309.5
genera2l2  | x0: 410.5 top: 309.5
purpose  | x0: 434.6 top: 309.5
lubricants  | x0: 460.7 top: 309.5
Each  | x0: 567.5 top: 309.5
473,000.00  | x0: 693.3 top: 309.5
473,000.00  | x0: 795.9 top: 309.5
33  | x0: 44.3 top: 317.8
works  | x0: 56.0 top: 317.8
72131700  | x0: 216.1 top: 317.8
0  | x0: 292.9 top: 317.8
Construction  | x0: 362.6 top: 317.8
of  | x0: 402.2 top: 317.8
an  | x0: 409.8 top: 317.8
Abl2u3tion  | x0: 419.1 top: 317.8
Block  | x0: 445.1 top: 317.8
at  | x0: 463.2 top: 317.8
the  | x0: 470.7 top: 317.8
Double  | x0: 482.0 top: 317.8
Storey  | x0: 504.9 top: 317.8
Building  | x0: 526.1 top: 317.8
opposEitaec  | x0: 551.7 top: 317.8
Chhirundu  | x0: 579.0 top: 317.8
Boarder  | x0: 608.1 top: 317.8
Post  | x0: 633.9 top: 317.8
90,000.00  | x0: 697.1 top: 317.8
90,000.00  | x0: 799.7 top: 317.8
34  | x0: 44.3 top: 326.1
works  | x0: 56.0 top: 326.1
72131700  | x0: 216.1 top: 326.1
0  | x0: 292.9 top: 326.1
Construction  | x0: 362.6 top: 326.1
of  | x0: 402.2 top: 326.1
an  | x0: 409.8 top: 326.1
Aba2t4toir  | x0: 419.1 top: 326.1
Each  | x0: 567.5 top: 326.1
300,000.00  | x0: 693.3 top: 326.1
300,000.00  | x0: 795.9 top: 326.1
35  | x0: 44.3 top: 334.3
goods  | x0: 56.0 top: 334.3
25191700  | x0: 216.1 top: 334.3
0  | x0: 292.9 top: 334.3
Vehicles  | x0: 362.6 top: 334.3
maintenance2  | x0: 389.6 top: 334.3
a5nd  | x0: 430.0 top: 334.3
servicing  | x0: 443.1 top: 334.3
/plant  | x0: 471.7 top: 334.3
maintenance  | x0: 489.9 top: 334.3
Each  | x0: 567.5 top: 334.3
525,000.00  | x0: 693.3 top: 334.3
525,000.00  | x0: 795.9 top: 334.3
36  | x0: 44.3 top: 342.6
works  | x0: 56.0 top: 342.6
72131701  | x0: 216.1 top: 342.6
0  | x0: 292.9 top: 342.6
Paving  | x0: 362.6 top: 342.6
of  | x0: 385.1 top: 342.6
the  | x0: 392.6 top: 342.6
township2  | x0: 403.9 top: 342.6
6roads  | x0: 431.8 top: 342.6
(1,6km)  | x0: 450.9 top: 342.6
Each  | x0: 567.5 top: 342.6
5,240,000.00  | x0: 687.7 top: 342.6
5,240,000.00  | x0: 790.3 top: 342.6
37  | x0: 44.3 top: 350.9
works  | x0: 56.0 top: 350.9
72000000  | x0: 216.1 top: 350.9
0  | x0: 292.9 top: 350.9
Construction  | x0: 362.6 top: 350.9
of  | x0: 402.2 top: 350.9
the  | x0: 409.8 top: 350.9
com27pletion  | x0: 421.0 top: 350.9
of  | x0: 455.3 top: 350.9
Chibende  | x0: 462.8 top: 350.9
Rural  | x0: 493.4 top: 350.9
Health  | x0: 511.1 top: 350.9
Centre  | x0: 532.2 top: 350.9
undeEr  | x0: 554.2 top: 350.9
athceh  | x0: 572.0 top: 350.9
2023  | x0: 584.5 top: 350.9
CDF  | x0: 601.3 top: 350.9
funding  | x0: 616.9 top: 350.9
538,726.57  | x0: 693.3 top: 350.9
538,726.57  | x0: 795.9 top: 350.9
38  | x0: 44.3 top: 359.2
works  | x0: 56.0 top: 359.2
72000000  | x0: 216.1 top: 359.2
0  | x0: 292.9 top: 359.2
Construction  | x0: 362.6 top: 359.2
of  | x0: 402.2 top: 359.2
the  | x0: 409.8 top: 359.2
Co2m8munity  | x0: 421.0 top: 359.2
Hall  | x0: 456.8 top: 359.2
Each  | x0: 567.5 top: 359.2
2,000,000.00  | x0: 687.7 top: 359.2
2,000,000.00  | x0: 790.3 top: 359.2
39  | x0: 44.3 top: 367.5
works  | x0: 56.0 top: 367.5
71151323  | x0: 216.1 top: 367.5
0  | x0: 292.9 top: 367.5
Boreholes,pumps  | x0: 362.6 top: 367.5
and  | x0: 416.5 top: 367.5
2w9ater  | x0: 428.1 top: 367.5
reticulation  | x0: 447.8 top: 367.5
Each  | x0: 567.5 top: 367.5
290,100.00  | x0: 693.3 top: 367.5
290,100.00  | x0: 795.9 top: 367.5
40  | x0: 44.3 top: 375.7
works  | x0: 56.0 top: 375.7
71151323  | x0: 216.1 top: 375.7
0  | x0: 292.9 top: 375.7
Construction  | x0: 362.6 top: 375.7
of  | x0: 402.2 top: 375.7
a  | x0: 409.8 top: 375.7
Sola3r  | x0: 415.4 top: 375.7
0powered  | x0: 431.8 top: 375.7
Borehole  | x0: 460.2 top: 375.7
Each  | x0: 567.5 top: 375.7
800,000.00  | x0: 693.3 top: 375.7
800,000.00  | x0: 795.9 top: 375.7
41  | x0: 44.3 top: 384.0
works  | x0: 56.0 top: 384.0
72000000  | x0: 216.1 top: 384.0
0  | x0: 292.9 top: 384.0
Construction  | x0: 362.6 top: 384.0
of  | x0: 402.2 top: 384.0
(1)  | x0: 409.8 top: 384.0
Abl3u1tion  | x0: 419.9 top: 384.0
Block  | x0: 445.9 top: 384.0
at  | x0: 464.0 top: 384.0
Mission  | x0: 471.6 top: 384.0
Hospital  | x0: 496.3 top: 384.0
Each  | x0: 567.5 top: 384.0
300,000.00  | x0: 693.3 top: 384.0
300,000.00  | x0: 795.9 top: 384.0
42  | x0: 44.3 top: 392.3
works  | x0: 56.0 top: 392.3
22101603  | x0: 216.1 top: 392.3
0  | x0: 292.9 top: 392.3
Rehabilitation  | x0: 362.6 top: 392.3
of  | x0: 405.1 top: 392.3
towns3h2ip  | x0: 412.6 top: 392.3
roads  | x0: 440.9 top: 392.3
Each  | x0: 567.5 top: 392.3
200,000.00  | x0: 693.3 top: 392.3
200,000.00  | x0: 795.9 top: 392.3
43  | x0: 44.3 top: 400.6
works  | x0: 56.0 top: 400.6
72000000  | x0: 216.1 top: 400.6
0  | x0: 292.9 top: 400.6
Construction  | x0: 362.6 top: 400.6
of  | x0: 402.2 top: 400.6
a  | x0: 409.8 top: 400.6
VIP  | x0: 415.4 top: 400.6
L3a3trine  | x0: 428.0 top: 400.6
Toilet  | x0: 450.5 top: 400.6
at  | x0: 468.8 top: 400.6
M15  | x0: 476.3 top: 400.6
Checkpoint  | x0: 491.3 top: 400.6
Each  | x0: 567.5 top: 400.6
50,000.00  | x0: 697.1 top: 400.6
50,000.00  | x0: 799.7 top: 400.6
44  | x0: 44.3 top: 408.9
works  | x0: 56.0 top: 408.9
72000000  | x0: 216.1 top: 408.9
0  | x0: 292.9 top: 408.9
Construction  | x0: 362.6 top: 408.9
of  | x0: 402.2 top: 408.9
Kaban3a4na  | x0: 409.8 top: 408.9
Truckpark  | x0: 442.1 top: 408.9
Each  | x0: 567.5 top: 408.9
535,959.96  | x0: 693.3 top: 408.9
535,959.96  | x0: 795.9 top: 408.9
45  | x0: 44.3 top: 417.2
works  | x0: 56.0 top: 417.2
39111608  | x0: 216.1 top: 417.2
0  | x0: 292.9 top: 417.2
Installation  | x0: 362.6 top: 417.2
and  | x0: 396.2 top: 417.2
mainte3n5ance  | x0: 409.3 top: 417.2
of  | x0: 449.7 top: 417.2
streetlights  | x0: 457.2 top: 417.2
Each  | x0: 567.5 top: 417.2
137,700.00  | x0: 693.3 top: 417.2
137,700.00  | x0: 795.9 top: 417.2
46  | x0: 44.3 top: 425.4
goods  | x0: 56.0 top: 425.4
22101700  | x0: 216.1 top: 425.4
0  | x0: 292.9 top: 425.4
Repair  | x0: 362.6 top: 425.4
of  | x0: 384.2 top: 425.4
heavy  | x0: 391.8 top: 425.4
duty  | x0: 411.6 top: 425.4
e3q6uipment  | x0: 426.1 top: 425.4
Each  | x0: 567.5 top: 425.4
50,000.00  | x0: 697.1 top: 425.4
50,000.00  | x0: 799.7 top: 425.4
47  | x0: 44.3 top: 433.7
goods  | x0: 56.0 top: 433.7
14111509  | x0: 216.1 top: 433.7
0  | x0: 292.9 top: 433.7
Intergrity  | x0: 362.6 top: 433.7
committee  | x0: 390.6 top: 433.7
S3ta7tionery,  | x0: 423.7 top: 433.7
attires  | x0: 457.7 top: 433.7
and  | x0: 478.0 top: 433.7
accessories  | x0: 491.1 top: 433.7
Each  | x0: 567.5 top: 433.7
110,025.00  | x0: 693.3 top: 433.7
110,025.00  | x0: 795.9 top: 433.7
48  | x0: 44.3 top: 442.0
non  | x0: 56.0 top: 442.0
consulting  | x0: 69.1 top: 442.0
services  | x0: 101.1 top: 442.0
56111513  | x0: 216.1 top: 442.0
0  | x0: 292.9 top: 442.0
Conference  | x0: 362.6 top: 442.0
hiring  | x0: 399.1 top: 442.0
for  | x0: 419.5 top: 442.0
3C8ouncil  | x0: 428.1 top: 442.0
meeting  | x0: 453.3 top: 442.0
and  | x0: 479.2 top: 442.0
refreshments  | x0: 492.3 top: 442.0
for  | x0: 533.5 top: 442.0
differentE  | x0: 543.3 top: 442.0
inascthituion  | x0: 569.6 top: 442.0
meetings  | x0: 598.3 top: 442.0
270,530.00  | x0: 693.3 top: 442.0
270,530.00  | x0: 795.9 top: 442.0
49  | x0: 44.3 top: 450.3
works  | x0: 56.0 top: 450.3
93140000  | x0: 216.1 top: 450.3
0  | x0: 292.9 top: 450.3
Procurement  | x0: 362.6 top: 450.3
of  | x0: 402.9 top: 450.3
WDC  | x0: 410.5 top: 450.3
3p9rojects  | x0: 428.1 top: 450.3
in  | x0: 454.2 top: 450.3
Chirundu  | x0: 461.4 top: 450.3
West  | x0: 490.5 top: 450.3
(Community  | x0: 508.1 top: 450.3
and  | x0: 546.2 top: 450.3
SocEiaacl  | x0: 559.3 top: 450.3
hSerives)  | x0: 579.1 top: 450.3
135,875.68  | x0: 693.3 top: 450.3
135,875.68  | x0: 795.9 top: 450.3
50  | x0: 44.3 top: 458.6
works  | x0: 56.0 top: 458.6
93140000  | x0: 216.1 top: 458.6

In [54]:
# Find the row containing the text "19" that is embedded in the
# procurement description for Ref No. 29.
for word in words1:
    if "Comm" in word["text"] or "1u9nity" in word["text"]:
        print(word)

{'text': 'Comments', 'x0': 56.04, 'x1': 90.2478, 'top': 102.56599999999997, 'doctop': 102.56599999999997, 'bottom': 109.166, 'upright': True, 'height': 6.600000000000023, 'width': 34.2078, 'direction': 'ltr'}
{'text': '(Community', 'x0': 482.7032, 'x1': 518.9504, 'top': 276.356, 'doctop': 276.356, 'bottom': 282.956, 'upright': True, 'height': 6.600000000000023, 'width': 36.247199999999964, 'direction': 'ltr'}
{'text': 'Comm1u9nity', 'x0': 410.486, 'x1': 444.4628, 'top': 284.656, 'doctop': 284.656, 'bottom': 291.25600000000003, 'upright': True, 'height': 6.600000000000023, 'width': 33.976800000000026, 'direction': 'ltr'}
{'text': '(Community', 'x0': 508.0934, 'x1': 544.3406, 'top': 450.286, 'doctop': 450.286, 'bottom': 456.88599999999997, 'upright': True, 'height': 6.599999999999966, 'width': 36.24720000000002, 'direction': 'ltr'}
{'text': '(Community', 'x0': 513.842, 'x1': 550.0891999999999, 'top': 458.56600000000003, 'doctop': 458.56600000000003, 'bottom': 465.166, 'upright': True, 'height': 6.599999999999966, 'width': 36.24719999999991, 'direction': 'ltr'}
{'text': '(Community', 'x0': 522.3692, 'x1': 558.6163999999999, 'top': 466.846, 'doctop': 466.846, 'bottom': 473.446, 'upright': True, 'height': 6.600000000000023, 'width': 36.24719999999991, 'direction': 'ltr'}
{'text': '(Community', 'x0': 510.36379999999997, 'x1': 546.611, 'top': 475.126, 'doctop': 475.126, 'bottom': 481.726, 'upright': True, 'height': 6.600000000000023, 'width': 36.24720000000002, 'direction': 'ltr'}
{'text': '(CommunEitay', 'x0': 539.4038, 'x1': 575.6547999999999, 'top': 483.406, 'doctop': 483.406, 'bottom': 490.006, 'upright': True, 'height': 6.599999999999966, 'width': 36.25099999999986, 'direction': 'ltr'}
{'text': '(Community', 'x0': 520.3166, 'x1': 556.5637999999999, 'top': 491.68600000000004, 'doctop': 491.68600000000004, 'bottom': 498.286, 'upright': True, 'height': 6.599999999999966, 'width': 36.24719999999991, 'direction': 'ltr'}
{'text': '(Community', 'x0': 515.7758, 'x1': 552.0229999999999, 'top': 499.986, 'doctop': 499.986, 'bottom': 506.586, 'upright': True, 'height': 6.600000000000023, 'width': 36.24719999999991, 'direction': 'ltr'}
{'text': '(Community', 'x0': 521.8742, 'x1': 558.1214, 'top': 508.266, 'doctop': 508.266, 'bottom': 514.866, 'upright': True, 'height': 6.599999999999966, 'width': 36.24720000000002, 'direction': 'ltr'}
{'text': '(Community', 'x0': 523.6826, 'x1': 559.9298, 'top': 516.546, 'doctop': 516.546, 'bottom': 523.146, 'upright': True, 'height': 6.599999999999909, 'width': 36.24720000000002, 'direction': 'ltr'}
{'text': '(Community', 'x0': 527.5172, 'x1': 563.7643999999999, 'top': 524.826, 'doctop': 524.826, 'bottom': 531.426, 'upright': True, 'height': 6.600000000000023, 'width': 36.24719999999991, 'direction': 'ltr'}
{'text': '(CommunityE', 'x0': 533.6222, 'x1': 571.9522, 'top': 533.106, 'doctop': 533.106, 'bottom': 539.706, 'upright': True, 'height': 6.600000000000023, 'width': 38.32999999999993, 'direction': 'ltr'}

In [55]:
# Inspect all PDF words belonging to Ref No. 29
row_29_words = [
    word for word in words1
    if 282 <= word["top"] <= 293
]

for word in sorted(row_29_words, key=lambda x: x["x0"]):
    print(
        f"x0={word['x0']:.1f} | "
        f"x1={word['x1']:.1f} | "
        f"text={word['text']}"
    )

x0=44.3 | x1=51.7 | text=29
x0=44.3 | x1=51.7 | text=30
x0=56.0 | x1=73.4 | text=works
x0=56.0 | x1=74.2 | text=goods
x0=216.1 | x1=245.8 | text=93140000
x0=216.1 | x1=245.8 | text=47000000
x0=292.9 | x1=296.5 | text=0
x0=292.9 | x1=296.5 | text=0
x0=362.6 | x1=400.9 | text=Procurement
x0=362.6 | x1=400.9 | text=Procurement
x0=402.9 | x1=408.5 | text=of
x0=402.9 | x1=408.5 | text=of
x0=410.5 | x1=444.5 | text=Comm1u9nity
x0=410.5 | x1=436.7 | text=Cleani2n0g
x0=438.6 | x1=465.8 | text=materials
x0=446.3 | x1=470.6 | text=Projects
x0=467.7 | x1=475.6 | text=for
x0=472.5 | x1=489.6 | text=under
x0=477.6 | x1=486.9 | text=the
x0=488.8 | x1=517.4 | text=institution
x0=491.6 | x1=500.9 | text=the
x0=502.8 | x1=517.7 | text=2025
x0=519.3 | x1=552.9 | text=(equipment
x0=519.6 | x1=533.2 | text=CDF
x0=554.9 | x1=566.0 | text=and
x0=567.5 | x1=582.7 | text=Each
x0=567.5 | x1=594.6 | text=Esuapcphlies)
x0=685.7 | x1=726.5 | text=###########
x0=697.1 | x1=726.9 | text=51,540.00
x0=786.6 | x1=829.4 | text=18,654,678.04
x0=799.7 | x1=829.5 | text=51,540.00

SHOWING TOP ROW POSITION OF REF 29

In [56]:
# Show the unique row positions around Ref 29
tops = sorted(set(
    round(word["top"], 3)
    for word in words1
    if 275 <= word["top"] <= 300
))

print(tops)

[276.356, 284.656, 292.936]

In [57]:
# Print each row separately
for top in tops:
    print(f"\n===== TOP {top} =====")
    
    row_words = [
        word for word in words1
        if abs(word["top"] - top) < 0.1
    ]
    
    for word in sorted(row_words, key=lambda x: x["x0"]):
        print(
            f"x0={word['x0']:.1f} | "
            f"text={word['text']}"
        )

===== TOP 276.356 =====
x0=44.3 | text=28
x0=56.0 | text=works
x0=216.1 | text=93140000
x0=292.9 | text=0
x0=362.6 | text=Procurement
x0=402.9 | text=of
x0=410.5 | text=WDC
x0=428.1 | text=1p8rojects
x0=454.2 | text=in
x0=461.4 | text=Njame
x0=482.7 | text=(Community
x0=520.8 | text=and
x0=533.9 | text=Social
x0=553.9 | text=SerivEeasc)h
x0=693.3 | text=135,875.68
x0=795.9 | text=135,875.68

===== TOP 284.656 =====
x0=44.3 | text=29
x0=56.0 | text=works
x0=216.1 | text=93140000
x0=292.9 | text=0
x0=362.6 | text=Procurement
x0=402.9 | text=of
x0=410.5 | text=Comm1u9nity
x0=446.3 | text=Projects
x0=472.5 | text=under
x0=491.6 | text=the
x0=502.8 | text=2025
x0=519.6 | text=CDF
x0=567.5 | text=Each
x0=685.7 | text=###########
x0=786.6 | text=18,654,678.04

===== TOP 292.936 =====
x0=44.3 | text=30
x0=56.0 | text=goods
x0=216.1 | text=47000000
x0=292.9 | text=0
x0=362.6 | text=Procurement
x0=402.9 | text=of
x0=410.5 | text=Cleani2n0g
x0=438.6 | text=materials
x0=467.7 | text=for
x0=477.6 | text=the
x0=488.8 | text=institution
x0=519.3 | text=(equipment
x0=554.9 | text=and
x0=567.5 | text=Esuapcphlies)
x0=697.1 | text=51,540.00
x0=799.7 | text=51,540.00

In [58]:
# Show only the budget columns for Ref No. 29
row_29_budget = [
    word for word in words1
    if abs(word["top"] - 284.656) < 0.1
    and word["x0"] >= 650
]

for word in sorted(row_29_budget, key=lambda x: x["x0"]):
    print(
        f"x0={word['x0']:.1f} | "
        f"x1={word['x1']:.1f} | "
        f"text={word['text']}"
    )

x0=685.7 | x1=726.5 | text=###########
x0=786.6 | x1=829.4 | text=18,654,678.04

In [60]:
df_2025_fixed["Estimated Amount"] = (
    df_2025_fixed["Estimated Amount"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df_2025_fixed["Estimated Amount"] = pd.to_numeric(
    df_2025_fixed["Estimated Amount"],
    errors="coerce"
)

In [61]:
df_2025_fixed.loc[
    df_2025_fixed["Ref No"] == 29,
    "Estimated Amount"
] = 18654678.04

In [62]:
df_2025_fixed[
    df_2025_fixed["Ref No"] == 29
][[
    "Ref No",
    "Category",
    "Procurement item",
    "Estimated Amount",
    "Source of Funds",
    "Procurement Method",
    "date"
]]

,Ref No,Category,Procurement item,Estimated Amount,Source of Funds,Procurement Method,date
18,29,works,Procurement of Comm1u9nity Projects under the ...,18654678.04,2025 CDF,obn,2025-06-02

In [63]:
df_2025_clean = df_2025_fixed[
    [
        "Category",
        "Procurement item",
        "Estimated Amount",
        "Source of Funds",
        "Procurement Method",
        "date"
    ]
].copy()

CLEAN THE SIURCE NAMES

In [64]:
df_2025_clean["Source of Funds"] = (
    df_2025_clean["Source of Funds"]
    .str.strip()
    .replace({
        "Local resources": "Local Resource"
    })
)

CLEAN PROCUREMENT METHOD

In [65]:
df_2025_clean["Procurement Method"] = (
    df_2025_clean["Procurement Method"]
    .str.strip()
    .str.lower()
)

RESET INDEX

In [66]:
df_2025_clean = df_2025_clean.reset_index(drop=True)

FINAL QUALITY CHECK

In [67]:
print("Total records:", len(df_2025_clean))

print("\nMissing values:")
print(df_2025_clean.isna().sum())

print("\nData types:")
print(df_2025_clean.dtypes)

print("\nCategories:")
print(df_2025_clean["Category"].value_counts())

print("\nSources of Funds:")
print(df_2025_clean["Source of Funds"].value_counts())

print("\nProcurement Methods:")
print(df_2025_clean["Procurement Method"].value_counts())

print("\nDate range:")
print(df_2025_clean["date"].min(), "to", df_2025_clean["date"].max())

Total records: 50

Missing values:
Category              0
Procurement item      0
Estimated Amount      0
Source of Funds       0
Procurement Method    0
date                  0
dtype: int64

Data types:
Category                         str
Procurement item                 str
Estimated Amount             float64
Source of Funds                  str
Procurement Method               str
date                  datetime64[us]
dtype: object

Categories:
Category
works                      25
goods                      17
consulting services         4
non consulting services     4
Name: count, dtype: int64

Sources of Funds:
Source of Funds
Local Resource                 44
2025 CDF                        3
Grant                           1
Grant and locally generated     1
2023 CDF project                1
Name: count, dtype: int64

Procurement Methods:
Procurement Method
sb     44
db      3
obn     3
Name: count, dtype: int64

Date range:
2025-01-13 00:00:00 to 2025-09-08 00:00:00

In [68]:
print("CATEGORIES")
print(df_2025_clean["Category"].value_counts())

print("\nSOURCE OF FUNDS")
print(df_2025_clean["Source of Funds"].value_counts())

print("\nPROCUREMENT METHODS")
print(df_2025_clean["Procurement Method"].value_counts())

CATEGORIES
Category
works                      25
goods                      17
consulting services         4
non consulting services     4
Name: count, dtype: int64

SOURCE OF FUNDS
Source of Funds
Local Resource                 44
2025 CDF                        3
Grant                           1
Grant and locally generated     1
2023 CDF project                1
Name: count, dtype: int64

PROCUREMENT METHODS
Procurement Method
sb     44
db      3
obn     3
Name: count, dtype: int64

In [69]:
df_2025_clean.to_csv(
    "chirundu_annual_procurement_plan_2025.csv",
    sep="|",
    index=False
)

print("2025 procurement data exported successfully.")

2025 procurement data exported successfully.

In [70]:
import os

print("File:", os.path.abspath("chirundu_procurement_2025.csv"))
print("Rows exported:", len(df_2025_clean))
print("Columns:", list(df_2025_clean.columns))

File: c:\Users\Rachel\Downloads\Chirundu procurement\chirundu_procurement_2025.csv
Rows exported: 50
Columns: ['Category', 'Procurement item', 'Estimated Amount', 'Source of Funds', 'Procurement Method', 'date']